import type { CatalogEntity, Skill } from '../../../platform/engine/types.js';

// Narrow typed boundary for the generated Mesmer API metadata snapshot. The
// implementation is regenerated by scripts/data/update-mesmer-api-data.mjs and stays
// JavaScript; this declaration describes only its public shape.

export interface MesmerApiTrait extends CatalogEntity {
  readonly description: string;
  readonly icon: string;
  readonly specialization: string;
  readonly tier: number;
  readonly position: number;
}

export interface MesmerApiSpecialization extends CatalogEntity {
  readonly elite: boolean;
  readonly icon: string;
  readonly background: string;
  readonly minorTraits: readonly MesmerApiTrait[];
  readonly majorTraits: readonly (readonly MesmerApiTrait[])[];
}

export const DATA_SNAPSHOT: string;
export const SPECIALIZATIONS: readonly MesmerApiSpecialization[];
export const SKILLS: readonly Skill[];
