import type { CatalogEntity, Skill } from '../../../platform/engine/types.js';

// Narrow typed boundary for the generated Necromancer API metadata snapshot.
// The implementation is regenerated by scripts/data/update-profession-api-data.mjs
// and intentionally remains JavaScript.

export interface NecromancerApiTrait extends CatalogEntity {
  readonly description: string;
  readonly icon: string;
  readonly specialization: string;
  readonly tier: number;
  readonly position: number;
  readonly slot: string;
}

export interface NecromancerApiSpecialization extends CatalogEntity {
  readonly elite: boolean;
  readonly icon: string;
  readonly background: string;
  readonly minorTraits: readonly NecromancerApiTrait[];
  readonly majorTraits: readonly (readonly NecromancerApiTrait[])[];
}

export const DATA_SNAPSHOT: string;
export const SPECIALIZATIONS: readonly NecromancerApiSpecialization[];
export const SKILLS: readonly Skill[];
