// Generated by scripts/data/generate-warrior-data.mjs.
// Committed constants keep mechanic references independent from metadata loading.

export const WARRIOR_SKILL_IDS = Object.freeze({
  SWAP_WEAPONS: -3,
  EVISCERATE: 14353, // Eviscerate
  THROW_BOLAS: 14354, // Throw Bolas
  SIGNET_OF_RAGE: 14355, // Signet of Rage
  GREATSWORD_SWING: 14356, // Greatsword Swing
  HAMMER_SWING: 14358, // Hammer Swing
  STAGGERING_BLOW: 14359, // Staggering Blow
  RIFLE_BUTT: 14360, // Rifle Butt
  SHIELD_BASH: 14361, // Shield Bash
  SHIELD_STANCE: 14362, // Shield Stance
  HAMSTRING: 14363, // Hamstring
  SEVER_ARTERY: 14364, // Sever Artery
  GASH: 14365, // Gash
  SAVAGE_LEAP: 14366, // Savage Leap
  FRENZY: 14368, // Frenzy
  CHOP: 14369, // Chop
  DOUBLE_CHOP: 14370, // Double Chop
  TRIPLE_CHOP: 14371, // Triple Chop
  SHAKE_IT_OFF: 14372, // "Shake It Off!"
  GREATSWORD_SLICE: 14373, // Greatsword Slice
  BRUTAL_STRIKE: 14374, // Brutal Strike
  ARCING_SLICE: 14375, // Arcing Slice
  MACE_SMASH: 14376, // Mace Smash
  MACE_BASH: 14377, // Mace Bash
  PULVERIZE: 14378, // Pulverize
  ARCING_ARROW: 14381, // Arcing Arrow
  HAMMER_BASH: 14384, // Hammer Bash
  HAMMER_SMASH: 14385, // Hammer Smash
  FIERCE_BLOW: 14386, // Fierce Blow
  EARTHSHAKER: 14387, // Earthshaker
  STOMP: 14388, // Stomp
  HEALING_SIGNET: 14389, // Healing Signet
  ENDURE_PAIN: 14392, // Endure Pain
  CHARGE: 14393, // Charge
  CALL_OF_VALOR: 14394, // Call of Valor
  KILL_SHOT: 14396, // Kill Shot
  THROW_AXE: 14398, // Throw Axe
  WHIRLING_AXE: 14399, // Whirling Axe
  RIPOSTE: 14400, // Riposte
  MENDING: 14401, // Mending
  TO_THE_LIMIT: 14402, // "To the Limit!"
  FOR_GREAT_JUSTICE: 14403, // "For Great Justice!"
  SIGNET_OF_MIGHT: 14404, // Signet of Might
  BANNER_OF_STRENGTH: 14405, // Banner of Strength
  BERSERKER_STANCE: 14406, // Berserker Stance
  BANNER_OF_DISCIPLINE: 14407, // Banner of Discipline
  BANNER_OF_TACTICS: 14408, // Banner of Tactics
  FEAR_ME: 14409, // "Fear Me!"
  SIGNET_OF_FURY: 14410, // Signet of Fury
  BALANCED_STANCE: 14412, // Balanced Stance
  DOLYAK_SIGNET: 14413, // Dolyak Signet
  SKULL_CRACK: 14414, // Skull Crack
  TREMOR: 14415, // Tremor
  VOLLEY: 14416, // Volley
  DUAL_STRIKE: 14418, // Dual Strike
  BATTLE_STANDARD: 14419, // Battle Standard
  CYCLONE_AXE: 14421, // Cyclone Axe
  EVISCERATE_ID_14422: 14422, // Eviscerate
  SKULL_CRACK_ID_14425: 14425, // Skull Crack
  DUAL_SHOT: 14431, // Dual Shot
  FIERCE_SHOT: 14432, // Fierce Shot
  WHIRLING_STRIKE: 14443, // Whirling Strike
  RUSH: 14446, // Rush
  WHIRLWIND_ATTACK: 14447, // Whirlwind Attack
  FORCEFUL_SHOT: 14469, // Forceful Shot
  EXPLOSIVE_SHELL: 14472, // Explosive Shell
  KILL_SHOT_ID_14473: 14473, // Kill Shot
  KILL_SHOT_ID_14474: 14474, // Kill Shot
  KILL_SHOT_ID_14475: 14475, // Kill Shot
  SIGNET_OF_STAMINA: 14479, // Signet of Stamina
  HAMMER_SHOCK: 14482, // Hammer Shock
  RAMPAGE: 14483, // Rampage
  IMPALE: 14498, // Impale
  RIP: 14501, // Rip
  KICK: 14502, // Kick
  POMMEL_BASH: 14503, // Pommel Bash
  PIN_DOWN: 14504, // Pin Down
  SMOLDERING_ARROW: 14505, // Smoldering Arrow
  COMBUSTIVE_SHOT: 14506, // Combustive Shot
  COUNTERBLOW: 14507, // Counterblow
  BLADETRAIL: 14510, // Bladetrail
  BACKBREAKER: 14511, // Backbreaker
  EARTHSHAKER_ID_14512: 14512, // Earthshaker
  BULLS_CHARGE: 14516, // Bull's Charge
  CRUSHING_BLOW: 14518, // Crushing Blow
  FAN_OF_FIRE: 14519, // Fan of Fire
  COMBUSTIVE_SHOT_ID_14520: 14520, // Combustive Shot
  BANNER_OF_DEFENSE: 14528, // Banner of Defense
  FORCEFUL_SHOT_ID_14544: 14544, // Forceful Shot
  ARCING_SLICE_ID_14545: 14545, // Arcing Slice
  TACTICAL_BLOW: 14548, // Tactical Blow
  WHIRLING_STRIKE_ID_14549: 14549, // Whirling Strike
  HUNDRED_BLADES: 14554, // Hundred Blades
  ADRENALINE_RUSH: 14557, // Adrenaline Rush
  ON_MY_MARK: 14575, // "On My Mark!"
  DEFIANT_STANCE: 21815, // Defiant Stance
  SUNDERING_LEAP: 29613, // Sundering Leap
  GUN_FLAME: 29644, // Gun Flame
  SKULL_GRINDER: 29679, // Skull Grinder
  BLAZE_BREAKER: 29845, // Blaze Breaker
  ARC_DIVIDER: 29852, // Arc Divider
  SCORCHED_EARTH: 29923, // Scorched Earth
  FLAMES_OF_WAR: 29940, // Flames of War
  WILD_BLOW: 29941, // Wild Blow
  SHATTERING_BLOW: 30074, // Shattering Blow
  BERSERK: 30185, // Berserk
  BLOOD_RECKONING: 30189, // Blood Reckoning
  OUTRAGE: 30258, // Outrage
  HEAD_BUTT: 30343, // Head Butt
  BERSERK_ID_30435: 30435, // Berserk
  FLAMING_FLURRY: 30682, // Flaming Flurry
  DECAPITATE: 30851, // Decapitate
  RUPTURING_SMASH: 30879, // Rupturing Smash
  BURNING_SHACKLES: 30989, // Burning Shackles
  WILD_WHIRL: 31048, // Wild Whirl
  BRUTAL_SHOT: 34296, // Brutal Shot
  SILENCER: 39972, // Silencer
  KEEN_STRIKE: 40275, // Keen Strike
  FOCUSED_SLASH: 40560, // Focused Slash
  EARTHSHAKER_ID_40601: 40601, // Earthshaker
  NATURAL_HEALING: 41100, // Natural Healing
  SKULL_CRACK_ID_41110: 41110, // Skull Crack
  BOON_CRUSHER: 41283, // Boon Crusher
  FORCEFUL_SHOT_ID_41330: 41330, // Forceful Shot
  WOUNDING_STRIKE: 41543, // Wounding Strike
  WHIRLING_STRIKE_ID_41746: 41746, // Whirling Strike
  IMMINENT_THREAT: 41919, // Imminent Threat
  KILL_SHOT_ID_42041: 42041, // Kill Shot
  ARCING_SLICE_ID_42707: 42707, // Arcing Slice
  PRECISE_CUT: 42745, // Precise Cut
  COMBUSTIVE_SHOT_ID_42803: 42803, // Combustive Shot
  BREAK_ENCHANTMENTS: 43123, // Break Enchantments
  FLEETING_STABILITY: 43488, // Fleeting Stability
  EVISCERATE_ID_43566: 43566, // Eviscerate
  SIGHT_BEYOND_SIGHT: 43745, // Sight beyond Sight
  WASTRELS_RUIN: 44004, // Wastrel's Ruin
  FULL_COUNTER: 44165, // Full Counter
  DISSONANCE: 44397, // Dissonance
  DISRUPTING_STAB: 44937, // Disrupting Stab
  HUSHBLADE: 45160, // Hushblade
  BREACHING_STRIKE: 45252, // Breaching Strike
  WINDS_OF_DISENCHANTMENT: 45333, // Winds of Disenchantment
  FEATHERFOOT_GRACE: 45380, // Featherfoot Grace
  MAGEHUNTER_STRIKE: 46044, // Magehunter Strike
  AURA_SLICER: 46233, // Aura Slicer
  GUNSTINGER: 62697, // Gunstinger
  UNSHEATHE_GUNSABER: 62745, // Unsheathe Gunsaber
  DRAGONS_ROAR: 62800, // Dragon's Roar
  DRAGON_TRIGGER: 62803, // Dragon Trigger
  ELECTRIC_FENCE: 62804, // Electric Fence
  SHEATHE_GUNSABER: 62861, // Sheathe Gunsaber
  TACTICAL_RELOAD: 62901, // Tactical Reload
  DRAGONSPIKE_MINE: 62960, // Dragonspike Mine
  FLOW_STABILIZER: 62967, // Flow Stabilizer
  COMBAT_STIMULANT: 62978, // Combat Stimulant
  OVERCHARGED_CARTRIDGES: 68085, // Overcharged Cartridges
  SLICING_MAELSTROM: 69290, // Slicing Maelstrom
  BREACHING_STRIKE_ID_69297: 69297, // Breaching Strike
  BREACHING_STRIKE_ID_69433: 69433, // Breaching Strike
  LINE_BREAKER: 71860, // Line Breaker
  RAMPART_SPLITTER: 71875, // Rampart Splitter
  DEFIANT_ROAR: 71889, // Defiant Roar
  PATH_TO_VICTORY: 71922, // Path to Victory
  PATH_TO_VICTORY_ID_71932: 71932, // Path to Victory
  PATH_TO_VICTORY_ID_71950: 71950, // Path to Victory
  REVERSE_STRIKE: 72001, // Reverse Strike
  VALIANT_LEAP: 72002, // Valiant Leap
  BALANCED_STRIKE: 72024, // Balanced Strike
  SNAP_PULL: 72026, // Snap Pull
  PATH_TO_VICTORY_ID_72029: 72029, // Path to Victory
  INSPIRING_WHIRL: 72049, // Inspiring Whirl
  PATH_TO_VICTORY_ID_72089: 72089, // Path to Victory
  MAIMING_SPEAR: 72897, // Maiming Spear
  HARRIERS_TOSS: 72911, // Harrier's Toss
  MIGHTY_THROW: 72958, // Mighty Throw
  DISRUPTING_THROW: 72959, // Disrupting Throw
  SPEARMARSHALS_SUPPORT: 72992, // Spearmarshal's Support
  HARRIERS_TOSS_ID_73006: 73006, // Harrier's Toss
  SPEAR_SWIPE: 73009, // Spear Swipe
  HARRIERS_TOSS_ID_73014: 73014, // Harrier's Toss
  HARRIERS_TOSS_ID_73024: 73024, // Harrier's Toss
  HARRIERS_TOSS_ID_73042: 73042, // Harrier's Toss
  WILD_THROW: 73103, // Wild Throw
  WE_WILL_NEVER_YIELD: 76562, // "We Will Never Yield!"
  WE_SHALL_RETURN: 76755, // "We Shall Return!"
  NEVER_SURRENDER: 76769, // "Never Surrender!"
  CHANT_OF_RECUPERATION: 76782, // Chant of Recuperation
  BRACE_YOURSELVES: 76934, // "Brace Yourselves!"
  FIND_THEIR_WEAKNESS: 77040, // "Find Their Weakness!"
  ON_YOUR_KNEES: 77114, // "On Your Knees!"
  CHANT_OF_FREEDOM: 77155, // Chant of Freedom
  CHANT_OF_ACTION: 77342, // Chant of Action
  BLOODTHIRSTER: 80203, // Bloodthirster
  REND: 80247, // Rend
  BLOODTHIRSTER_ID_80252: 80252, // Bloodthirster
  BLOODTHIRSTER_ID_80263: 80263, // Bloodthirster
  SWIFT_CUT: 62966, // Swift Cut
  STEEL_DIVIDE: 62772, // Steel Divide
  EXPLOSIVE_THRUST: 62918, // Explosive Thrust
  BLOOMING_FIRE: 62930, // Blooming Fire
  ARTILLERY_SLASH: 62732, // Artillery Slash
  CYCLONE_TRIGGER: 62789, // Cyclone Trigger
  BREAK_STEP: 62885, // Break Step
  DRAGON_SLASH_FORCE: 62797, // Dragon Slash—Force
  DRAGON_SLASH_BOOST: 62980, // Dragon Slash—Boost
  DRAGON_SLASH_REACH: 62951, // Dragon Slash—Reach
  FLICKER_STEP: 62926, // Flicker Step
  TRIGGERGUARD: 62893, // Triggerguard
});

export const WARRIOR_TRAIT_IDS = Object.freeze({
  RECKLESS_DODGE: 1446, // Reckless Dodge
  BUILDING_MOMENTUM: 1448, // Building Momentum
  PINNACLE_OF_STRENGTH: 1453, // Pinnacle of Strength
  BRAVE_STRIDE: 1447, // Brave Stride
  RESTORATIVE_STRENGTH: 1451, // Restorative Strength
  PEAK_PERFORMANCE: 1444, // Peak Performance
  BODY_BLOW: 2000, // Body Blow
  FORCEFUL_GREATSWORD: 1338, // Forceful Greatsword
  GREAT_FORTITUDE: 1449, // Great Fortitude
  BERSERKERS_POWER: 1437, // Berserker's Power
  MIGHT_MAKES_RIGHT: 1454, // Might Makes Right
  AGGRESSIVE_ONSLAUGHT: 1440, // Aggressive Onslaught
  MARCHING_ORDERS: 1480, // Marching Orders
  EMPOWERED: 1485, // Empowered
  MENDING_MIGHT: 1481, // Mending Might
  LEG_SPECIALIST: 1469, // Leg Specialist
  SOLDIERS_COMFORT: 1474, // Soldier's Comfort
  ROARING_REVEILLE: 1471, // Roaring Reveille
  WARRIORS_CUNNING: 1486, // Warrior's Cunning
  SHRUG_IT_OFF: 1479, // Shrug It Off
  EMPOWER_ALLIES: 1482, // Empower Allies
  MARTIAL_CADENCE: 1667, // Martial Cadence
  VIGOROUS_SHOUTS: 1470, // Vigorous Shouts
  PHALANX_STRENGTH: 1711, // Phalanx Strength
  PRIMAL_RAGE: 1831, // Primal Rage
  BURST_OF_AGGRESSION: 1993, // Burst of Aggression
  FATAL_FRENZY: 2046, // Fatal Frenzy
  SMASH_BRAWLER: 2049, // Smash Brawler
  LAST_BLAZE: 2039, // Last Blaze
  SAVAGE_INSTINCT: 1977, // Savage Instinct
  BLOOD_REACTION: 2011, // Blood Reaction
  HEAT_THE_SOUL: 2042, // Heat the Soul
  DEAD_OR_ALIVE: 2002, // Dead or Alive
  BLOODY_ROAR: 1928, // Bloody Roar
  KING_OF_FIRES: 2038, // King of Fires
  ETERNAL_CHAMPION: 2307, // Eternal Champion
  THICK_SKIN: 1350, // Thick Skin
  ADRENAL_HEALTH: 1348, // Adrenal Health
  HARDENED_ARMOR: 1380, // Hardened Armor
  SHIELD_MASTER: 1376, // Shield Master
  DOGGED_MARCH: 1488, // Dogged March
  CULL_THE_WEAK: 1372, // Cull the Weak
  DEFY_PAIN: 1368, // Defy Pain
  RESILIENT_ROLL: 1379, // Resilient Roll
  MERCILESS_HAMMER: 1367, // Merciless Hammer
  LAST_STAND: 1375, // Last Stand
  CLEANSING_IRE: 1649, // Cleansing Ire
  STALWART_STRENGTH: 1708, // Stalwart Strength
  FURIOUS_BURST: 1342, // Furious Burst
  DEEP_STRIKES: 1343, // Deep Strikes
  BLOODLUST: 1337, // Bloodlust
  WOUNDING_PRECISION: 1455, // Wounding Precision
  SIGNET_MASTERY: 1344, // Signet Mastery
  OPPORTUNIST: 1334, // Opportunist
  UNSUSPECTING_FOE: 1315, // Unsuspecting Foe
  SUNDERING_BURST: 1316, // Sundering Burst
  BLADEMASTER: 1333, // Blademaster
  BURST_PRECISION: 1336, // Burst Precision
  FURIOUS: 1346, // Furious
  DUAL_WIELDING: 1707, // Dual Wielding
  VERSATILE_RAGE: 1415, // Versatile Rage
  FAST_HANDS: 1416, // Fast Hands
  VERSATILE_POWER: 1417, // Versatile Power
  CRACK_SHOT: 1329, // Crack Shot
  WARRIORS_SPRINT: 1413, // Warrior's Sprint
  STALWART_FOCUS: 1381, // Stalwart Focus
  DOUBLED_STANDARDS: 1484, // Doubled Standards
  DESTRUCTION_OF_THE_EMPOWERED: 1489, // Destruction of the Empowered
  BRAWLERS_RECOVERY: 1709, // Brawler's Recovery
  AXE_MASTERY: 1369, // Axe Mastery
  HEIGHTENED_FOCUS: 1317, // Heightened Focus
  BURST_MASTERY: 1657, // Burst Mastery
  SPELLBREAKERS_CONVICTION: 2175, // Spellbreaker's Conviction
  DISPELLING_FORCE: 2162, // Dispelling Force
  ATTACKERS_INSIGHT: 2130, // Attacker's Insight
  PURE_STRIKE: 2107, // Pure Strike
  GUARD_COUNTER: 2153, // Guard Counter
  NO_ESCAPE: 2140, // No Escape
  LOSS_AVERSION: 2126, // Loss Aversion
  RESILIENT_COUNTER: 2097, // Resilient Counter
  SUN_AND_MOON_STYLE: 2095, // Sun and Moon Style
  ENCHANTMENT_COLLAPSE: 2163, // Enchantment Collapse
  RESOLUTE_COUNTER: 2168, // Resolute Counter
  MAGEBANE_TETHER: 2060, // Magebane Tether
  GUN_X_SWORD: 2226, // Gun X Sword
  DRAGONSCALE_DEFENSE: 2242, // Dragonscale Defense
  GUNS_AND_GLORY: 2236, // Guns and Glory
  UNSEEN_SWORD: 2225, // Unseen Sword
  SHARP_AS_THE_WIND: 2260, // Sharp as the Wind
  RIVERS_FLOW: 2237, // River's Flow
  UNSHAKABLE_MOUNTAIN: 2253, // Unshakable Mountain
  FIERCE_AS_FIRE: 2302, // Fierce as Fire
  LUSH_FOREST: 2303, // Lush Forest
  IMMORTAL_DRAGON: 2261, // Immortal Dragon
  UNYIELDING_DRAGON: 2239, // Unyielding Dragon
  DARING_DRAGON: 2245, // Daring Dragon
  RALLY_THE_VALIANT: 2373, // Rally the Valiant
  INSPIRING_IMPLEMENTS: 2418, // Inspiring Implements
  UNYIELDING_RESOLVE: 2340, // Unyielding Resolve
  CALL_TO_ACTION: 2345, // Call to Action
  CALMING_TONGUE: 2433, // Calming Tongue
  LIBERATING_LIAISE: 2357, // Liberating Liaise
  STRENGTHENING_STANZAS: 2385, // Strengthening Stanzas
  INVIGORATING_TEMPO: 2426, // Invigorating Tempo
  REVERBERATION: 2399, // Reverberation
  FEVERISH_PULSE: 2369, // Feverish Pulse
  BRISK_PACING: 2375, // Brisk Pacing
  ENDURING_REFRAIN: 2428, // Enduring Refrain
});

export const WARRIOR_SPECIALIZATION_IDS = Object.freeze({
  STRENGTH: 4, // Strength
  TACTICS: 11, // Tactics
  BERSERKER: 18, // Berserker
  DEFENSE: 22, // Defense
  ARMS: 36, // Arms
  DISCIPLINE: 51, // Discipline
  SPELLBREAKER: 61, // Spellbreaker
  BLADESWORN: 68, // Bladesworn
  PARAGON: 74, // Paragon
});
