/**
 * Conduit skill mechanics owned by the Conduit Revenant module.
 */
import { REVENANT_SKILL_IDS as ID } from "../../data/ids.js";
import type { SkillFragment } from "../../../../platform/engine/types.js";

export const CONDUIT_BASE_SKILL_MECHANICS: Readonly<
  Record<number, SkillFragment>
> = Object.freeze({
  [ID.BEGUILING_HAZE_ID_76805]: {
    implemented: true,
    handlerId: "revenant.beguiling-haze",
    castTimeMs: 250,
    cooldown: 10,
    recharge: 0,
    ammo: 1,
    ammoRecharge: 10,
    energyCost: 20,
    freeWhenStatePositive: "beguilingHazeCharges",
    effects: [],
    legendId: "LegendaryEntity",
  },
  [ID.FORM_OF_THE_DERVISH_ATTACK]: {
    implemented: true,
    castTimeMs: 0,
    cooldown: 0,
    energyCost: 0,
    effects: [
      {
        type: "strike",
        coefficient: 0.8,
        hits: 1,
        name: "Form of the Dervish (Attack)",
        actorType: "player",
      },
    ],
  },
  [ID.BEGUILING_HAZE_ID_76917]: {
    implemented: true,
    handlerId: "revenant.beguiling-haze",
    castTimeMs: 250,
    cooldown: 10,
    recharge: 0,
    ammo: 1,
    ammoRecharge: 10,
    energyCost: 20,
    freeWhenStatePositive: "beguilingHazeCharges",
    effects: [],
    legendId: "LegendaryEntity",
  },
  [ID.TWIN_MOON_SWEEP]: {
    implemented: true,
    handlerId: "revenant.twin-moon-sweep",
    castTimeMs: 1250,
    quicknessCastTimeMs: 920,
    cooldown: 3,
    energyCost: 25,
    affinityOnHit: true,
    finisherType: "Whirl",
    finisherValue: 1,
    effects: [],
    legendId: "LegendaryEntity",
  },
  [ID.TWIN_MOON_SWEEP_ID_77001]: {
    implemented: true,
    handlerId: "revenant.twin-moon-sweep",
    castTimeMs: 1250,
    quicknessCastTimeMs: 920,
    cooldown: 3,
    energyCost: 25,
    affinityOnHit: true,
    finisherType: "Whirl",
    finisherValue: 1,
    effects: [],
    legendId: "LegendaryEntity",
  },
  [ID.SHIELDING_HANDS]: {
    implemented: true,
    castTimeMs: 1500,
    cooldown: 30,
    energyCost: 5,
    effects: [],
    legendId: "LegendaryEntity",
  },
  [ID.FORM_OF_THE_DERVISH_ATTACK_ELITE]: {
    implemented: true,
    castTimeMs: 0,
    cooldown: 0,
    energyCost: 0,
    effects: [
      {
        type: "strike",
        coefficient: 0.8,
        hits: 1,
        name: "Form of the Dervish (Attack - Elite)",
        actorType: "player",
      },
    ],
  },
  [ID.BEGUILING_HAZE]: {
    implemented: true,
    handlerId: "revenant.beguiling-haze",
    castTimeMs: 250,
    cooldown: 10,
    recharge: 0,
    ammo: 1,
    ammoRecharge: 10,
    energyCost: 20,
    freeWhenStatePositive: "beguilingHazeCharges",
    effects: [],
    legendId: "LegendaryEntity",
  },
  [ID.BEGUILING_HAZE_ID_77159]: {
    implemented: true,
    handlerId: "revenant.beguiling-haze",
    castTimeMs: 250,
    cooldown: 10,
    recharge: 0,
    ammo: 1,
    ammoRecharge: 10,
    energyCost: 20,
    freeWhenStatePositive: "beguilingHazeCharges",
    effects: [],
    legendId: "LegendaryEntity",
  },
  [ID.HEX_EATER_VORTEX]: {
    implemented: true,
    handlerId: "revenant.hex-eater-vortex",
    castTimeMs: 520,
    quicknessCastTimeMs: 526,
    cooldown: 5,
    energyCost: 15,
    effects: [],
    legendId: "LegendaryEntity",
  },
  [ID.GLADIATORS_DEFENSE]: {
    implemented: true,
    handlerId: "revenant.gladiators-defense",
    castTimeMs: 40,
    defaultInterruptMs: 40,
    cooldown: 5,
    energyCost: 10,
    effects: [],
    legendId: "LegendaryEntity",
  },
  [ID.COSMIC_WISDOM]: {
    implemented: true,
    handlerId: "revenant.cosmic-wisdom",
    castTimeMs: 0,
    cooldown: 20,
    energyCost: 0,
    effects: [],
  },
  [ID.DWARVEN_RETRIBUTION]: {
    implemented: true,
    castTimeMs: 0,
    cooldown: 0,
    energyCost: 0,
    effects: [
      {
        type: "strike",
        coefficient: 1.1,
        hits: 1,
        name: "Dwarven Retribution",
        actorType: "player",
      },
    ],
  },
  [ID.RELEASE_POTENTIAL_MONK]: {
    implemented: true,
    handlerId: "revenant.release-potential",
    castTimeMs: 500,
    cooldown: 10,
    energyCost: 0,
    effects: [],
  },
  [ID.RELEASE_POTENTIAL_MESMER]: {
    implemented: true,
    handlerId: "revenant.release-potential",
    castTimeMs: 500,
    quicknessCastTimeMs: 440,
    cooldown: 10,
    energyCost: 0,
    effects: [],
  },
  [ID.RELEASE_POTENTIAL_DERVISH]: {
    implemented: true,
    handlerId: "revenant.release-potential",
    castTimeMs: 750,
    quicknessCastTimeMs: 680,
    cooldown: 10,
    energyCost: 0,
    effects: [],
  },
  [ID.RELEASE_POTENTIAL_ASSASSIN]: {
    implemented: true,
    handlerId: "revenant.release-potential",
    castTimeMs: 750,
    quicknessCastTimeMs: 740,
    cooldown: 10,
    energyCost: 0,
    effects: [],
  },
  [ID.RELEASE_POTENTIAL_WARRIOR]: {
    implemented: true,
    handlerId: "revenant.release-potential",
    castTimeMs: 750,
    cooldown: 10,
    energyCost: 0,
    effects: [],
  },
  [ID.LESSER_ENCHANTED_DAGGERS]: {
    implemented: true,
    castTimeMs: 0,
    cooldown: 0,
    energyCost: 0,
    effects: [
      {
        type: "strike",
        coefficient: 0.06,
        hits: 1,
        name: "Lesser Enchanted Daggers",
        actorType: "player",
      },
    ],
  },
});
