// Generated by scripts/data/generate-ranger-ids.mjs.
// Committed constants keep mechanic references independent from metadata loading.

export const RANGER_SKILL_IDS = Object.freeze({
  DODGE: -5,
  PET_SWAP: -4,
  SWAP_WEAPONS: -3,
  PATH_OF_SCARS_MAX_RANGE: -1001,
  RICOCHET: 12466, // Ricochet
  POISON_VOLLEY: 12468, // Poison Volley
  BARRAGE: 12469, // Barrage
  CROSSFIRE: 12470, // Crossfire
  SLASH: 12471, // Slash
  CRIPPLING_THRUST: 12472, // Crippling Thrust
  PRECISION_SWIPE: 12473, // Precision Swipe
  SLASH_ID_12474: 12474, // Slash
  HILT_BASH: 12475, // Hilt Bash
  SPIKE_TRAP: 12476, // Spike Trap
  CRIPPLING_TALON: 12477, // Crippling Talon
  STALKERS_STRIKE: 12478, // Stalker's Strike
  SPLITBLADE: 12480, // Splitblade
  SERPENTS_STRIKE: 12482, // Serpent's Strike
  TROLL_UNGUENT: 12483, // Troll Unguent
  SLICE: 12487, // Slice
  ENDURING_SWING: 12488, // Enduring Swing
  HEALING_SPRING: 12489, // Healing Spring
  WINTERS_BITE: 12490, // Winter's Bite
  SIGNET_OF_THE_WILD: 12491, // Signet of the Wild
  FROST_TRAP: 12492, // Frost Trap
  STORM_SPIRIT: 12493, // Storm Spirit
  LIGHTNING_REFLEXES: 12494, // Lightning Reflexes
  STONE_SPIRIT: 12495, // Stone Spirit
  VIPERS_NEST: 12496, // Viper's Nest
  FROST_SPIRIT: 12497, // Frost Spirit
  SUN_SPIRIT: 12498, // Sun Spirit
  FLAME_TRAP: 12499, // Flame Trap
  SIGNET_OF_STONE: 12500, // Signet of Stone
  MUDDY_TERRAIN: 12501, // Muddy Terrain
  SIGNET_OF_RENEWAL: 12502, // Signet of Renewal
  BONFIRE: 12504, // Bonfire
  CRIPPLING_SHOT: 12507, // Crippling Shot
  CONCUSSION_SHOT: 12508, // Concussion Shot
  RAPID_FIRE: 12509, // Rapid Fire
  LONG_RANGE_SHOT: 12510, // Long Range Shot
  POINT_BLANK_SHOT: 12511, // Point-Blank Shot
  STRENGTH_OF_THE_PACK: 12516, // "Strength of the Pack!"
  QUICK_SHOT: 12517, // Quick Shot
  SWOOP: 12521, // Swoop
  COUNTERATTACK: 12522, // Counterattack
  COUNTERATTACK_KICK: 12523, // Counterattack Kick
  MAUL: 12525, // Maul
  SHARPENING_STONE: 12537, // Sharpening Stone
  SIGNET_OF_THE_HUNT: 12542, // Signet of the Hunt
  QUICKENING_ZEPHYR: 12550, // Quickening Zephyr
  SPIRIT_OF_NATURE: 12569, // Spirit of Nature
  HUNTERS_SHOT: 12573, // Hunter's Shot
  ENTANGLE: 12580, // Entangle
  SOLAR_FLARE: 12597, // Solar Flare
  CALL_LIGHTNING: 12598, // Call Lightning
  QUAKE: 12599, // Quake
  COLD_SNAP: 12600, // Cold Snap
  NATURES_RENEWAL: 12601, // Nature's Renewal
  HUNTERS_CALL: 12620, // Hunter's Call
  CALL_OF_THE_WILD: 12621, // Call of the Wild
  PROTECT_ME: 12631, // "Protect Me!"
  GUARD: 12632, // "Guard!"
  SIC_EM: 12633, // "Sic 'Em!"
  THROW_TORCH: 12635, // Throw Torch
  PATH_OF_SCARS: 12638, // Path of Scars
  WHIRLING_DEFENSE: 12639, // Whirling Defense
  FELINE_SLASH: 12655, // Slash (feline pet AI)
  FELINE_MAUL: 12657, // Maul (feline pet AI)
  TWIN_DARTS: 12676, // Twin Darts
  PET_TAIL_LASH: 12673, // Tail Lash (pet AI)
  FELINE_BITE: 12694, // Bite (feline pet AI)
  SPIT: 12724, // Spit
  WATER_SPIRIT: 21773, // Water Spirit
  AQUA_SURGE: 21776, // Aqua Surge
  GLYPH_OF_THE_TIDES: 30238, // Glyph of the Tides
  GLYPH_OF_ALIGNMENT: 31322, // Glyph of Alignment
  GLYPH_OF_REJUVENATION: 31407, // Glyph of Rejuvenation
  RELEASE_CELESTIAL_AVATAR: 31411, // Release Celestial Avatar
  SUBLIME_CONVERSION: 31496, // Sublime Conversion
  ANCESTRAL_GRACE: 31535, // Ancestral Grace
  GLYPH_OF_BURGEONING: 31582, // Glyph of Burgeoning
  GLYPH_OF_THE_STARS: 31677, // Glyph of the Stars
  VINE_SURGE: 31700, // Vine Surge
  SOLAR_BEAM: 31710, // Solar Beam
  GLYPH_OF_EQUALITY: 31746, // Glyph of Equality
  CELESTIAL_AVATAR: 31869, // Celestial Avatar
  ASTRAL_WISP: 31889, // Astral Wisp
  WE_HEAL_AS_ONE: 31914, // "We Heal As One!"
  SEARCH_AND_RESCUE: 34309, // "Search and Rescue!"
  NARCOTIC_SPORES: 40111, // Narcotic Spores
  SMOKE_ASSAULT: 40255, // Smoke Assault
  LEADING_SWIPE: 40301, // Leading Swipe
  VULTURE_STANCE: 40498, // Vulture Stance
  PRIMAL_CRY: 40588, // Primal Cry
  BITE: 40625, // Bite
  WORLDLY_IMPACT: 40729, // Worldly Impact
  RAIN_OF_SPIKES: 41206, // Rain of Spikes
  MAUL_ID_41406: 41406, // Maul
  DEVOURER_RETREAT: 41461, // Devourer Retreat
  KICK: 41524, // Kick
  CHOMP: 41537, // Chomp
  TAIL_SWIPE: 41575, // Tail Swipe
  SERPENT_STAB: 41800, // Serpent Stab
  DARK_WATER: 41837, // Dark Water
  WING_BUFFET: 41908, // Wing Buffet
  QUICKENING_SCREECH: 42042, // Quickening Screech
  PROTECTION: 42717, // Protection
  CHARGING_BITE: 42797, // Charging Bite
  WORLDLY_IMPACT_ID_42809: 42809, // Worldly Impact
  BRUTAL_CHARGE: 42894, // Brutal Charge
  TAKEDOWN: 42907, // Takedown
  BEASTMODE: 42944, // Beastmode
  LEAVE_BEASTMODE: 43014, // Leave Beastmode
  DEFY_PAIN: 43060, // Defy Pain
  TAIL_LASH: 43068, // Tail Lash
  BITE_ID_43136: 43136, // Bite
  HEALING_CLOUD: 43186, // Healing Cloud
  PRELUDE_LASH: 43375, // Prelude Lash
  DOUBLE_ARC: 43536, // Double Arc
  FRENZIED_ATTACK: 43548, // Frenzied Attack
  POISON_GAS: 43671, // Poison Gas
  PHOTOSYNTHESIZE: 43701, // Photosynthesize
  CRIPPLING_LEAP: 43726, // Crippling Leap
  CALL_LIGHTNING_ID_43788: 43788, // Call Lightning
  ENTANGLING_WEB: 44097, // Entangling Web
  DEADLY_DELIVERY: 44278, // Deadly Delivery
  FEAR: 44360, // Fear
  CRIPPLING_ANGUISH: 44384, // Crippling Anguish
  MAUL_ID_44514: 44514, // Maul
  HARMONIC_CRY: 44617, // Harmonic Cry
  SPIRITUAL_REPRIEVE: 44626, // Spiritual Reprieve
  CHOMP_ID_44885: 44885, // Chomp
  BEAR_STANCE: 44948, // Bear Stance
  SWOOP_ID_44991: 44991, // Swoop
  GRIFFON_STANCE: 45142, // Griffon Stance
  GROUNDWORK_GOUGE: 45426, // Groundwork Gouge
  SHARPEN_SPINES: 45479, // Sharpen Spines
  ONE_WOLF_PACK: 45717, // One Wolf Pack
  ONE_WOLF_PACK_STRIKE: 42145,
  LESSER_SIC_EM: 79348,
  CHARGE: 45743, // Charge
  DOLYAK_STANCE: 45789, // Dolyak Stance
  UNFLINCHING_FORTITUDE: 45797, // Unflinching Fortitude
  MOA_STANCE: 45970, // Moa Stance
  INSTINCTIVE_ENGAGE: 46123, // Instinctive Engage
  TAIL_LASH_ID_46386: 46386, // Tail Lash
  BRUTAL_CHARGE_ID_46432: 46432, // Brutal Charge
  MAUL_ID_46629: 46629, // Maul
  ETERNAL_BOND: 59554, // Eternal Bond
  ENVELOPING_HAZE: 63094, // Enveloping Haze
  HAMMER_STRIKE: 63118, // Hammer Strike
  NATURES_BINDING: 63130, // Nature's Binding
  UNLEASHED_SAVAGE_SHOCK_WAVE: 63131, // Unleashed Savage Shock Wave
  UNLEASH_RANGER: 63147, // Unleash Ranger
  EXPLODING_SPORES: 63157, // Exploding Spores
  FORESTS_FORTIFICATION: 63163, // Forest's Fortification
  UNNATURAL_TRAVERSAL: 63195, // Unnatural Traversal
  UNLEASHED_OVERBEARING_SMASH: 63197, // Unleashed Overbearing Smash
  OVERBEARING_SMASH_SECOND_STRIKE: 63201,
  UNLEASHED_THUMP: 63208, // Unleashed Thump
  VENOMOUS_OUTBURST: 63209, // Venomous Outburst
  HAMMER_SLAM: 63222, // Hammer Slam
  MUTATE_CONDITIONS: 63256, // Mutate Conditions
  RENDING_VINES: 63258, // Rending Vines
  PERILOUS_GIFT: 63319, // Perilous Gift
  UNLEASHED_WILD_SWING: 63335, // Unleashed Wild Swing
  DEFT_STRIKE: 63336, // Deft Strike
  HEAVY_SMASH: 63337, // Heavy Smash
  EXPLODING_SPORE: 63352, // Exploding Spore
  UNLEASH_PET: 63344, // Unleash Pet
  RELENTLESS_WHIRL: 63438, // Relentless Whirl
  DASH: 64038, // Dash
  SLAM: 64699, // Slam
  UNDEAD_PLAGUE: 64882, // Undead Plague
  HEAVY_SHOT: 66258, // Heavy Shot
  PHASE_POUNCE: 67382, // Phase Pounce
  WILD_SWING: 69167, // Wild Swing
  POUNCE: 69203, // Pounce
  THUMP: 69212, // Thump
  OVERBEARING_SMASH: 69262, // Overbearing Smash
  SAVAGE_SHOCK_WAVE: 69340, // Savage Shock Wave
  LEY_LINE_VORTEX: 70889, // Ley-Line Vortex
  LUNGE: 71282, // Lunge
  ELECTROCUTE: 71499, // Electrocute
  SPIT_GOOP: 71546, // Spit Goop
  WILD_STRIKES: 71841, // Wild Strikes
  CULTIVATE: 71885, // Cultivate
  THISTLEGUARD: 71903, // Thistleguard
  OAKEN_CUDGEL: 71963, // Oaken Cudgel
  FLOURISH: 71999, // Flourish
  BURGEON: 72044, // Burgeon
  GERMINATE: 72088, // Germinate
  TORMENTING_VISIONS: 72636, // Tormenting Visions
  STARING_VOID: 72851, // Staring Void
  BEES_STING: 72920, // Bee's Sting
  DRAKES_SWIPE: 72922, // Drake's Swipe
  FALCONS_STOOP: 72928, // Falcon's Stoop
  PANTHERS_PROWL: 73008, // Panther's Prowl
  WARCLAWS_ENGAGE: 73020, // Warclaw's Engage
  PREDATORS_AMBUSH: 73150, // Predator's Ambush
  CHEETAHS_STRIKE: 73087, // Cheetah's Strike
  MONGOOSES_FRENZY: 73110, // Mongoose's Frenzy
  WYVERNS_LASH: 73112, // Wyvern's Lash
  BATTLE_MAUL: 73733, // Battle Maul
  BOP: 73938, // Bop
  BUMBLE: 75771, // Bumble
  STINGING_SORROW: 75814, // Stinging Sorrow
  WHIRLWIND: 76619, // Whirlwind
  MISTRAL: 76757, // Mistral
  SUMMON_CYCLONE_BOW: 76787, // Summon Cyclone Bow
  PERFECT_STORM: 76979, // Perfect Storm
  WIND_SHEAR: 77211, // Wind Shear
  DISMISS_CYCLONE_BOW: 77213, // Dismiss Cyclone Bow
  PIERCING_GALES: 77264, // Piercing Gales
  SOOTHING_BREEZE: 77271, // Soothing Breeze
  LEAPING_LIZARD: 78091, // Leaping Lizard
  SAURIAN_MIGHT: 79203, // Saurian Might
  TAIL_WHIP: 80031, // Tail Whip
  JET: 80035, // Jet
  MIGHTY_ROAR: 12658, // Mighty Roar
  FORAGE_ROCK: 12754, // Forage Rock
  RENDING_POUNCE: 12680, // Rending Pounce
  INTIMIDATING_HOWL: 12715, // Intimidating Howl
  SHAKE_IT_OFF: 12666, // Shake It Off
  PURGE_CONDITIONS: 12691, // Purge Conditions
  POISONOUS_CLOUD: 12675, // Poisonous Cloud
  REGENERATE: 12703, // Regenerate
  FIRE_BREATH: 12670, // Fire Breath
  BOIL: 12695, // Boil
  CHILLING_HOWL: 12716, // Chilling Howl
  ICY_POUNCE: 12693, // Icy Pounce
  ICY_BITE: 12656, // Icy Bite
  BLINDING_SLASH: 12723, // Blinding Slash
  STALK: 12681, // Stalk
  INSECT_SWARM: 12701, // Insect Swarm
  POISON_CLOUD: 12700, // Poison Cloud
  PROTECTING_SCREECH: 12713, // Protecting Screech
  ICY_SCREECH: 12711, // Icy Screech
  DAZING_SCREECH: 12708, // Dazing Screech
  DAZING_SCREECH_ID_12709: 12709, // Dazing Screech
  FURIOUS_SCREECH: 12712, // Furious Screech
  FROST_BREATH: 12696, // Frost Breath
  FROST_NOVA: 12697, // Frost Nova
  LIGHTNING_BREATH: 12698, // Lightning Breath
  ELECTROCUTE_ID_12699: 12699, // Electrocute
  POISON_CLOUD_ID_12687: 12687, // Poison Cloud
  POISONOUS_MAUL: 12690, // Poisonous Maul
  FEEDING_FRENZY: 12757, // Feeding Frenzy
  REGENERATE_ID_12717: 12717, // Regenerate
  ENFEEBLING_MAUL: 12688, // Enfeebling Maul
  ENFEEBLING_ROAR: 12685, // Enfeebling Roar
  ICY_ROAR: 12667, // Icy Roar
  ICY_MAUL: 12689, // Icy Maul
  RENDING_MAUL: 12664, // Rending Maul
  POISON_CLOUD_ID_12702: 12702, // Poison Cloud
  POISON_BARBS: 12674, // Poison Barbs
  LASHTAIL_VENOM: 12704, // Lashtail Venom
  RENDING_BARBS: 12679, // Rending Barbs
  HOWL_OF_THE_PACK: 12718, // Howl of the Pack
  TERRIFYING_HOWL: 12714, // Terrifying Howl
  CHILLING_SLASH: 12721, // Chilling Slash
  BRASH_SLASH: 12722, // Brash Slash
  DEADLY_VENOM: 12731, // Deadly Venom
  PARALYZING_VENOM: 12729, // Paralyzing Venom
  WEAKENING_VENOM: 12730, // Weakening Venom
  FORAGE_SCALE: 12755, // Forage Scale
  FORAGE_FEATHERS: 12756, // Forage Feathers
  FORAGE_SWORD: 12732, // Forage Sword
  STUNNING_RUSH: 12744, // Stunning Rush
  CHILLING_WHIRL: 12748, // Chilling Whirl
  IMMOBILIZING_WHIRL: 12749, // Immobilizing Whirl
  LACERATING_SLASH: 20975, // Lacerating Slash
  SONIC_SHRIEK: 16426, // Sonic Shriek
  SONIC_BARRIER: 16427, // Sonic Barrier
  SMOKE_CLOUD: 31568, // Smoke Cloud
  FURIOUS_POUNCE: 31451, // Furious Pounce
  LIGHTNING_ASSAULT: 31639, // Lightning Assault
  CONSUMING_FLAME: 31459, // Consuming Flame
  SPIKE_BARRAGE: 31367, // Spike Barrage
  SAVANNAH_STRIKE: 42963, // Savannah Strike
  BLINDING_ROAR: 42180, // Blinding Roar
  JACARANDAS_EMBRACE: 44980, // Jacaranda's Embrace
  JACARANDA_ROOT_SLAP: 45990, // Root Slap (Jacaranda pet AI)
  JACARANDA_CALL_LIGHTNING: 40487, // Call Lightning (Jacaranda pet AI)
  HEAD_TOSS: 43636, // Head Toss
  FANG_GRAPPLE: 41156, // Fang Grapple
  CRIPPLING_ANGUISH_PET: 41864, // Crippling Anguish (pet AI)
  CONSUMING_BITE: 43734, // Consuming Bite
  NARCOTIC_SPORES_PET: 45262, // Narcotic Spores (pet AI)
  GUARDIANS_ROAR: 65109, // Guardian's Roar
  BLOODTHIRSTY_CHARGE: 66622, // Bloodthirsty Charge
  GALE_BREATH: 63716, // Gale Breath
  HUNKER_DOWN: 65418, // Hunker Down
  DIMENSION_BREACH: 71002, // Dimension Breach
  LEY_ENERGY_PULSE: 71688, // Ley Energy Pulse
  PANOPTICON: 72843, // Panopticon
  RALLYING_ROAR: 74314, // Rallying Roar
  HONEY_TOSS: 75783, // Honey Toss
  PIERCING_SHRIEK: 78873, // Piercing Shriek
  INNOCENT_DISPLAY: 79766, // Innocent Display
  COSMIC_RAY: 31796, // Cosmic Ray
  SEED_OF_LIFE: 31406, // Seed of Life
  LUNAR_IMPACT: 31318, // Lunar Impact
  REJUVENATING_TIDES: 31894, // Rejuvenating Tides
  NATURAL_CONVERGENCE: 31503, // Natural Convergence
  KEEN_SHOT: 77183, // Keen Shot
  HAWKEYE: 76664, // Hawkeye
  BLUSTER: 77319, // Bluster
  FLEETING_ZEPHYR: 77012, // Fleeting Zephyr
  QUARRYS_PERIL: 76807, // Quarry's Peril (PvE)
  PELT: 76722, // Pelt
  SUPERSONIC_ARROW: 77174, // Supersonic Arrow
  WUTHERING_WIND: 76905, // Wuthering Wind
});

export const RANGER_TRAIT_IDS = Object.freeze({
  CELESTIAL_BEING: 1874, // Celestial Being
  LIVE_VICARIOUSLY: 1862, // Live Vicariously
  NATURAL_MENDER: 1992, // Natural Mender
  DRUIDIC_CLARITY: 1868, // Druidic Clarity
  VERDANT_ETCHING: 2016, // Verdant Etching
  BLOOD_MOON: 1935, // Blood Moon
  CELESTIAL_SHADOW: 2053, // Celestial Shadow
  GRACE_OF_THE_LAND: 2001, // Grace of the Land
  NATURAL_BALANCE: 2056, // Natural Balance
  CULTIVATED_SYNERGY: 2057, // Cultivated Synergy
  LINGERING_LIGHT: 2058, // Lingering Light
  ECLIPSE: 2055, // Eclipse
  OPENING_STRIKE: 1010, // Opening Strike
  ALPHA_FOCUS: 1009, // Alpha Focus
  PRECISE_STRIKE: 1011, // Precise Strike
  STONEFORM: 1021, // Stoneform
  HUNTERS_GAZE: 1014, // Hunter's Gaze
  CLARION_BOND: 986, // Clarion Bond
  WOLFSONG: 1001, // Wolfsong
  FARSIGHTED: 1000, // Farsighted
  MOMENT_OF_CLARITY: 1070, // Moment of Clarity
  PREDATORS_ONSLAUGHT: 996, // Predator's Onslaught
  REMORSELESS: 1015, // Remorseless
  LEAD_THE_WIND: 1698, // Lead the Wind
  REJUVENATION: 1055, // Rejuvenation
  FORTIFYING_BOND: 1056, // Fortifying Bond
  LINGERING_MAGIC: 1059, // Lingering Magic
  BOUNTIFUL_HUNTER: 1062, // Bountiful Hunter
  WELLSPRING: 978, // Wellspring
  ALLIES_AID: 1060, // Allies' Aid
  EVASIVE_PURITY: 1054, // Evasive Purity
  SPIRITED_ARRIVAL: 965, // Spirited Arrival
  WINDBORNE_NOTES: 964, // Windborne Notes
  NATURES_VENGEANCE: 1038, // Nature's Vengeance
  PROTECTIVE_WARD: 1988, // Protective Ward
  INVIGORATING_BOND: 1697, // Invigorating Bond
  TAIL_WIND: 1080, // Tail Wind
  FURIOUS_GRIP: 1083, // Furious Grip
  HUNTERS_TACTICS: 1068, // Hunter's Tactics
  SHARPENED_EDGES: 1069, // Sharpened Edges
  PRIMAL_REFLEXES: 1067, // Primal Reflexes
  TRAPPERS_EXPERTISE: 1075, // Trapper's Expertise
  FANG_AND_CLAW: 1016, // Fang and Claw
  STRIDERS_STRENGTH: 1700, // Strider's Strength
  HIDDEN_BARBS: 1846, // Hidden Barbs
  QUICK_DRAW: 1064, // Quick Draw
  LIGHT_ON_YOUR_FEET: 1912, // Light on your Feet
  VICIOUS_QUARRY: 1888, // Vicious Quarry
  PACK_ALPHA: 1900, // Pack Alpha
  LOUD_WHISTLE: 974, // Loud Whistle
  PETS_PROWESS: 1065, // Pet's Prowess
  GO_FOR_THE_EYES: 1861, // Go for the Eyes
  NATURAL_HEALING: 1072, // Natural Healing
  RESOUNDING_TIMBRE: 1606, // Resounding Timbre
  WILTING_STRIKE: 975, // Wilting Strike
  BESTIAL_RAGE: 1047, // Bestial Rage
  HONED_AXES: 970, // Honed Axes
  BEASTLY_WARDEN: 1945, // Beastly Warden
  ZEPHYRS_SPEED: 968, // Zephyr's Speed
  GO_FOR_THE_THROAT: 1066, // Go for the Throat
  NATURAL_VIGOR: 1096, // Natural Vigor
  COMPANIONS_DEFENSE: 1090, // Companion's Defense
  RUGGED_GROWTH: 1089, // Rugged Growth
  CHILD_OF_EARTH: 1098, // Child of Earth
  OAKHEART_SALVE: 1086, // Oakheart Salve
  ARACHNOPHOBIA: 1099, // Arachnophobia
  AMBIDEXTERITY: 1101, // Ambidexterity
  SURVIVAL_INSTINCTS: 2032, // Survival Instincts
  EMPATHIC_BOND: 1100, // Empathic Bond
  CARNIVORE: 1094, // Carnivore
  WILDERNESS_KNOWLEDGE: 1699, // Wilderness Knowledge
  POISON_MASTER: 1701, // Poison Master
  ELEVATED_BOND: 2151, // Elevated Bond
  FURIOUS_STRENGTH: 2156, // Furious Strength
  TWICE_AS_VICIOUS: 2127, // Twice as Vicious
  FRESH_REINFORCEMENT: 2134, // Fresh Reinforcement
  LIVE_FAST: 2071, // Live Fast
  UNSTOPPABLE_UNION: 2072, // Unstoppable Union
  SECOND_SKIN: 2119, // Second Skin
  ESSENCE_OF_SPEED: 2085, // Essence of Speed
  PREDATORS_CUNNING: 2161, // Predator's Cunning
  ETERNAL_BOND: 2155, // Eternal Bond
  LEADER_OF_THE_PACK: 2128, // Leader of the Pack
  OPPRESSIVE_SUPERIORITY: 2143, // Oppressive Superiority
  UNLEASHED_POWER: 2268, // Unleashed Power
  NATURAL_FORTITUDE: 2286, // Natural Fortitude
  VOW_OF_THE_UNTAMED: 2269, // Vow of the Untamed
  DEBILITATING_BLOWS: 2297, // Debilitating Blows
  NATURES_SHIELD: 2277, // Nature's Shield
  BLINDING_OUTBURST: 2301, // Blinding Outburst
  ENHANCING_IMPACT: 2263, // Enhancing Impact
  CLEANSING_UNLEASH: 2287, // Cleansing Unleash
  CORRUPTING_VINES: 2278, // Corrupting Vines
  LET_LOOSE: 2271, // Let Loose
  BIORHYTHM: 2283, // Biorhythm
  FEROCIOUS_SYMBIOSIS: 2274, // Ferocious Symbiosis
  TEACHINGS_OF_THE_TENGU: 2359, // Teachings of the Tengu
  BIRD_OF_PREY: 2363, // Bird of Prey
  JETSTREAM: 2341, // Jetstream
  JOY_OF_MOVEMENT: 2402, // Joy of Movement
  FEEL_THE_RUSH: 2370, // Feel the Rush
  WUTHERING_WIND: 2360, // Wuthering Wind
  FLOCK_TOGETHER: 2408, // Flock Together
  PERILOUS_SKIES: 2413, // Perilous Skies
  THRILL_OF_THE_CATCH: 2396, // Thrill of the Catch
  CLOUDBURST: 2425, // Cloudburst
  GALE_FORCE: 2336, // Gale Force
  SHRIKE: 2372, // Shrike
});

export const RANGER_SPECIALIZATION_IDS = Object.freeze({
  DRUID: 5, // Druid
  MARKSMANSHIP: 8, // Marksmanship
  NATURE_MAGIC: 25, // Nature Magic
  SKIRMISHING: 30, // Skirmishing
  BEASTMASTERY: 32, // Beastmastery
  WILDERNESS_SURVIVAL: 33, // Wilderness Survival
  SOULBEAST: 55, // Soulbeast
  UNTAMED: 72, // Untamed
  GALESHOT: 78, // Galeshot
});
