import type { CatalogEntity, Skill } from '../../../platform/engine/types.js';

// Narrow typed boundary for the generated Engineer API metadata snapshot. The
// implementation is regenerated by scripts/data/update-profession-api-data.mjs and
// remains JavaScript.

export interface EngineerApiTrait extends CatalogEntity {
  readonly description: string;
  readonly icon: string;
  readonly specialization: string;
  readonly tier: number;
  readonly position: number;
  readonly slot: string;
}

export interface EngineerApiSpecialization extends CatalogEntity {
  readonly elite: boolean;
  readonly icon: string;
  readonly background: string;
  readonly minorTraits: readonly EngineerApiTrait[];
  readonly majorTraits: readonly (readonly EngineerApiTrait[])[];
}

export const DATA_SNAPSHOT: string;
export const SPECIALIZATIONS: readonly EngineerApiSpecialization[];
export const SKILLS: readonly Skill[];
