import type { CatalogEntity } from "../../../platform/engine/types.js";
import type { ThiefSkill } from "../types.js";

// Narrow typed boundary for the generated Thief API metadata snapshot.
// The implementation is regenerated by scripts/data/update-profession-api-data.mjs
// and intentionally remains JavaScript.

export interface ThiefApiTrait extends CatalogEntity {
  readonly description: string;
  readonly icon: string;
  readonly specialization: string;
  readonly tier: number;
  readonly position: number;
}

export interface ThiefApiSpecialization extends CatalogEntity {
  readonly elite: boolean;
  readonly icon: string;
  readonly background: string;
  readonly minorTraits: readonly ThiefApiTrait[];
  readonly majorTraits: readonly (readonly ThiefApiTrait[])[];
}

export const DATA_SNAPSHOT: string;
export const SPECIALIZATIONS: readonly ThiefApiSpecialization[];
export const SKILLS: readonly ThiefSkill[];
