/** Canonical Core engineer skill fragments grouped by their GW2 owner. */
import { ENGINEER_SKILL_IDS as ID } from '#gw2/content/professions/engineer/data/ids.js';
import type { SkillFragment } from '#gw2/platform/engine/types.js';

/** Defines miscellaneous Core skill fragments generated by traits, bundles, and auxiliary effects. */
export const ENGINEER_MISC_SKILLS_SKILL_MECHANICS: Readonly<Record<number, SkillFragment>> = Object.freeze({
  [ID.JUMP_SHOT_ID_5817]: {
    implemented: true,
    castTimeMs: 1000,
    cooldown: 18,
    effects: [
      {
        type: 'strike',
        coefficient: 0.3,
        hits: 1,
        name: 'Leap Damage',
        actorType: 'player'
      },
      {
        type: 'strike',
        coefficient: 2.4,
        hits: 1,
        name: 'Landing Damage',
        actorType: 'player'
      },
      {
        type: 'condition',
        condition: 'Vulnerability',
        stacks: 3,
        duration: 7,
        actorType: 'player'
      }
    ]
  },
  [ID.LESSER_GRENADE_BARRAGE]: {
    implemented: true,
    castTimeMs: 0,
    cooldown: 20,
    effects: [
      {
        type: 'strike',
        coefficient: 3,
        hits: 6,
        atMs: 0,
        name: 'Lesser Grenade Barrage',
        actorType: 'player'
      }
    ]
  },
  [ID.WITHERING_PLAGUE]: {
    implemented: true,
    castTimeMs: 0,
    cooldown: 1,
    effects: [
      {
        type: 'condition',
        condition: 'Bleeding',
        stacks: 2,
        duration: 8,
        actorType: 'player'
      }
    ]
  },
  [ID.PLAGUE_OF_DARKNESS]: {
    implemented: true,
    castTimeMs: 0,
    cooldown: 1,
    effects: [
      {
        type: 'condition',
        condition: 'Torment',
        stacks: 1,
        duration: 8,
        actorType: 'player'
      },
      {
        type: 'blind',
        actorType: 'player'
      }
    ]
  },
  [ID.PLAGUE_OF_PESTILENCE]: {
    implemented: true,
    castTimeMs: 0,
    cooldown: 1,
    effects: [
      {
        type: 'condition',
        condition: 'Crippled',
        stacks: 1,
        duration: 2.5,
        actorType: 'player'
      },
      {
        type: 'condition',
        condition: 'Weakness',
        stacks: 1,
        duration: 3,
        actorType: 'player'
      }
    ]
  },
  [ID.LESSER_ELIXIR_B]: {
    implemented: true,
    castTimeMs: 0,
    cooldown: 24,
    effects: [
      {
        type: 'boon',
        boon: 'fury',
        duration: 8,
        stacks: 1
      },
      {
        type: 'boon',
        boon: 'might',
        duration: 8,
        stacks: 5
      },
      {
        type: 'boon',
        boon: 'resolution',
        duration: 8,
        stacks: 1
      },
      {
        type: 'boon',
        boon: 'swiftness',
        duration: 8,
        stacks: 1
      }
    ]
  },
  [ID.ALLY_WARD]: {
    implemented: true,
    castTimeMs: 0,
    cooldown: 0,
    effects: [
      {
        type: 'boon',
        boon: 'protection',
        duration: 3,
        stacks: 1
      }
    ]
  },
  [ID.STATIC_DISCHARGE_TRAIT_SKILL]: {
    implemented: true,
    castTimeMs: 0,
    cooldown: 0,
    effects: [
      {
        type: 'strike',
        coefficient: 0.33,
        hits: 1,
        name: 'Static Discharge (trait skill)',
        actorType: 'player'
      }
    ]
  },
  [ID.SNOWMAN_TURRET_SKILL]: {
    implemented: true,
    castTimeMs: 1500,
    cooldown: 20,
    effects: []
  },
  [ID.DETONATE_SNOWMAN_TURRET]: {
    implemented: true,
    castTimeMs: 0,
    cooldown: 0,
    effects: []
  },
  [ID.DROP_MINE]: {
    implemented: true,
    castTimeMs: 0,
    cooldown: 0,
    effects: [
      {
        type: 'strike',
        coefficient: 1.75,
        hits: 1,
        name: 'Drop Mine',
        actorType: 'player'
      }
    ]
  },
  [ID.MAGNETIC_BOMB_TRAIT_SKILL]: {
    interruptCommitMs: 0,
    implemented: true,
    castTimeMs: 0,
    cooldown: 0,
    effects: [
      {
        type: 'control',
        actorType: 'player',
        metadata: {
          controlKind: 'pull',
          duration: 300
        }
      }
    ]
  },
  [ID.SUPERSPEED_TRAIT_SKILL]: {
    implemented: true,
    castTimeMs: 0,
    cooldown: 0,
    effects: []
  },
  [ID.FIRE_SHIELD_TRAIT_SKILL]: {
    implemented: true,
    castTimeMs: 0,
    cooldown: 0,
    effects: [
      {
        type: 'condition',
        condition: 'Burning',
        stacks: 1,
        duration: 1,
        actorType: 'player'
      },
      {
        type: 'boon',
        boon: 'might',
        duration: 10,
        stacks: 1
      }
    ]
  },
  [ID.MAGNETIC_AURA_TRAIT_SKILL]: {
    implemented: true,
    castTimeMs: 0,
    cooldown: 0,
    effects: []
  },
  [ID.GLUE_TRAIL]: {
    implemented: true,
    castTimeMs: 0,
    cooldown: 0,
    effects: [
      {
        type: 'condition',
        condition: 'Immobilized',
        stacks: 1,
        duration: 1,
        actorType: 'player'
      }
    ]
  },
  [ID.BUNKER_DOWN_TRAIT_SKILL]: {
    implemented: true,
    castTimeMs: 0,
    cooldown: 1,
    effects: [
      {
        type: 'strike',
        coefficient: 0.95,
        hits: 1,
        name: 'Bunker Down (trait skill)',
        actorType: 'player'
      },
      {
        type: 'condition',
        condition: 'Vulnerability',
        stacks: 6,
        duration: 8,
        actorType: 'player'
      }
    ]
  },
  [ID.OVERFUELED_FLAME_JET]: {
    implemented: true,
    castTimeMs: 2250,
    cooldown: 1,
    effects: []
  },
  [ID.INVISIBLE_ANALYSIS]: {
    implemented: true,
    castTimeMs: 0,
    cooldown: 25,
    effects: [
      {
        type: 'condition',
        condition: 'Vulnerability',
        stacks: 10,
        duration: 8,
        actorType: 'player'
      },
      {
        type: 'boon',
        boon: 'fury',
        duration: 5,
        stacks: 1
      }
    ]
  },
  [ID.CLEANSING_PULSE]: {
    implemented: true,
    castTimeMs: 0,
    cooldown: 0,
    effects: [
      {
        type: 'boon',
        boon: 'Regeneration',
        duration: 4,
        stacks: 1
      }
    ]
  },
  [ID.LESSER_UTILITY_GOGGLES]: {
    implemented: true,
    castTimeMs: 0,
    cooldown: 0,
    effects: [
      {
        type: 'boon',
        boon: 'resistance',
        duration: 3,
        stacks: 1
      }
    ]
  },
  [ID.AIM_ASSISTED_ROCKET_TRAIT_SKILL]: {
    implemented: true,
    castTimeMs: 0,
    cooldown: 0,
    effects: [
      {
        type: 'strike',
        coefficient: 1,
        hits: 1,
        name: 'Aim-Assisted Rocket (trait skill)',
        actorType: 'player'
      }
    ]
  },
  [ID.DROP_GUNK]: {
    implemented: true,
    castTimeMs: 0,
    cooldown: 0,
    effects: [
      {
        type: 'strike',
        coefficient: 0.3,
        hits: 1,
        name: 'Drop Gunk',
        actorType: 'player'
      }
    ]
  },
  [ID.BANDAGE_TRAIT_SKILL]: {
    implemented: true,
    castTimeMs: 0,
    cooldown: 1,
    effects: [
      {
        type: 'boon',
        boon: 'regeneration',
        duration: 3,
        stacks: 1
      }
    ]
  },
  [ID.LONG_FUSED_POWDER_PACK]: {
    implemented: true,
    castTimeMs: 0,
    cooldown: 0,
    effects: [
      {
        type: 'strike',
        coefficient: 2,
        hits: 1,
        name: 'Long-Fused Powder Pack',
        actorType: 'player'
      }
    ]
  },
  [ID.THROW_JUNK_DOPPELGANGER]: {
    implemented: true,
    castTimeMs: 0,
    cooldown: 0.25,
    effects: [
      {
        type: 'strike',
        coefficient: 0.33,
        hits: 1,
        name: 'Throw Junk (Doppelganger)',
        actorType: 'player'
      },
      {
        type: 'condition',
        condition: 'Bleeding',
        stacks: 2,
        duration: 3,
        actorType: 'player'
      },
      {
        type: 'condition',
        condition: 'Chilled',
        stacks: 1,
        duration: 3,
        actorType: 'player'
      },
      {
        type: 'condition',
        condition: 'Weakness',
        stacks: 1,
        duration: 3,
        actorType: 'player'
      }
    ]
  },
  [ID.ORBITAL_COMMAND_STRIKE]: {
    implemented: true,
    castTimeMs: 0,
    cooldown: 0,
    effects: [
      {
        type: 'strike',
        coefficient: 1.92,
        hits: 1,
        name: 'Orbital Command Strike',
        actorType: 'player'
      }
    ]
  },
  [ID.CONTROLLED_ANALYSIS]: {
    implemented: true,
    castTimeMs: 0,
    cooldown: 25,
    effects: [
      {
        type: 'condition',
        condition: 'Vulnerability',
        stacks: 10,
        duration: 8,
        actorType: 'player'
      },
      {
        type: 'boon',
        boon: 'fury',
        duration: 5,
        stacks: 1
      }
    ]
  },
  [ID.LESSER_ELIXIR_C]: {
    implemented: true,
    castTimeMs: 0,
    cooldown: 10,
    effects: []
  },
  [ID.EXPLOSIVE_ENTRANCE_TRAIT_SKILL]: {
    implemented: true,
    castTimeMs: 0,
    cooldown: 0.25,
    effects: [
      {
        type: 'strike',
        coefficient: 1.25,
        hits: 1,
        name: 'Explosive Entrance (trait skill)',
        actorType: 'player'
      }
    ]
  }
});
