export const SHADOW_FORCE_DRAIN_FRACTION_PER_SECOND = 0.02;
export const SHADOW_FORCE_PER_INITIATIVE = 1.5;
export const SIPHON_BASE_SHADOW_FORCE = 25;
export const SIPHON_AMPLIFIED_SHADOW_FORCE = 35;
