import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import test from "node:test";

import { loadProfessionAppAdapter } from "../../../js/app/profession/registry.js";

const rotationUrl = new URL(
  "../../../Rotations/elementalist/r-condi-weaver-pistol.json",
  import.meta.url,
);
const buildUrl = new URL(
  "../../../Builds/elementalist/b-condi-weaver-pistol.json",
  import.meta.url,
);

const entryName = (entry) => (typeof entry === "string" ? entry : entry.name);

test("condition Weaver pistol/warhorn preserves the supplied default rotation", async () => {
  const preset = JSON.parse(await readFile(rotationUrl, "utf8"));
  const names = preset.rotation.map(entryName);
  const counts = Object.fromEntries(
    [...new Set(names)].map((name) => [
      name,
      names.filter((candidate) => candidate === name).length,
    ]),
  );

  assert.deepEqual(preset.metadata, {
    report: "https://dps.report/Yt2F-20260805-122746_golem",
    benchmarkDurationSeconds: 87.052,
    benchmarkDamage: 3902408,
    benchmarkDps: 44828.47033956715,
    timingSource: "Elite Insights activation timings",
    note: "The simulator-safe opener starts from Earth/Fire so Wildfire, Earth Attunement, and Dust Storm execute before combat without availability warnings. The saved rotation preserves the benchmark's completed skill activations and timing offsets while omitting Weapon Stow bookkeeping, automatic attunement trait procs, Dual Water attunement records generated by Unravel, and cancelled weapon activations.",
  });
  assert.deepEqual(names.slice(0, 10), [
    "Wildfire",
    "Earth Attunement",
    "Dust Storm",
    "Weave Self",
    "Primordial Stance (Earth)",
    "Signet of Fire",
    "__combat_start",
    "Shattering Stone",
    "Boulder Blast",
    "Fire Attunement",
  ]);
  assert.deepEqual(
    Object.fromEntries(
      [
        "Piercing Pebble",
        "Scorching Shot",
        "Shattering Stone",
        "Raging Ricochet",
        "Signet of Fire",
        "Boulder Blast",
        "Searing Salvo",
        "Molten Meteor",
        "Signet of Earth",
        "Primordial Stance (Earth)",
        "Primordial Stance (Fire)",
        "Wildfire",
        "Dust Storm",
        "Frozen Fusillade",
        "Frigid Flurry",
        "Water Attunement",
        "Unravel",
        "Echoing Erosion",
        "Weave Self",
      ].map((name) => [name, counts[name]]),
    ),
    {
      "Piercing Pebble": 38,
      "Scorching Shot": 30,
      "Shattering Stone": 14,
      "Raging Ricochet": 12,
      "Signet of Fire": 9,
      "Boulder Blast": 9,
      "Searing Salvo": 9,
      "Molten Meteor": 8,
      "Signet of Earth": 7,
      "Primordial Stance (Earth)": 5,
      "Primordial Stance (Fire)": 2,
      Wildfire: 5,
      "Dust Storm": 5,
      "Frozen Fusillade": 3,
      "Frigid Flurry": 3,
      "Water Attunement": 3,
      Unravel: 3,
      "Echoing Erosion": 2,
      "Weave Self": 2,
    },
  );
  assert.equal(
    preset.rotation.some(
      (entry) => typeof entry === "object" && entry.interruptMs != null,
    ),
    false,
  );
  assert.equal(names.includes("Weapon Stow"), false);

  const [savedBuild, adapter] = await Promise.all([
    readFile(buildUrl, "utf8").then(JSON.parse),
    loadProfessionAppAdapter("elementalist"),
  ]);
  assert.deepEqual(savedBuild.build.sigils, ["Malice", "Earth"]);
  assert.equal(savedBuild.build.food, "Salsa-Topped Veggie Flatbread");
  assert.deepEqual(savedBuild.build.infusions[0], {
    stat: "Expertise",
    count: 18,
  });
  assert.equal(savedBuild.build.gear.Back, "Viper's");
  assert.equal(savedBuild.build.utility, "Tuning Icicle");
  assert.deepEqual(savedBuild.pistolBullets, {
    Fire: true,
    Water: false,
    Air: false,
    Earth: true,
  });
  assert.equal(savedBuild.activeAttunement, "Earth");
  assert.equal(savedBuild.secondaryAttunement, "Fire");
  const build = {
    ...adapter.toApplicationBuild({
      ...savedBuild,
      rotation: preset.rotation,
    }),
    targetHealth: Number.MAX_SAFE_INTEGER,
    rotation: preset.rotation,
  };
  const app = {
    build,
    adapter,
    profession: adapter.profession,
    skillByName: adapter.profession.catalog.skillsByName,
    skillById: adapter.profession.catalog.skillsById,
    attributeWeaponSet: 1,
  };

  adapter.recalculate(app);
  const result = adapter.simulateBuild(
    build.rotation,
    adapter.simulationConfig(app),
  );

  assert.deepEqual(result.warnings, []);
  assert.ok(result.totalDamage > 0);
  const damagePackets = result.resolvedEvents
    .flatMap((event) =>
      event.type === "damage"
        ? [{ at: event.at, damage: Number(event.damage || 0) }]
        : (event.damageTicks || []).map((tick) => ({
            at: tick.at,
            damage: tick.damage,
          })),
    )
    .sort((left, right) => left.at - right.at);
  const weaveSelfSteps = result.steps.filter(
    (step) => step.skill === "Weave Self",
  );
  const openingEarthAttunement = result.steps.find(
    (step) => step.skill === "Earth Attunement",
  );
  const openingDustStorm = result.steps.find(
    (step) => step.skill === "Dust Storm",
  );
  const openingWildfire = result.steps.find(
    (step) => step.skill === "Wildfire",
  );
  const openingPrimordial = result.steps.find((step) =>
    String(step.skill).startsWith("Primordial Stance"),
  );
  const openingSignet = result.steps.find(
    (step) => step.skill === "Signet of Fire",
  );
  const combatStart = result.steps.find(
    (step) => step.skill === "Combat Start",
  );
  const openingFireAttunement = result.steps.find(
    (step) => step.skill === "Fire Attunement",
  );
  const perfectWeave = result.events.find(
    (event) => event.type === "buff" && event.kind === "perfect weave",
  );

  assert.equal(weaveSelfSteps.length, 2);
  assert.equal(combatStart.start - openingWildfire.start, 2739);
  assert.equal(combatStart.start - openingEarthAttunement.start, 2079);
  assert.equal(combatStart.start - openingDustStorm.start, 2079);
  assert.equal(openingPrimordial.start - weaveSelfSteps[0].start, 400);
  assert.equal(openingSignet.start - weaveSelfSteps[0].start, 918);
  assert.equal(combatStart.start - openingSignet.start, 321);
  assert.equal(combatStart.start - weaveSelfSteps[0].start, 1239);
  assert.equal(openingFireAttunement.start - combatStart.start, 1121);
  assert.ok(
    Math.abs(perfectWeave.at * 1000 - combatStart.start - 18998) < 1e-9,
  );

  const sourceCurve = [
    [18.328, 44422.90593627237],
    [34.227, 47182.16612674263],
    [54.327, 44172.15381843954],
    [73.227, 43464.59420678492],
    [87.052, 44828.47033956715],
  ];
  for (const [at, sourceDps] of sourceCurve) {
    const damage = damagePackets
      .filter((packet) => packet.at <= combatStart.start / 1000 + at)
      .reduce((sum, packet) => sum + packet.damage, 0);
    assert.ok(Math.abs(damage / at / sourceDps - 1) < 0.025);
  }
});
