import {
  markOfEvasion,
  lastRites,
  vampiric,
  vampiricPresence,
  overflowingThirst,
  bansheesWail,
  transfusion
} from '#gw2/professions/necromancer/core/traits/blood-magic.js';
import {
  barbedPrecision,
  chillingDarkness,
  insidiousDisruption,
  furiousDemise,
  targetTheWeak,
  lingeringCurse,
  weakeningShroud,
  masterOfCorruption,
  plagueSending,
  terror
} from '#gw2/professions/necromancer/core/traits/curses.js';
import {
  necromanticCorruption,
  fleshOfTheMaster,
  deadlyStrength,
  corruptersFervor,
  darkDefense,
  shroudedRemoval,
  soulComprehension,
  armoredShroud,
  putridDefense
} from '#gw2/professions/necromancer/core/traits/death-magic.js';
import {
  dhuumfire,
  unyieldingBlast,
  vitalPersistence,
  sinisterShroud,
  deathPerception,
  soulBarbs,
  eternalLife,
  fearOfDeath,
  speedOfShadows,
  soulMarks,
  soulBattery,
  gluttony
} from '#gw2/professions/necromancer/core/traits/soul-reaping.js';
import {
  reapersMight,
  siphonedPower,
  chillOfDeath,
  awakenThePain,
  spitefulFortitude,
  signetsOfSuffering,
  bitterChill,
  maliciousSwarm,
  spitefulSpirit,
  dread,
  spitefulTalisman,
  closeToDeath
} from '#gw2/professions/necromancer/core/traits/spite.js';

/** Register each Core trait directly, preserving the execution order of its rules. */
export const necromancerCoreTraits = [
  necromanticCorruption,
  fleshOfTheMaster,
  deadlyStrength,
  corruptersFervor,
  darkDefense,
  shroudedRemoval,
  soulComprehension,
  armoredShroud,
  putridDefense,
  dhuumfire,
  unyieldingBlast,
  vitalPersistence,
  sinisterShroud,
  deathPerception,
  soulBarbs,
  eternalLife,
  fearOfDeath,
  speedOfShadows,
  soulMarks,
  soulBattery,
  gluttony,
  barbedPrecision,
  chillingDarkness,
  insidiousDisruption,
  furiousDemise,
  targetTheWeak,
  lingeringCurse,
  weakeningShroud,
  masterOfCorruption,
  plagueSending,
  terror,
  markOfEvasion,
  lastRites,
  vampiric,
  vampiricPresence,
  overflowingThirst,
  bansheesWail,
  transfusion,
  reapersMight,
  siphonedPower,
  chillOfDeath,
  awakenThePain,
  spitefulFortitude,
  signetsOfSuffering,
  bitterChill,
  maliciousSwarm,
  spitefulSpirit,
  dread,
  spitefulTalisman,
  closeToDeath
];
