import {
  bansheesWail,
  lastRites,
  markOfEvasion,
  overflowingThirst,
  transfusion,
  vampiric,
  vampiricPresence
} from '#gw2/professions/necromancer/core/traits/blood-magic/index.js';
import {
  barbedPrecision,
  chillingDarkness,
  furiousDemise,
  insidiousDisruption,
  lingeringCurse,
  masterOfCorruption,
  plagueSending,
  targetTheWeak,
  terror,
  weakeningShroud
} from '#gw2/professions/necromancer/core/traits/curses/index.js';
import {
  armoredShroud,
  corruptersFervor,
  darkDefense,
  deadlyStrength,
  fleshOfTheMaster,
  necromanticCorruption,
  putridDefense,
  shroudedRemoval,
  soulComprehension
} from '#gw2/professions/necromancer/core/traits/death-magic/index.js';
import {
  deathPerception,
  dhuumfire,
  eternalLife,
  fearOfDeath,
  gluttony,
  sinisterShroud,
  soulBarbs,
  soulBattery,
  soulMarks,
  speedOfShadows,
  unyieldingBlast,
  vitalPersistence
} from '#gw2/professions/necromancer/core/traits/soul-reaping/index.js';
import {
  awakenThePain,
  bitterChill,
  chillOfDeath,
  closeToDeath,
  dread,
  maliciousSwarm,
  reapersMight,
  signetsOfSuffering,
  siphonedPower,
  spitefulFortitude,
  spitefulSpirit,
  spitefulTalisman
} from '#gw2/professions/necromancer/core/traits/spite/index.js';

/** Register each Core trait directly, preserving the execution order of its rules. */
export const necromancerCoreTraits = [
  necromanticCorruption,
  fleshOfTheMaster,
  deadlyStrength,
  corruptersFervor,
  darkDefense,
  shroudedRemoval,
  soulComprehension,
  armoredShroud,
  putridDefense,
  dhuumfire,
  unyieldingBlast,
  vitalPersistence,
  sinisterShroud,
  deathPerception,
  soulBarbs,
  eternalLife,
  fearOfDeath,
  speedOfShadows,
  soulMarks,
  soulBattery,
  gluttony,
  barbedPrecision,
  chillingDarkness,
  insidiousDisruption,
  furiousDemise,
  targetTheWeak,
  lingeringCurse,
  weakeningShroud,
  masterOfCorruption,
  plagueSending,
  terror,
  markOfEvasion,
  lastRites,
  vampiric,
  vampiricPresence,
  overflowingThirst,
  bansheesWail,
  transfusion,
  reapersMight,
  siphonedPower,
  chillOfDeath,
  awakenThePain,
  spitefulFortitude,
  signetsOfSuffering,
  bitterChill,
  maliciousSwarm,
  spitefulSpirit,
  dread,
  spitefulTalisman,
  closeToDeath
];
