/**
 * Herald skill mechanics owned by the Herald Revenant module.
 */
import { REVENANT_SKILL_IDS as ID } from "../../data/ids.js";
import type { SkillFragment } from "../../../../platform/engine/types.js";

export const HERALD_BASE_SKILL_MECHANICS: Readonly<
  Record<number, SkillFragment>
> = Object.freeze({
  [ID.FACET_OF_STRENGTH]: {
    implemented: true,
    handlerId: "revenant.upkeep",
    castTimeMs: 0,
    cooldown: 0,
    energyCost: 0,
    upkeepCost: 2,
    effects: [],
    legendId: "LegendaryDragon",
    facet: true,
    upkeepPulseInterval: 3,
    upkeepPulse: { kind: "might", duration: 12, stacks: 1 },
    upkeepConsumeId: ID.BURST_OF_STRENGTH,
  },
  [ID.FACET_OF_ELEMENTS]: {
    implemented: true,
    handlerId: "revenant.upkeep",
    castTimeMs: 0,
    cooldown: 0,
    energyCost: 0,
    upkeepCost: 1,
    effects: [],
    legendId: "LegendaryDragon",
    facet: true,
    upkeepPulseInterval: 3,
    upkeepPulse: { kind: "swiftness", duration: 3, stacks: 1 },
    upkeepConsumeId: ID.ELEMENTAL_BLAST,
  },
  [ID.GAZE_OF_DARKNESS]: {
    implemented: true,
    handlerId: "revenant.facet-consume",
    castTimeMs: 0,
    cooldown: 15,
    energyCost: 0,
    effects: [
      {
        type: "condition",
        condition: "Vulnerability",
        stacks: 10,
        duration: 6,
        actorType: "player",
      },
      {
        type: "condition",
        condition: "Revealed",
        stacks: 1,
        duration: 5,
        actorType: "player",
      },
      {
        type: "blind",
        actorType: "player",
        metadata: {
          duration: 5,
        },
      },
    ],
    legendId: "LegendaryDragon",
    consume: true,
  },
  [ID.ELEMENTAL_BLAST]: {
    implemented: true,
    handlerId: "revenant.elemental-blast",
    quicknessCastTimeMs: 480,
    cooldown: 12,
    energyCost: 0,
    effects: [],
    legendId: "LegendaryDragon",
    consume: true,
  },
  [ID.FACET_OF_LIGHT]: {
    implemented: true,
    handlerId: "revenant.upkeep",
    castTimeMs: 250,
    cooldown: 0,
    energyCost: 0,
    upkeepCost: 1,
    effects: [],
    legendId: "LegendaryDragon",
    facet: true,
    upkeepPulseInterval: 3,
    upkeepPulse: { kind: "regeneration", duration: 4, stacks: 1 },
    upkeepConsumeId: ID.INFUSE_LIGHT,
  },
  [ID.INFUSE_LIGHT]: {
    implemented: true,
    handlerId: "revenant.facet-consume",
    castTimeMs: 0,
    cooldown: 30,
    energyCost: 0,
    effects: [],
    legendId: "LegendaryDragon",
    consume: true,
  },
  [ID.FACET_OF_CHAOS]: {
    implemented: true,
    handlerId: "revenant.upkeep",
    castTimeMs: 0,
    cooldown: 0,
    energyCost: 0,
    upkeepCost: 4,
    effects: [],
    legendId: "LegendaryDragon",
    facet: true,
    upkeepPulseInterval: 3,
    upkeepPulse: { kind: "protection", duration: 3, stacks: 1 },
    upkeepConsumeId: ID.CHAOTIC_RELEASE,
  },
  [ID.CHAOTIC_RELEASE]: {
    implemented: true,
    handlerId: "revenant.facet-consume",
    quicknessCastTimeMs: 600,
    cooldown: 20,
    energyCost: 0,
    effects: [
      {
        type: "strike",
        coefficient: 4,
        hits: 1,
        name: "Chaotic Release",
        actorType: "player",
        atMs: 560,
        timingAnchor: "castStart",
        timingScale: "fixed",
      },
      {
        type: "control",
        actorType: "player",
        atMs: 560,
        timingAnchor: "castStart",
        timingScale: "fixed",
        metadata: {
          controlKind: "knockback",
          duration: 360,
        },
      },
      {
        type: "boon",
        boon: "superspeed",
        duration: 5,
        stacks: 1,
        atMs: 560,
        timingAnchor: "castStart",
        timingScale: "fixed",
      },
    ],
    legendId: "LegendaryDragon",
    consume: true,
  },
  [ID.BURST_OF_STRENGTH]: {
    implemented: true,
    handlerId: "revenant.facet-consume",
    quicknessCastTimeMs: 840,
    cooldown: 12,
    energyCost: 0,
    effects: [
      {
        type: "strike",
        coefficient: 3.2,
        hits: 2,
        name: "Burst of Strength",
        actorType: "player",
        atMs: 360,
        intervalMs: 320,
        timingAnchor: "castStart",
        timingScale: "fixed",
      },
      {
        type: "buff",
        kind: "burst-of-strength",
        duration: 10,
        stacks: 1,
        atMs: 360,
        timingAnchor: "castStart",
        timingScale: "fixed",
      },
    ],
    legendId: "LegendaryDragon",
    consume: true,
  },
  [ID.FACET_OF_DARKNESS]: {
    implemented: true,
    handlerId: "revenant.upkeep",
    castTimeMs: 0,
    cooldown: 0,
    energyCost: 0,
    upkeepCost: 2,
    effects: [],
    legendId: "LegendaryDragon",
    facet: true,
    upkeepPulseInterval: 3,
    upkeepPulse: { kind: "fury", duration: 3, stacks: 1 },
    upkeepConsumeId: ID.GAZE_OF_DARKNESS,
  },
  [ID.FACET_OF_NATURE]: {
    implemented: true,
    handlerId: "revenant.upkeep",
    castTimeMs: 0,
    cooldown: 0,
    energyCost: 0,
    upkeepCost: 2,
    effects: [],
    legendId: "LegendaryDragon",
    facet: true,
    upkeepPulseInterval: 3,
    upkeepConsumeByLegendId: {
      LegendaryAssassin: ID.TRUE_NATURE,
      LegendaryDwarf: ID.TRUE_NATURE_ID_51675,
      LegendaryDragon: ID.TRUE_NATURE_ID_51696,
      LegendaryCentaur: ID.TRUE_NATURE_ID_51713,
      LegendaryDemon: ID.TRUE_NATURE_ID_51714,
    },
  },
  [ID.TRUE_NATURE]: {
    implemented: true,
    handlerId: "revenant.facet-consume",
    quicknessCastTimeMs: 480,
    cooldown: 20,
    energyCost: 0,
    effects: [
      {
        type: "strike",
        coefficient: 1,
        hits: 1,
        name: "True Nature (assassin)",
        actorType: "player",
      },
    ],
    legendId: "LegendaryDragon",
    consume: true,
  },
  [ID.TRUE_NATURE_ID_51675]: {
    implemented: true,
    handlerId: "revenant.facet-consume",
    quicknessCastTimeMs: 480,
    cooldown: 20,
    energyCost: 0,
    effects: [
      {
        type: "boon",
        boon: "stability",
        duration: 4,
        stacks: 2,
      },
    ],
    legendId: "LegendaryDragon",
    consume: true,
  },
  [ID.TRUE_NATURE_ID_51696]: {
    implemented: true,
    handlerId: "revenant.facet-consume",
    quicknessCastTimeMs: 480,
    cooldown: 20,
    energyCost: 0,
    effects: [],
    legendId: "LegendaryDragon",
    consume: true,
  },
  [ID.TRUE_NATURE_ID_51713]: {
    implemented: true,
    handlerId: "revenant.facet-consume",
    quicknessCastTimeMs: 480,
    cooldown: 20,
    energyCost: 0,
    effects: [],
    legendId: "LegendaryDragon",
    consume: true,
  },
  [ID.TRUE_NATURE_ID_51714]: {
    implemented: true,
    handlerId: "revenant.facet-consume",
    quicknessCastTimeMs: 480,
    cooldown: 20,
    energyCost: 0,
    effects: [
      {
        type: "boon",
        boon: "might",
        duration: 10,
        stacks: 5,
      },
    ],
    legendId: "LegendaryDragon",
    consume: true,
  },
});
