import type { PatchPreview } from "../platform/gw2/skill-patch.js";

/**
 * Generated by the local patch preview authoring UI. Review this diff before
 * committing it; the runtime validates every referenced skill and modifier.
 */
export const activePatchPreview: PatchPreview = {
  "id": "upcoming-patch",
  "label": "Upcoming Patch",
  "professions": {
    "necromancer": {
      "skills": {
        "30670": {
          "effects": [
            {
              "effectIndex": 0,
              "coefficient": {
                "from": 1.5,
                "to": 2
              },
              "hits": {
                "from": 1,
                "to": 2
              }
            }
          ]
        },
        "73013": {
          "effects": [
            {
              "effectIndex": 0,
              "coefficient": {
                "from": 1.9,
                "to": 1.8
              }
            }
          ]
        }
      },
      "overview": [
        {
          "subject": "\"Suffer!\"",
          "text": "Effect 0 coefficient 1.5 → 2; effect 0 hits 1 → 2.",
          "source": "skill-diff"
        },
        {
          "subject": "Addle",
          "text": "Effect 0 coefficient 1.9 → 1.8.",
          "source": "skill-diff"
        }
      ]
    }
  },
  "sourceUrl": "https://en-forum.guildwars2.com/topic/175644-game-update-notes-august-11-2026/"
};

export default activePatchPreview;
