import {
  beastlyWarden,
  bestialRage,
  goForTheEyes,
  goForTheThroat,
  honedAxes,
  loudWhistle,
  packAlpha,
  petsProwess,
  resoundingTimbre,
  wiltingStrike
} from '#gw2/professions/ranger/core/traits/beastmastery/index.js';
import {
  alphaFocus,
  clarionBond,
  farsighted,
  huntersGaze,
  leadTheWind,
  openingStrike,
  preciseStrike,
  predatorsOnslaught,
  remorseless,
  wolfsong
} from '#gw2/professions/ranger/core/traits/marksmanship/index.js';
import {
  bountifulHunter,
  fortifyingBond,
  lingeringMagic,
  naturesVengeance,
  rejuvenation,
  spiritedArrival,
  wellspring,
  windborneNotes
} from '#gw2/professions/ranger/core/traits/nature-magic/index.js';
import {
  fangAndClaw,
  furiousGrip,
  hiddenBarbs,
  huntersTactics,
  lightOnYourFeet,
  quickDraw,
  sharpenedEdges,
  stridersStrength,
  tailWind,
  trappersExpertise,
  viciousQuarry
} from '#gw2/professions/ranger/core/traits/skirmishing/index.js';
import {
  ambidexterity,
  arachnophobia,
  carnivore,
  childOfEarth,
  naturalVigor,
  poisonMaster,
  survivalInstincts
} from '#gw2/professions/ranger/core/traits/wilderness-survival/index.js';

/** Register authored owners in a fixed order; runtime boundaries stay explicit. */
export const rangerCoreTraits = [
  beastlyWarden,
  lightOnYourFeet,
  childOfEarth,
  wellspring,
  windborneNotes,
  rejuvenation,
  poisonMaster,
  wolfsong,
  tailWind,
  quickDraw,
  furiousGrip,
  spiritedArrival,
  clarionBond,
  resoundingTimbre,
  openingStrike,
  alphaFocus,
  huntersGaze,
  leadTheWind,
  arachnophobia,
  goForTheThroat,
  sharpenedEdges,
  trappersExpertise,
  carnivore,
  naturalVigor,
  fangAndClaw,
  stridersStrength,
  honedAxes,
  viciousQuarry,
  packAlpha,
  petsProwess,
  lingeringMagic,
  fortifyingBond,
  naturesVengeance,
  huntersTactics,
  preciseStrike,
  ambidexterity,
  wiltingStrike,
  goForTheEyes,
  bestialRage,
  farsighted,
  bountifulHunter,
  remorseless,
  predatorsOnslaught,
  hiddenBarbs,
  survivalInstincts,
  loudWhistle
];
