/**
 * Core skill mechanics owned by the Core Revenant module.
 */
import { REVENANT_SKILL_IDS as ID } from "../data/ids.js";
import type { Skill, SkillFragment } from "../../../platform/engine/types.js";

export const REVENANT_CORE_BASE_SKILL_MECHANICS: Readonly<
  Record<number, SkillFragment>
> = Object.freeze({
  [ID.VENGEFUL_HAMMERS]: {
    implemented: true,
    handlerId: "revenant.upkeep",
    castTimeMs: 0,
    cooldown: 0,
    energyCost: 5,
    upkeepCost: 6,
    effects: [],
    legendId: "LegendaryDwarf",
  },
  [ID.LEGENDARY_DWARF_STANCE_ID_26650]: {
    implemented: true,
    castTimeMs: 0,
    cooldown: 0,
    energyCost: 0,
    effects: [],
  },
  [ID.MANIFEST_TOXIN]: {
    implemented: true,
    quicknessCastTimeMs: 560,
    cooldown: 0,
    energyCost: 0,
    effects: [
      {
        type: "strike",
        coefficient: 0.6,
        hits: 1,
        name: "Manifest Toxin — Packet 1",
        actorType: "player",
        atMs: 440,
        timingAnchor: "castStart",
        timingScale: "fixed",
      },
      {
        type: "condition",
        condition: "Poisoned",
        stacks: 1,
        duration: 12,
        actorType: "player",
        atMs: 440,
        timingAnchor: "castStart",
        timingScale: "fixed",
      },
    ],
  },
  [ID.FORCED_ENGAGEMENT]: {
    implemented: true,
    castTimeMs: 500,
    cooldown: 15,
    energyCost: 10,
    effects: [
      {
        type: "strike",
        coefficient: 0.5,
        hits: 1,
        name: "Forced Engagement",
        actorType: "player",
      },
      {
        type: "condition",
        condition: "Slow",
        stacks: 1,
        duration: 4,
        actorType: "player",
      },
      {
        type: "control",
        actorType: "player",
        metadata: {
          controlKind: "taunt",
          duration: 4,
        },
      },
    ],
    legendId: "LegendaryDwarf",
  },
  [ID.RESIST_THE_DARKNESS]: {
    implemented: true,
    handlerId: "revenant.upkeep-release",
    castTimeMs: 0,
    cooldown: 0,
    energyCost: 0,
    effects: [],
    legendId: "LegendaryDemon",
  },
  [ID.UNRELENTING_ASSAULT]: {
    implemented: true,
    castTimeMs: 750,
    cooldown: 12,
    energyCost: 15,
    effects: [
      {
        type: "strike",
        coefficient: 3.9325,
        hits: 5,
        name: "Unrelenting Assault",
        actorType: "player",
        atMs: 150,
        intervalMs: 150,
        timingAnchor: "castStart",
        timingScale: "cast",
      },
      {
        type: "boon",
        boon: "might",
        duration: 8,
        stacks: 1,
      },
    ],
  },
  [ID.ANGUISH_SWIPE]: {
    implemented: true,
    quicknessCastTimeMs: 360,
    cooldown: 0,
    energyCost: 0,
    effects: [
      {
        type: "strike",
        coefficient: 0.4,
        hits: 1,
        name: "Anguish Swipe",
        actorType: "player",
        atMs: 280,
        timingAnchor: "castStart",
        timingScale: "fixed",
      },
      {
        type: "condition",
        condition: "Torment",
        stacks: 1,
        duration: 3,
        actorType: "player",
        atMs: 280,
        timingAnchor: "castStart",
        timingScale: "fixed",
      },
    ],
  },
  [ID.PROTECTIVE_SOLACE]: {
    implemented: true,
    handlerId: "revenant.upkeep",
    castTimeMs: 0,
    cooldown: 5,
    energyCost: 5,
    upkeepCost: 8,
    effects: [],
    legendId: "LegendaryCentaur",
  },
  [ID.ENCHANTED_DAGGERS]: {
    implemented: true,
    handlerId: "revenant.enchanted-daggers",
    castTimeMs: 500,
    cooldown: 30,
    energyCost: 5,
    effects: [],
    legendId: "LegendaryAssassin",
  },
  [ID.RELEASE_HAMMERS]: {
    implemented: true,
    handlerId: "revenant.upkeep-release",
    castTimeMs: 0,
    cooldown: 0,
    energyCost: 0,
    effects: [],
    legendId: "LegendaryDwarf",
  },
  [ID.NATURAL_HARMONY]: {
    implemented: true,
    castTimeMs: 0,
    cooldown: 2,
    energyCost: 20,
    effects: [],
    legendId: "LegendaryCentaur",
  },
  [ID.MISERY_SWIPE]: {
    implemented: true,
    quicknessCastTimeMs: 440,
    cooldown: 0,
    energyCost: 0,
    effects: [
      {
        type: "strike",
        coefficient: 0.35,
        hits: 1,
        name: "Misery Swipe",
        actorType: "player",
        atMs: 280,
        timingAnchor: "castStart",
        timingScale: "fixed",
      },
      {
        type: "condition",
        condition: "Torment",
        stacks: 1,
        duration: 3,
        actorType: "player",
        atMs: 280,
        timingAnchor: "castStart",
        timingScale: "fixed",
      },
    ],
  },
  [ID.DEATHSTRIKE]: {
    implemented: true,
    quicknessCastTimeMs: 720,
    cooldown: 15,
    rechargeAnchor: "castStart",
    rechargeOffsetMs: 420,
    energyCost: 10,
    effects: [
      {
        type: "strike",
        coefficient: 0.45,
        hits: 1,
        name: "Initial Damage",
        actorType: "player",
        atMs: 320,
        timingAnchor: "castStart",
        timingScale: "fixed",
      },
      {
        type: "strike",
        coefficient: 2.67,
        hits: 1,
        name: "Final Damage",
        actorType: "player",
        atMs: 600,
        timingAnchor: "castStart",
        timingScale: "fixed",
      },
      {
        type: "boon",
        boon: "fury",
        duration: 8,
        stacks: 1,
        atMs: 320,
        timingAnchor: "castStart",
        timingScale: "fixed",
      },
    ],
  },
  [ID.IMPOSSIBLE_ODDS]: {
    implemented: true,
    handlerId: "revenant.upkeep",
    castTimeMs: 0,
    cooldown: 0,
    energyCost: 5,
    upkeepCost: 6,
    manualReleaseCooldown: 1,
    starvationCooldown: 4,
    effects: [],
    legendId: "LegendaryAssassin",
  },
  [ID.DOME_OF_THE_MISTS]: {
    implemented: true,
    castTimeMs: 0,
    cooldown: 20,
    energyCost: 0,
    effects: [
      {
        type: "condition",
        condition: "Weakness",
        stacks: 1,
        duration: 1,
        actorType: "player",
      },
    ],
  },
  [ID.PAIN_ABSORPTION]: {
    implemented: true,
    castTimeMs: 500,
    cooldown: 0,
    energyCost: 30,
    effects: [
      {
        type: "boon",
        boon: "resistance",
        duration: 3,
        stacks: 1,
      },
      {
        type: "boon",
        boon: "resolution",
        duration: 5,
        stacks: 1,
      },
      {
        type: "boon",
        boon: "resistance",
        duration: 1,
        stacks: 1,
      },
    ],
    legendId: "LegendaryDemon",
  },
  [ID.ENERGY_EXPULSION]: {
    implemented: true,
    castTimeMs: 0,
    cooldown: 2,
    energyCost: 35,
    effects: [
      {
        type: "control",
        actorType: "player",
        metadata: {
          controlKind: "knockdown",
          duration: 3,
        },
      },
      {
        type: "boon",
        boon: "stability",
        duration: 5,
        stacks: 3,
      },
    ],
    legendId: "LegendaryCentaur",
  },
  [ID.SOOTHING_STONE]: {
    implemented: true,
    castTimeMs: 1000,
    cooldown: 30,
    energyCost: 5,
    effects: [
      {
        type: "boon",
        boon: "resolution",
        duration: 5,
        stacks: 1,
      },
    ],
    legendId: "LegendaryDwarf",
  },
  [ID.BANISH_ENCHANTMENT]: {
    implemented: true,
    quicknessCastTimeMs: 440,
    cooldown: 0,
    energyCost: 20,
    effects: [
      {
        type: "strike",
        coefficient: 1.2,
        hits: 3,
        name: "Banish Enchantment",
        actorType: "player",
        atMs: 402,
        intervalMs: 119,
        timingAnchor: "castStart",
        timingScale: "fixed",
        persistsAfterInterrupt: true,
        metadata: {
          extendsResolutionHorizon: true,
        },
      },
      {
        type: "condition",
        condition: "Chilled",
        stacks: 1,
        duration: 1,
        applications: 3,
        atMs: 402,
        intervalMs: 119,
        timingAnchor: "castStart",
        timingScale: "fixed",
        persistsAfterInterrupt: true,
        metadata: {
          extendsResolutionHorizon: true,
        },
        actorType: "player",
      },
      {
        type: "condition",
        condition: "Torment",
        stacks: 1,
        duration: 3,
        applications: 3,
        atMs: 402,
        intervalMs: 119,
        timingAnchor: "castStart",
        timingScale: "fixed",
        persistsAfterInterrupt: true,
        metadata: {
          extendsResolutionHorizon: true,
        },
        actorType: "player",
      },
    ],
    legendId: "LegendaryDemon",
  },
  [ID.DIMINISH_SOLACE]: {
    implemented: true,
    castTimeMs: 0,
    cooldown: 5,
    energyCost: 0,
    effects: [],
  },
  [ID.LEGENDARY_ASSASSIN_STANCE_ID_27659]: {
    implemented: true,
    castTimeMs: 0,
    cooldown: 0,
    energyCost: 0,
    effects: [],
  },
  [ID.FIELD_OF_THE_MISTS]: {
    implemented: true,
    castTimeMs: 750,
    cooldown: 12,
    energyCost: 10,
    effects: [
      {
        type: "strike",
        coefficient: 1.8,
        hits: 1,
        name: "Field of the Mists",
        actorType: "player",
        atMs: 560,
        timingAnchor: "castStart",
        timingScale: "fixed",
        persistsAfterInterrupt: true,
        metadata: {
          extendsResolutionHorizon: true,
        },
      },
      {
        type: "boon",
        boon: "aegis",
        duration: 2,
        stacks: 1,
      },
    ],
  },
  [ID.PURIFYING_ESSENCE]: {
    implemented: true,
    castTimeMs: 0,
    cooldown: 5,
    energyCost: 25,
    effects: [],
    legendId: "LegendaryCentaur",
  },
  [ID.CALL_TO_ANGUISH]: {
    implemented: true,
    quicknessCastTimeMs: 820,
    cooldown: 3,
    energyCost: 30,
    effects: [
      {
        type: "strike",
        coefficient: 1.2,
        hits: 1,
        name: "Call to Anguish",
        actorType: "player",
        atMs: 804,
        timingAnchor: "castStart",
        timingScale: "fixed",
        persistsAfterInterrupt: true,
        metadata: {
          extendsResolutionHorizon: true,
        },
      },
      {
        type: "condition",
        condition: "Chilled",
        stacks: 1,
        duration: 2,
        actorType: "player",
        atMs: 804,
        timingAnchor: "castStart",
        timingScale: "fixed",
        persistsAfterInterrupt: true,
        metadata: {
          extendsResolutionHorizon: true,
        },
      },
      {
        type: "control",
        actorType: "player",
        atMs: 804,
        timingAnchor: "castStart",
        timingScale: "fixed",
        persistsAfterInterrupt: true,
        metadata: {
          controlKind: "pull",
          duration: 360,
          extendsResolutionHorizon: true,
        },
      },
    ],
    legendId: "LegendaryDemon",
  },
  [ID.ECHOING_ERUPTION]: {
    implemented: true,
    quicknessCastTimeMs: 960,
    cooldown: 8,
    ammo: 0,
    ammoRecharge: 0,
    energyCost: 5,
    finisherType: "Blast",
    finisherValue: 1,
    effects: [
      {
        type: "strike",
        coefficient: 1,
        hits: 1,
        name: "Echoing Eruption",
        actorType: "player",
        atMs: 800,
        timingAnchor: "castStart",
        timingScale: "fixed",
      },
      {
        type: "condition",
        condition: "Torment",
        stacks: 4,
        duration: 5,
        actorType: "player",
        atMs: 800,
        timingAnchor: "castStart",
        timingScale: "fixed",
      },
      {
        type: "condition",
        condition: "Weakness",
        stacks: 1,
        duration: 3,
        actorType: "player",
        atMs: 800,
        timingAnchor: "castStart",
        timingScale: "fixed",
      },
      {
        type: "boon",
        boon: "Might",
        duration: 9,
        stacks: 3,
        atMs: 800,
        timingAnchor: "castStart",
        timingScale: "fixed",
      },
    ],
  },
  [ID.RITE_OF_THE_GREAT_DWARF]: {
    implemented: true,
    castTimeMs: 1250,
    cooldown: 0,
    energyCost: 40,
    effects: [],
    legendId: "LegendaryDwarf",
  },
  [ID.PHASE_SMASH]: {
    implemented: true,
    castTimeMs: 1250,
    cooldown: 8,
    energyCost: 5,
    effects: [
      {
        type: "strike",
        coefficient: 2.2,
        hits: 1,
        name: "Phase Smash",
        actorType: "player",
      },
      {
        type: "condition",
        condition: "Chilled",
        stacks: 1,
        duration: 2,
        actorType: "player",
      },
    ],
  },
  [ID.FRIGID_BLITZ]: {
    implemented: true,
    quicknessCastTimeMs: 681,
    cooldown: 10,
    energyCost: 10,
    effects: [
      {
        type: "strike",
        coefficient: 0.15,
        hits: 1,
        name: "Pass-Through Damage",
        actorType: "player",
      },
      {
        type: "strike",
        coefficient: 1.5,
        hits: 1,
        name: "Final Damage",
        actorType: "player",
      },
      {
        type: "condition",
        condition: "Chilled",
        stacks: 1,
        duration: 2,
        actorType: "player",
      },
      {
        type: "condition",
        condition: "Torment",
        stacks: 3,
        duration: 6,
        actorType: "player",
      },
    ],
  },
  [ID.LEGENDARY_DRAGON_STANCE]: {
    implemented: true,
    castTimeMs: 0,
    cooldown: 0,
    energyCost: 0,
    effects: [],
  },
  [ID.DROP_THE_HAMMER]: {
    implemented: true,
    castTimeMs: 500,
    cooldown: 15,
    energyCost: 10,
    effects: [
      {
        type: "strike",
        coefficient: 3.2,
        hits: 1,
        name: "Drop the Hammer",
        actorType: "player",
        atMs: 1639,
        timingAnchor: "castStart",
        timingScale: "fixed",
        persistsAfterInterrupt: true,
        metadata: {
          extendsResolutionHorizon: true,
        },
      },
      {
        type: "control",
        actorType: "player",
        atMs: 1639,
        timingAnchor: "castStart",
        timingScale: "fixed",
        persistsAfterInterrupt: true,
        metadata: {
          controlKind: "knockdown",
          duration: 3,
          extendsResolutionHorizon: true,
        },
      },
    ],
  },
  [ID.LEGENDARY_ASSASSIN_STANCE]: {
    implemented: true,
    castTimeMs: 0,
    cooldown: 0,
    energyCost: 0,
    effects: [],
  },
  [ID.LEGENDARY_CENTAUR_STANCE_ID_28141]: {
    implemented: true,
    castTimeMs: 0,
    cooldown: 0,
    energyCost: 0,
    effects: [],
  },
  [ID.LEGENDARY_CENTAUR_STANCE]: {
    implemented: true,
    castTimeMs: 0,
    cooldown: 0,
    energyCost: 0,
    effects: [],
  },
  [ID.EMPOWERING_MISERY]: {
    implemented: true,
    castTimeMs: 750,
    cooldown: 30,
    energyCost: 5,
    effects: [
      {
        type: "boon",
        boon: "might",
        duration: 8,
        stacks: 1,
      },
    ],
    legendId: "LegendaryDemon",
  },
  [ID.PHASE_TRAVERSAL]: {
    implemented: true,
    castTimeMs: 500,
    cooldown: 5,
    energyCost: 30,
    effects: [
      {
        type: "strike",
        coefficient: 2,
        hits: 1,
        name: "Phase Traversal",
        actorType: "player",
      },
      {
        type: "boon",
        boon: "quickness",
        duration: 3,
        stacks: 1,
      },
    ],
    legendId: "LegendaryAssassin",
  },
  [ID.COALESCENCE_OF_RUIN]: {
    implemented: true,
    castTimeMs: 750,
    cooldown: 4,
    energyCost: 5,
    effects: [
      {
        type: "strike",
        coefficient: 2.3,
        hits: 1,
        name: "Coalescence of Ruin",
        actorType: "player",
        atMs: 561,
        timingAnchor: "castStart",
        timingScale: "fixed",
        persistsAfterInterrupt: true,
        metadata: {
          extendsResolutionHorizon: true,
        },
      },
    ],
  },
  [ID.CRYSTAL_HIBERNATION]: {
    implemented: true,
    castTimeMs: 3000,
    cooldown: 25,
    energyCost: 20,
    effects: [],
  },
  [ID.EMBRACE_THE_DARKNESS]: {
    implemented: true,
    handlerId: "revenant.upkeep",
    quicknessCastTimeMs: 440,
    cooldown: 3,
    energyCost: 5,
    upkeepCost: 6,
    effects: [],
    legendId: "LegendaryDemon",
  },
  [ID.SEARING_FISSURE]: {
    implemented: true,
    quicknessCastTimeMs: 600,
    interruptCommitMs: 480,
    cooldown: 3,
    energyCost: 5,
    comboField: "Fire",
    duration: 3,
    effects: [
      {
        type: "strike",
        coefficient: 0.5,
        hits: 1,
        name: "Initial Strike",
        actorType: "player",
        atMs: 480,
        timingAnchor: "castStart",
        timingScale: "fixed",
        persistsAfterInterrupt: true,
      },
      {
        type: "strike",
        coefficient: 0.75,
        hits: 3,
        name: "Pulsing Strikes",
        actorType: "player",
        atMs: 1480,
        intervalMs: 1000,
        timingAnchor: "castStart",
        timingScale: "fixed",
        persistsAfterInterrupt: true,
        metadata: {
          extendsResolutionHorizon: true,
        },
      },
      {
        type: "condition",
        condition: "Burning",
        stacks: 3,
        duration: 3,
        actorType: "player",
        atMs: 480,
        timingAnchor: "castStart",
        timingScale: "fixed",
        persistsAfterInterrupt: true,
      },
      {
        type: "condition",
        condition: "Burning",
        stacks: 1,
        duration: 1,
        applications: 3,
        atMs: 1480,
        intervalMs: 1000,
        timingAnchor: "castStart",
        timingScale: "fixed",
        actorType: "player",
        persistsAfterInterrupt: true,
      },
    ],
  },
  [ID.LEGENDARY_DEMON_STANCE_ID_28376]: {
    implemented: true,
    castTimeMs: 0,
    cooldown: 0,
    energyCost: 0,
    effects: [],
  },
  [ID.RELINQUISH_POWER]: {
    implemented: true,
    handlerId: "revenant.upkeep-release",
    castTimeMs: 0,
    cooldown: 0,
    energyCost: 0,
    effects: [],
    legendId: "LegendaryAssassin",
  },
  [ID.JADE_WINDS]: {
    implemented: true,
    castTimeMs: 1000,
    cooldown: 10,
    energyCost: 35,
    effects: [
      {
        type: "strike",
        coefficient: 3,
        hits: 1,
        name: "Jade Winds",
        actorType: "player",
      },
      {
        type: "condition",
        condition: "Vulnerability",
        stacks: 6,
        duration: 6,
        actorType: "player",
      },
    ],
    legendId: "LegendaryAssassin",
  },
  [ID.TEMPORAL_RIFT]: {
    implemented: true,
    quicknessCastTimeMs: 560,
    cooldown: 15,
    energyCost: 10,
    effects: [
      {
        type: "strike",
        coefficient: 0.75,
        hits: 1,
        name: "Temporal Rift",
        actorType: "player",
        atMs: 640,
        timingAnchor: "castEnd",
        timingScale: "fixed",
      },
      {
        type: "condition",
        condition: "Torment",
        stacks: 4,
        duration: 10,
        actorType: "player",
        atMs: 640,
        timingAnchor: "castEnd",
        timingScale: "fixed",
      },
      {
        type: "control",
        actorType: "player",
        atMs: 640,
        timingAnchor: "castEnd",
        timingScale: "fixed",
        metadata: {
          controlKind: "pull",
          duration: 300,
        },
      },
    ],
  },
  [ID.LEGENDARY_DWARF_STANCE]: {
    implemented: true,
    castTimeMs: 0,
    cooldown: 0,
    energyCost: 0,
    effects: [],
  },
  [ID.VENTARIS_WILL]: {
    implemented: true,
    castTimeMs: 0,
    cooldown: 0.25,
    energyCost: 0,
    effects: [],
    legendId: "LegendaryCentaur",
  },
  [ID.SHACKLING_WAVE]: {
    implemented: true,
    quicknessCastTimeMs: 800,
    cooldown: 15,
    energyCost: 10,
    effects: [
      {
        type: "strike",
        coefficient: 1.2,
        hits: 1,
        name: "Initial Damage",
        actorType: "player",
        atMs: 640,
        timingAnchor: "castStart",
        timingScale: "fixed",
      },
      {
        type: "strike",
        name: "Additional Strikes",
        actorType: "player",
        ticks: [
          { atMs: 720, coefficient: 0.4 },
          { atMs: 800, coefficient: 0.4 },
          { atMs: 880, coefficient: 0.4 },
          { atMs: 960, coefficient: 0.4 },
          { atMs: 1040, coefficient: 0.4 },
        ],
        timingAnchor: "castStart",
        timingScale: "fixed",
        metadata: {
          extendsResolutionHorizon: true,
        },
      },
      {
        type: "condition",
        condition: "Immobilized",
        stacks: 1,
        duration: 1,
        actorType: "player",
        atMs: 640,
        timingAnchor: "castStart",
        timingScale: "fixed",
      },
      {
        type: "condition",
        condition: "Vulnerability",
        stacks: 8,
        duration: 5,
        actorType: "player",
        atMs: 640,
        timingAnchor: "castStart",
        timingScale: "fixed",
      },
    ],
  },
  [ID.LEGENDARY_DEMON_STANCE]: {
    implemented: true,
    castTimeMs: 0,
    cooldown: 0,
    energyCost: 0,
    effects: [],
  },
  [ID.INSPIRING_REINFORCEMENT]: {
    implemented: true,
    handlerId: "revenant.inspiring-reinforcement",
    castTimeMs: 250,
    cooldown: 10,
    energyCost: 30,
    effects: [],
    legendId: "LegendaryDwarf",
  },
  [ID.HAMMER_BOLT]: {
    implemented: true,
    castTimeMs: 750,
    cooldown: 0,
    energyCost: 0,
    effects: [
      {
        type: "strike",
        coefficient: 0.9,
        hits: 1,
        name: "Hammer Bolt",
        actorType: "player",
        atMs: 481,
        timingAnchor: "castStart",
        timingScale: "fixed",
      },
    ],
  },
  [ID.DEATHSTRIKE_ID_28625]: {
    implemented: true,
    castTimeMs: 0,
    cooldown: 0,
    energyCost: 0,
    effects: [
      {
        type: "strike",
        coefficient: 2.67,
        hits: 1,
        name: "Final Strike Damage",
        actorType: "player",
      },
    ],
  },
  [ID.IGNITING_BRAND]: {
    implemented: true,
    castTimeMs: 500,
    cooldown: 12,
    energyCost: 10,
    effects: [
      {
        type: "strike",
        coefficient: 1.25,
        hits: 1,
        name: "Igniting Brand",
        actorType: "player",
      },
      {
        type: "condition",
        condition: "Burning",
        stacks: 1,
        duration: 1,
        actorType: "player",
      },
    ],
  },
  [ID.SPEAR_OF_ANGUISH]: {
    implemented: true,
    castTimeMs: 500,
    cooldown: 0,
    energyCost: 0,
    effects: [
      {
        type: "strike",
        coefficient: 0.8,
        hits: 1,
        name: "Spear of Anguish",
        actorType: "player",
      },
      {
        type: "condition",
        condition: "Torment",
        stacks: 1,
        duration: 8,
        actorType: "player",
      },
      {
        type: "condition",
        condition: "Torment",
        stacks: 1,
        duration: 4,
        actorType: "player",
      },
    ],
  },
  [ID.FRIGID_DISCHARGE]: {
    implemented: true,
    castTimeMs: 0,
    cooldown: 0,
    energyCost: 10,
    effects: [
      {
        type: "strike",
        coefficient: 2,
        hits: 1,
        name: "Frigid Discharge",
        actorType: "player",
      },
      {
        type: "condition",
        condition: "Chilled",
        stacks: 1,
        duration: 3,
        actorType: "player",
      },
    ],
  },
  [ID.DEVOUR_BRAND]: {
    implemented: true,
    castTimeMs: 500,
    cooldown: 0,
    energyCost: 10,
    effects: [
      {
        type: "strike",
        coefficient: 1.5,
        hits: 1,
        name: "Devour Brand",
        actorType: "player",
      },
    ],
  },
  [ID.VENOMOUS_SPHERE]: {
    implemented: true,
    castTimeMs: 750,
    cooldown: 8,
    energyCost: 5,
    effects: [
      {
        type: "strike",
        coefficient: 0.2,
        hits: 1,
        name: "Venomous Sphere",
        actorType: "player",
      },
      {
        type: "condition",
        condition: "Poisoned",
        stacks: 1,
        duration: 4,
        actorType: "player",
      },
    ],
  },
  [ID.RAPID_ASSAULT]: {
    implemented: true,
    castTimeMs: 1250,
    cooldown: 5,
    energyCost: 5,
    effects: [
      {
        type: "strike",
        coefficient: 24,
        hits: 8,
        name: "Rapid Assault",
        actorType: "player",
        atMs: 156,
        intervalMs: 156,
        timingAnchor: "castStart",
        timingScale: "cast",
      },
      {
        type: "condition",
        condition: "Vulnerability",
        stacks: 1,
        duration: 3,
        actorType: "player",
      },
    ],
  },
  [ID.RIFT_CONTAINMENT]: {
    implemented: true,
    castTimeMs: 500,
    cooldown: 20,
    energyCost: 20,
    effects: [
      {
        type: "strike",
        coefficient: 6.6000000000000005,
        hits: 5,
        name: "Rift Containment",
        actorType: "player",
        atMs: 100,
        intervalMs: 100,
        timingAnchor: "castStart",
        timingScale: "cast",
      },
    ],
  },
  [ID.RIFT_SLASH]: {
    implemented: true,
    quicknessCastTimeMs: 480,
    cooldown: 0,
    energyCost: 0,
    effects: [
      {
        type: "strike",
        coefficient: 0.9,
        hits: 1,
        name: "Rift Slash — Packet 1",
        actorType: "player",
        atMs: 400,
        timingAnchor: "castStart",
        timingScale: "fixed",
      },
      {
        type: "strike",
        coefficient: 0.2175,
        hits: 1,
        name: "Rift Damage",
        actorType: "player",
        atMs: 1400,
        timingAnchor: "castStart",
        timingScale: "fixed",
        metadata: {
          extendsResolutionHorizon: true,
        },
      },
    ],
  },
  [ID.SURGE_OF_THE_MISTS]: {
    implemented: true,
    castTimeMs: 1000,
    cooldown: 20,
    energyCost: 15,
    effects: [
      {
        type: "strike",
        coefficient: 29.160000000000004,
        hits: 9,
        name: "Surge of the Mists",
        actorType: "player",
        atMs: 111,
        intervalMs: 111,
        timingAnchor: "castStart",
        timingScale: "cast",
      },
      {
        type: "control",
        actorType: "player",
        metadata: {
          controlKind: "knockback",
          duration: 120,
        },
      },
    ],
  },
  [ID.REJUVENATING_ASSAULT]: {
    implemented: true,
    castTimeMs: 1000,
    cooldown: 0,
    energyCost: 0,
    effects: [
      {
        type: "strike",
        coefficient: 2,
        hits: 2,
        name: "Rejuvenating Assault",
        actorType: "player",
        atMs: 500,
        intervalMs: 500,
        timingAnchor: "castStart",
        timingScale: "cast",
      },
    ],
  },
  [ID.PREPARATION_THRUST]: {
    implemented: true,
    quicknessCastTimeMs: 360,
    cooldown: 0,
    energyCost: 0,
    effects: [
      {
        type: "strike",
        coefficient: 0.75,
        hits: 1,
        name: "Preparation Thrust",
        actorType: "player",
        atMs: 320,
        timingAnchor: "castStart",
        timingScale: "fixed",
      },
      {
        type: "condition",
        condition: "Vulnerability",
        stacks: 1,
        duration: 6,
        actorType: "player",
        atMs: 320,
        timingAnchor: "castStart",
        timingScale: "fixed",
      },
    ],
  },
  [ID.NATURAL_HARMONY_ID_29082]: {
    implemented: true,
    castTimeMs: 0,
    cooldown: 2,
    energyCost: 20,
    effects: [],
    legendId: "LegendaryCentaur",
  },
  [ID.ENERGY_EXPULSION_ID_29114]: {
    implemented: true,
    castTimeMs: 0,
    cooldown: 2,
    energyCost: 35,
    effects: [
      {
        type: "control",
        actorType: "player",
        metadata: {
          controlKind: "knockdown",
          duration: 3,
        },
      },
      {
        type: "boon",
        boon: "stability",
        duration: 5,
        stacks: 3,
      },
    ],
    legendId: "LegendaryCentaur",
  },
  [ID.MENDERS_REBUKE]: {
    implemented: true,
    castTimeMs: 750,
    cooldown: 5,
    energyCost: 5,
    effects: [
      {
        type: "strike",
        coefficient: 1.5,
        hits: 1,
        name: "Mender's Rebuke",
        actorType: "player",
      },
      {
        type: "condition",
        condition: "Weakness",
        stacks: 1,
        duration: 3,
        actorType: "player",
      },
    ],
  },
  [ID.PROJECT_TRANQUILITY]: {
    implemented: true,
    castTimeMs: 0,
    cooldown: 2,
    energyCost: 0,
    effects: [],
    legendId: "LegendaryCentaur",
  },
  [ID.RAPID_SWIPE]: {
    implemented: true,
    castTimeMs: 500,
    cooldown: 0,
    energyCost: 0,
    effects: [
      {
        type: "strike",
        coefficient: 0.65,
        hits: 1,
        name: "Rapid Swipe",
        actorType: "player",
      },
    ],
  },
  [ID.PURIFYING_ESSENCE_ID_29197]: {
    implemented: true,
    castTimeMs: 0,
    cooldown: 5,
    energyCost: 25,
    effects: [],
    legendId: "LegendaryCentaur",
  },
  [ID.RIPOSTING_SHADOWS]: {
    implemented: true,
    castTimeMs: 0,
    cooldown: 0,
    energyCost: 30,
    effects: [
      {
        type: "boon",
        boon: "fury",
        duration: 6,
        stacks: 1,
      },
    ],
    legendId: "LegendaryAssassin",
  },
  [ID.CHILLING_ISOLATION]: {
    implemented: true,
    castTimeMs: 680,
    unaffectedByQuickness: true,
    paletteInterruptMs: 480,
    interruptCommitMs: 420,
    cooldown: 5,
    energyCost: 5,
    effects: [
      {
        type: "strike",
        coefficient: 0.8,
        hits: 1,
        name: "Chilling Isolation — Packet 1",
        actorType: "player",
        atMs: 280,
        timingAnchor: "castStart",
        timingScale: "fixed",
      },
      {
        type: "strike",
        coefficient: 1.6,
        hits: 1,
        name: "Isolated Damage",
        actorType: "player",
        atMs: 480,
        timingAnchor: "castStart",
        timingScale: "fixed",
        persistsAfterInterrupt: true,
        metadata: {
          extendsResolutionHorizon: true,
        },
      },
      {
        type: "condition",
        condition: "Chilled",
        stacks: 1,
        duration: 2,
        actorType: "player",
        atMs: 280,
        timingAnchor: "castStart",
        timingScale: "fixed",
      },
    ],
  },
  [ID.BRUTAL_BLADE]: {
    implemented: true,
    quicknessCastTimeMs: 560,
    cooldown: 0,
    energyCost: 0,
    effects: [
      {
        type: "strike",
        coefficient: 0.8,
        hits: 1,
        name: "Brutal Blade",
        actorType: "player",
        atMs: 480,
        timingAnchor: "castStart",
        timingScale: "fixed",
      },
      {
        type: "condition",
        condition: "Vulnerability",
        stacks: 2,
        duration: 6,
        actorType: "player",
        atMs: 480,
        timingAnchor: "castStart",
        timingScale: "fixed",
      },
    ],
  },
  [ID.WARDING_RIFT]: {
    implemented: true,
    castTimeMs: 1500,
    cooldown: 12,
    energyCost: 10,
    effects: [
      {
        type: "strike",
        coefficient: 0.4,
        hits: 1,
        name: "Warding Rift",
        actorType: "player",
      },
      {
        type: "blind",
        actorType: "player",
      },
    ],
  },
  [ID.PROTECTIVE_SOLACE_ID_29310]: {
    implemented: true,
    handlerId: "revenant.upkeep",
    castTimeMs: 0,
    cooldown: 5,
    energyCost: 5,
    upkeepCost: 8,
    effects: [],
    legendId: "LegendaryCentaur",
  },
  [ID.RENEWING_WAVE]: {
    implemented: true,
    castTimeMs: 1000,
    cooldown: 15,
    energyCost: 15,
    effects: [],
  },
  [ID.FORCEFUL_BASH]: {
    implemented: true,
    castTimeMs: 500,
    cooldown: 0,
    energyCost: 0,
    effects: [
      {
        type: "strike",
        coefficient: 0.75,
        hits: 1,
        name: "Forceful Bash",
        actorType: "player",
      },
    ],
  },
  [ID.HEALING_ORB]: {
    implemented: true,
    castTimeMs: 0,
    cooldown: 0,
    energyCost: 0,
    effects: [],
  },
  [ID.ENVOY_OF_EXUBERANCE]: {
    implemented: true,
    castTimeMs: 750,
    cooldown: 15,
    energyCost: 8,
    effects: [
      {
        type: "boon",
        boon: "protection",
        duration: 3,
        stacks: 1,
      },
      {
        type: "boon",
        boon: "aegis",
        duration: 4,
        stacks: 1,
      },
    ],
  },
  [ID.JADE_WINDS_ID_31294]: {
    implemented: true,
    castTimeMs: 1000,
    cooldown: 10,
    energyCost: 35,
    effects: [
      {
        type: "strike",
        coefficient: 3,
        hits: 1,
        name: "Jade Winds",
        actorType: "player",
      },
      {
        type: "condition",
        condition: "Vulnerability",
        stacks: 6,
        duration: 6,
        actorType: "player",
      },
    ],
    legendId: "LegendaryAssassin",
  },
  [ID.RITE_OF_THE_GREAT_DWARF_TRAIT_SKILL]: {
    implemented: true,
    castTimeMs: 0,
    cooldown: 45,
    energyCost: 0,
    effects: [],
    legendId: "LegendaryDwarf",
  },
  [ID.VENGEFUL_SNOWBALLS]: {
    implemented: true,
    castTimeMs: 0,
    cooldown: 45,
    energyCost: 0,
    effects: [
      {
        type: "condition",
        condition: "Chilled",
        stacks: 1,
        duration: 2,
        actorType: "player",
      },
    ],
  },
  [ID.BLOODBANE_PATH]: {
    implemented: true,
    castTimeMs: 760,
    unaffectedByQuickness: true,
    cooldown: 3,
    energyCost: 4,
    effects: [
      {
        type: "strike",
        name: "Bloodbane Path",
        actorType: "player",
        ticks: [
          { atMs: 600, coefficient: 0.4 },
          { atMs: 720, coefficient: 0.4 },
          { atMs: 840, coefficient: 0.4 },
        ],
        timingAnchor: "castStart",
        timingScale: "fixed",
      },
      {
        type: "condition",
        condition: "Bleeding",
        stacks: 3,
        duration: 6,
        actorType: "player",
      },
    ],
  },
  [ID.SHATTERSHOT]: {
    implemented: true,
    castTimeMs: 480,
    unaffectedByQuickness: true,
    cooldown: 0,
    energyCost: 0,
    finisherType: "Projectile",
    finisherValue: 0.2,
    effects: [
      {
        type: "strike",
        coefficient: 0.65,
        hits: 1,
        name: "Shattershot",
        actorType: "player",
        atMs: 400,
        timingAnchor: "castStart",
        timingScale: "fixed",
      },
      {
        type: "condition",
        condition: "Bleeding",
        stacks: 1,
        duration: 3,
        actorType: "player",
      },
    ],
  },
  [ID.SCORCHRAZOR]: {
    implemented: true,
    castTimeMs: 520,
    cooldown: 12,
    energyCost: 16,
    effects: [
      {
        type: "strike",
        coefficient: 1,
        hits: 1,
        name: "Scorchrazor",
        actorType: "player",
        atMs: 440,
        timingAnchor: "castStart",
        timingScale: "fixed",
      },
      {
        type: "condition",
        condition: "Burning",
        stacks: 1,
        duration: 4,
        actorType: "player",
        atMs: 440,
        timingAnchor: "castStart",
        timingScale: "fixed",
      },
      {
        type: "control",
        actorType: "player",
        atMs: 440,
        timingAnchor: "castStart",
        timingScale: "fixed",
        metadata: {
          controlKind: "knockdown",
          duration: 2,
        },
      },
    ],
  },
  [ID.SEVENSHOT]: {
    implemented: true,
    castTimeMs: 440,
    unaffectedByQuickness: true,
    cooldown: 7,
    energyCost: 7,
    finisherType: "Projectile",
    finisherValue: 0.2,
    effects: [
      {
        type: "strike",
        name: "Sevenshot",
        actorType: "player",
        ticks: [
          { atMs: 0, coefficient: 0.31 },
          { atMs: 160, coefficient: 0.31 },
          { atMs: 200, coefficient: 0.31 },
          { atMs: 360, coefficient: 0.31 },
          { atMs: 400, coefficient: 0.31 },
          { atMs: 600, coefficient: 0.31 },
          { atMs: 600, coefficient: 0.31 },
        ],
        timingAnchor: "castEnd",
        timingScale: "fixed",
      },
      {
        type: "condition",
        actorType: "player",
        ticks: [
          { atMs: 0, condition: "Torment", stacks: 1, duration: 4 },
          { atMs: 160, condition: "Torment", stacks: 1, duration: 4 },
          { atMs: 200, condition: "Torment", stacks: 1, duration: 4 },
          { atMs: 360, condition: "Torment", stacks: 1, duration: 4 },
          { atMs: 400, condition: "Torment", stacks: 1, duration: 4 },
          { atMs: 600, condition: "Torment", stacks: 1, duration: 4 },
          { atMs: 600, condition: "Torment", stacks: 1, duration: 4 },
        ],
        timingAnchor: "castEnd",
        timingScale: "fixed",
      },
    ],
  },
  [ID.LEGENDARY_RENEGADE_STANCE]: {
    implemented: true,
    castTimeMs: 0,
    cooldown: 0,
    energyCost: 0,
    effects: [],
  },
  [ID.SPIRITCRUSH]: {
    implemented: true,
    castTimeMs: 400,
    unaffectedByQuickness: true,
    cooldown: 9,
    energyCost: 12,
    comboField: "Fire",
    duration: 3,
    effects: [
      {
        type: "strike",
        coefficient: 1.25,
        hits: 1,
        name: "Initial Damage",
        actorType: "player",
        atMs: 1320,
        timingAnchor: "castEnd",
        timingScale: "fixed",
      },
      {
        type: "strike",
        coefficient: 0.75,
        hits: 3,
        name: "Spiritcrush — Fire Field",
        actorType: "player",
        atMs: 2320,
        intervalMs: 1000,
        timingAnchor: "castEnd",
        timingScale: "fixed",
        metadata: {
          extendsResolutionHorizon: true,
        },
      },
      {
        type: "condition",
        condition: "Burning",
        stacks: 1,
        duration: 3,
        applications: 4,
        atMs: 1320,
        intervalMs: 1000,
        timingAnchor: "castEnd",
        timingScale: "fixed",
        actorType: "player",
      },
      {
        type: "condition",
        condition: "Slow",
        stacks: 1,
        duration: 1.5,
        applications: 4,
        atMs: 1320,
        intervalMs: 1000,
        timingAnchor: "castEnd",
        timingScale: "fixed",
        actorType: "player",
      },
    ],
  },
  [ID.ESSENCE_SAP_DOPPELGANGER]: {
    implemented: true,
    castTimeMs: 250,
    cooldown: 0,
    energyCost: 0,
    effects: [
      {
        type: "strike",
        coefficient: 0.5,
        hits: 1,
        name: "Essence Sap (Doppelganger)",
        actorType: "player",
      },
      {
        type: "condition",
        condition: "Slow",
        stacks: 1,
        duration: 1,
        actorType: "player",
      },
    ],
  },
  [ID.LEGENDARY_RENEGADE_STANCE_ID_46409]: {
    implemented: true,
    castTimeMs: 0,
    cooldown: 0,
    energyCost: 0,
    effects: [],
  },
  [ID.CALL_OF_THE_DWARF]: {
    implemented: true,
    castTimeMs: 0,
    cooldown: 0,
    energyCost: 0,
    effects: [
      {
        type: "strike",
        coefficient: 0.75,
        hits: 1,
        name: "Call of the Dwarf",
        actorType: "player",
      },
      {
        type: "condition",
        condition: "Weakness",
        stacks: 1,
        duration: 5,
        actorType: "player",
      },
    ],
  },
  [ID.CALL_OF_THE_CENTAUR]: {
    implemented: true,
    castTimeMs: 0,
    cooldown: 0,
    energyCost: 0,
    effects: [],
  },
  [ID.CALL_OF_THE_RENEGADE]: {
    implemented: true,
    castTimeMs: 0,
    cooldown: 0,
    energyCost: 0,
    effects: [
      {
        type: "strike",
        coefficient: 0.5,
        hits: 1,
        name: "Call of the Renegade",
        actorType: "player",
      },
      {
        type: "condition",
        condition: "Bleeding",
        stacks: 2,
        duration: 8,
        actorType: "player",
      },
    ],
  },
  [ID.CALL_OF_THE_ASSASSIN]: {
    implemented: true,
    castTimeMs: 0,
    cooldown: 0,
    energyCost: 0,
    effects: [
      {
        type: "strike",
        coefficient: 0.93,
        hits: 1,
        name: "Call of the Assassin",
        actorType: "player",
      },
      {
        type: "condition",
        condition: "Vulnerability",
        stacks: 8,
        duration: 5,
        actorType: "player",
      },
      {
        type: "boon",
        boon: "Quickness",
        duration: 2,
        stacks: 1,
      },
      {
        type: "boon",
        boon: "Quickness",
        duration: 1,
        stacks: 1,
      },
    ],
  },
  [ID.CALL_OF_THE_DEMON]: {
    implemented: true,
    castTimeMs: 0,
    cooldown: 0,
    energyCost: 0,
    effects: [
      {
        type: "strike",
        coefficient: 0.9,
        hits: 1,
        name: "Call of the Demon",
        actorType: "player",
      },
      {
        type: "condition",
        condition: "Slow",
        stacks: 1,
        duration: 3,
        actorType: "player",
      },
      {
        type: "condition",
        condition: "Torment",
        stacks: 2,
        duration: 8,
        actorType: "player",
      },
    ],
  },
  [ID.CALL_OF_THE_DRAGON]: {
    implemented: true,
    castTimeMs: 0,
    cooldown: 0,
    energyCost: 0,
    effects: [
      {
        type: "strike",
        coefficient: 0.75,
        hits: 1,
        name: "Call of the Dragon",
        actorType: "player",
      },
      {
        type: "condition",
        condition: "Burning",
        stacks: 2,
        duration: 3,
        actorType: "player",
      },
      {
        type: "condition",
        condition: "Chilled",
        stacks: 1,
        duration: 3,
        actorType: "player",
      },
    ],
  },
  [ID.UNCHAINED_DESOLATION]: {
    implemented: true,
    castTimeMs: 2000,
    cooldown: 5,
    energyCost: 0,
    effects: [],
  },
  [ID.LEGENDARY_PRISONER_STANCE]: {
    implemented: true,
    castTimeMs: 0,
    cooldown: 0,
    energyCost: 0,
    effects: [],
  },
  [ID.RIFT_OF_PAIN]: {
    implemented: true,
    castTimeMs: 750,
    cooldown: 8,
    energyCost: 5,
    effects: [
      {
        type: "strike",
        coefficient: 0.25,
        hits: 1,
        name: "Rift of Pain",
        actorType: "player",
      },
      {
        type: "condition",
        condition: "Chilled",
        stacks: 1,
        duration: 1,
        actorType: "player",
      },
      {
        type: "boon",
        boon: "protection",
        duration: 1.5,
        stacks: 1,
      },
    ],
  },
  [ID.MISTSFIRE]: {
    implemented: true,
    castTimeMs: 500,
    cooldown: 0,
    energyCost: 0,
    effects: [
      {
        type: "strike",
        coefficient: 0.6,
        hits: 1,
        name: "Mistsfire",
        actorType: "player",
      },
      {
        type: "condition",
        condition: "Torment",
        stacks: 1,
        duration: 6,
        actorType: "player",
      },
      {
        type: "condition",
        condition: "Vulnerability",
        stacks: 1,
        duration: 10,
        actorType: "player",
      },
      {
        type: "condition",
        condition: "Weakness",
        stacks: 1,
        duration: 2,
        actorType: "player",
      },
      {
        type: "condition",
        condition: "Burning",
        stacks: 1,
        duration: 1.75,
        actorType: "player",
      },
      {
        type: "condition",
        condition: "Slow",
        stacks: 1,
        duration: 0.5,
        actorType: "player",
      },
    ],
  },
  [ID.RECKONING_BLAST]: {
    implemented: true,
    castTimeMs: 1000,
    cooldown: 15,
    energyCost: 10,
    effects: [
      {
        type: "strike",
        coefficient: 0.8,
        hits: 2,
        name: "Reckoning Blast",
        actorType: "player",
        atMs: 500,
        intervalMs: 500,
        timingAnchor: "castStart",
        timingScale: "cast",
      },
      {
        type: "condition",
        condition: "Torment",
        stacks: 2,
        duration: 6,
        actorType: "player",
      },
      {
        type: "condition",
        condition: "Vulnerability",
        stacks: 3,
        duration: 10,
        actorType: "player",
      },
      {
        type: "condition",
        condition: "Weakness",
        stacks: 1,
        duration: 2,
        actorType: "player",
      },
      {
        type: "condition",
        condition: "Burning",
        stacks: 2,
        duration: 1.5,
        actorType: "player",
      },
      {
        type: "condition",
        condition: "Slow",
        stacks: 1,
        duration: 1,
        actorType: "player",
      },
      {
        type: "control",
        actorType: "player",
        metadata: {
          controlKind: "knockback",
          duration: 400,
        },
      },
    ],
  },
  [ID.PORTAL_FIRE]: {
    implemented: true,
    castTimeMs: 1250,
    cooldown: 6,
    energyCost: 5,
    effects: [
      {
        type: "strike",
        coefficient: 21.12,
        hits: 8,
        name: "Portal Fire",
        actorType: "player",
        atMs: 156,
        intervalMs: 156,
        timingAnchor: "castStart",
        timingScale: "cast",
      },
      {
        type: "condition",
        condition: "Torment",
        stacks: 1,
        duration: 6,
        actorType: "player",
      },
      {
        type: "condition",
        condition: "Vulnerability",
        stacks: 1,
        duration: 10,
        actorType: "player",
      },
      {
        type: "condition",
        condition: "Weakness",
        stacks: 1,
        duration: 2,
        actorType: "player",
      },
      {
        type: "condition",
        condition: "Burning",
        stacks: 1,
        duration: 1.5,
        actorType: "player",
      },
      {
        type: "condition",
        condition: "Slow",
        stacks: 1,
        duration: 0.5,
        actorType: "player",
      },
    ],
  },
  [ID.TORRENTIAL_MISTS]: {
    implemented: true,
    castTimeMs: 2000,
    cooldown: 20,
    energyCost: 20,
    effects: [
      {
        type: "strike",
        coefficient: 106.47999999999999,
        hits: 22,
        name: "Torrential Mists",
        actorType: "player",
        atMs: 91,
        intervalMs: 91,
        timingAnchor: "castStart",
        timingScale: "cast",
      },
      {
        type: "condition",
        condition: "Torment",
        stacks: 1,
        duration: 6,
        actorType: "player",
      },
      {
        type: "condition",
        condition: "Vulnerability",
        stacks: 1,
        duration: 10,
        actorType: "player",
      },
      {
        type: "condition",
        condition: "Weakness",
        stacks: 1,
        duration: 2,
        actorType: "player",
      },
      {
        type: "condition",
        condition: "Burning",
        stacks: 1,
        duration: 1.5,
        actorType: "player",
      },
      {
        type: "condition",
        condition: "Slow",
        stacks: 1,
        duration: 0.5,
        actorType: "player",
      },
    ],
  },
  [ID.ANCIENT_ECHO]: {
    implemented: true,
    handlerId: "revenant.ancient-echo",
    castTimeMs: 500,
    cooldown: 20,
    energyCost: 0,
    effects: [
      {
        type: "boon",
        boon: "regeneration",
        duration: 5,
        stacks: 1,
      },
      {
        type: "boon",
        boon: "Resistance",
        duration: 3,
        stacks: 1,
      },
    ],
  },
  [ID.SOOTHING_STONE_ID_56661]: {
    implemented: true,
    castTimeMs: 1000,
    cooldown: 30,
    energyCost: 5,
    effects: [
      {
        type: "boon",
        boon: "resolution",
        duration: 5,
        stacks: 1,
      },
    ],
    legendId: "LegendaryDwarf",
  },
  [ID.FORCED_ENGAGEMENT_ID_56662]: {
    implemented: true,
    castTimeMs: 500,
    cooldown: 15,
    energyCost: 10,
    effects: [
      {
        type: "strike",
        coefficient: 0.5,
        hits: 1,
        name: "Forced Engagement",
        actorType: "player",
      },
      {
        type: "condition",
        condition: "Slow",
        stacks: 1,
        duration: 4,
        actorType: "player",
      },
      {
        type: "control",
        actorType: "player",
        metadata: {
          controlKind: "taunt",
          duration: 4,
        },
      },
    ],
    legendId: "LegendaryDwarf",
  },
  [ID.VENGEFUL_HAMMERS_ID_56752]: {
    implemented: true,
    handlerId: "revenant.upkeep",
    castTimeMs: 0,
    cooldown: 0,
    energyCost: 5,
    upkeepCost: 6,
    effects: [],
    legendId: "LegendaryDwarf",
  },
  [ID.RITE_OF_THE_GREAT_DWARF_ID_56773]: {
    implemented: true,
    castTimeMs: 1250,
    cooldown: 0,
    energyCost: 40,
    effects: [],
    legendId: "LegendaryDwarf",
  },
  [ID.INSPIRING_REINFORCEMENT_ID_56841]: {
    implemented: true,
    castTimeMs: 250,
    cooldown: 10,
    energyCost: 30,
    effects: [
      {
        type: "strike",
        coefficient: 7.5,
        hits: 5,
        name: "Inspiring Reinforcement",
        actorType: "player",
        atMs: 50,
        intervalMs: 50,
        timingAnchor: "castStart",
        timingScale: "cast",
      },
      {
        type: "condition",
        condition: "Weakness",
        stacks: 1,
        duration: 6,
        actorType: "player",
      },
      {
        type: "boon",
        boon: "stability",
        duration: 3,
        stacks: 1,
      },
      {
        type: "boon",
        boon: "stability",
        duration: 3,
        stacks: 1,
      },
    ],
    legendId: "LegendaryDwarf",
  },
  [ID.INVOKE_TORMENT]: {
    implemented: true,
    castTimeMs: 0,
    cooldown: 0,
    energyCost: 0,
    effects: [
      {
        type: "strike",
        coefficient: 1,
        hits: 1,
        name: "Invoke Torment",
        actorType: "player",
      },
      {
        type: "condition",
        condition: "Torment",
        stacks: 1,
        duration: 10,
        actorType: "player",
      },
    ],
  },
  [ID.MIST_SLASH]: {
    implemented: true,
    castTimeMs: 600,
    unaffectedByQuickness: true,
    cooldown: 0,
    energyCost: 0,
    effects: [
      {
        type: "strike",
        coefficient: 0.8,
        hits: 1,
        name: "Mist Slash",
        actorType: "player",
        atMs: 400,
        timingAnchor: "castStart",
        timingScale: "fixed",
      },
      {
        type: "condition",
        condition: "Vulnerability",
        stacks: 1,
        duration: 10,
        actorType: "player",
        atMs: 400,
        timingAnchor: "castStart",
        timingScale: "fixed",
      },
    ],
  },
  [ID.MIST_UNLEASHED]: {
    implemented: true,
    quicknessCastTimeMs: 520,
    cooldown: 3,
    energyCost: 5,
    effects: [
      {
        type: "strike",
        coefficient: 1.6,
        hits: 1,
        name: "Mist Unleashed",
        actorType: "player",
        atMs: 400,
        timingAnchor: "castStart",
        timingScale: "fixed",
      },
      {
        type: "condition",
        condition: "Vulnerability",
        stacks: 3,
        duration: 10,
        actorType: "player",
      },
    ],
  },
  [ID.CALL_OF_THE_ALLIANCE]: {
    implemented: true,
    castTimeMs: 0,
    cooldown: 0,
    energyCost: 0,
    effects: [
      {
        type: "strike",
        coefficient: 0.93,
        hits: 1,
        name: "Call of the Alliance",
        actorType: "player",
      },
    ],
  },
  [ID.PHANTOMS_ONSLAUGHT_ID_62713]: {
    implemented: true,
    quicknessCastTimeMs: 438,
    dashTimeMs: 38,
    hitDelayMs: 400,
    cooldown: 8,
    rechargeAnchor: "castStart",
    rechargeOffsetMs: 420,
    energyCost: 8,
    effects: [
      {
        type: "strike",
        coefficient: 1.6,
        hits: 1,
        name: "Phantom's Onslaught",
        actorType: "player",
      },
      {
        type: "condition",
        condition: "Chilled",
        stacks: 1,
        duration: 3,
        actorType: "player",
      },
      {
        type: "boon",
        boon: "fury",
        duration: 3,
        stacks: 1,
      },
    ],
  },
  [ID.ARCING_MISTS]: {
    implemented: true,
    castTimeMs: 680,
    unaffectedByQuickness: true,
    cooldown: 0,
    energyCost: 0,
    effects: [
      {
        type: "strike",
        coefficient: 1.2,
        hits: 1,
        name: "Arcing Mists",
        actorType: "player",
        atMs: 440,
        timingAnchor: "castStart",
        timingScale: "fixed",
      },
      {
        type: "condition",
        condition: "Chilled",
        stacks: 1,
        duration: 3,
        actorType: "player",
        atMs: 440,
        timingAnchor: "castStart",
        timingScale: "fixed",
      },
      {
        type: "condition",
        condition: "Vulnerability",
        stacks: 2,
        duration: 10,
        actorType: "player",
        atMs: 440,
        timingAnchor: "castStart",
        timingScale: "fixed",
      },
    ],
  },
  [ID.TRUE_STRIKE]: {
    implemented: true,
    castTimeMs: 750,
    cooldown: 0,
    energyCost: 0,
    effects: [
      {
        type: "strike",
        coefficient: 1.5,
        hits: 1,
        name: "True Strike (vindicator) — Packet 1",
        actorType: "player",
      },
    ],
  },
  [ID.LEGENDARY_ALLIANCE_STANCE]: {
    implemented: true,
    castTimeMs: 0,
    cooldown: 0,
    energyCost: 0,
    effects: [],
  },
  [ID.PHANTOMS_ONSLAUGHT]: {
    implemented: true,
    quicknessCastTimeMs: 438,
    dashTimeMs: 38,
    hitDelayMs: 400,
    cooldown: 8,
    rechargeAnchor: "castStart",
    rechargeOffsetMs: 420,
    energyCost: 8,
    effects: [
      {
        type: "strike",
        coefficient: 1.6,
        hits: 1,
        name: "Phantom's Onslaught",
        actorType: "player",
      },
      {
        type: "condition",
        condition: "Chilled",
        stacks: 1,
        duration: 3,
        actorType: "player",
      },
      {
        type: "boon",
        boon: "fury",
        duration: 3,
        stacks: 1,
      },
    ],
  },
  [ID.MIST_SWING]: {
    implemented: true,
    castTimeMs: 400,
    unaffectedByQuickness: true,
    cooldown: 0,
    energyCost: 0,
    effects: [
      {
        type: "strike",
        coefficient: 0.7,
        hits: 1,
        name: "Mist Swing",
        actorType: "player",
      },
    ],
  },
  [ID.IMPERIAL_GUARD]: {
    implemented: true,
    castTimeMs: 2000,
    unaffectedByQuickness: true,
    defaultInterruptMs: 80,
    cooldown: 12,
    energyCost: 10,
    effects: [],
  },
  [ID.ETERNITYS_REQUIEM]: {
    implemented: true,
    quicknessCastTimeMs: 840,
    cooldown: 15,
    energyCost: 10,
    effects: [
      {
        type: "strike",
        name: "Eternity's Requiem",
        actorType: "player",
        timingAnchor: "castEnd",
        timingScale: "fixed",
        ticks: [
          // Median packet positions by hit rank across the supplied logs.
          // Individual uses vary from six to ten target hits.
          { atMs: 323, coefficient: 1 },
          { atMs: 401, coefficient: 0.9 },
          { atMs: 521, coefficient: 0.8 },
          { atMs: 605, coefficient: 0.7 },
          { atMs: 646, coefficient: 0.6 },
          { atMs: 722, coefficient: 0.5 },
          { atMs: 838, coefficient: 0.4 },
          { atMs: 922, coefficient: 0.3 },
        ],
        metadata: {
          extendsResolutionHorizon: true,
        },
      },
    ],
  },
  [ID.BLOSSOMING_AURA]: {
    implemented: true,
    castTimeMs: 750,
    cooldown: 8,
    energyCost: 10,
    effects: [
      {
        type: "strike",
        coefficient: 4.8,
        hits: 4,
        name: "Pulsing Damage",
        actorType: "player",
        atMs: 188,
        intervalMs: 188,
        timingAnchor: "castStart",
        timingScale: "cast",
      },
      {
        type: "strike",
        coefficient: 1,
        hits: 1,
        name: "Final Damage",
        actorType: "player",
      },
      {
        type: "condition",
        condition: "Weakness",
        stacks: 1,
        duration: 3,
        actorType: "player",
      },
    ],
  },
  [ID.OTHERWORLDLY_ATTRACTION_ALLY]: {
    implemented: true,
    castTimeMs: 0,
    cooldown: 5,
    energyCost: 10,
    effects: [],
  },
  [ID.DEACTIVATE_OTHERWORLDLY_BOND]: {
    implemented: true,
    castTimeMs: 0,
    cooldown: 0,
    energyCost: 0,
    effects: [],
  },
  [ID.OTHERWORLDLY_ATTRACTION_ENEMY]: {
    implemented: true,
    castTimeMs: 500,
    cooldown: 0,
    energyCost: 10,
    effects: [
      {
        type: "condition",
        condition: "Vulnerability",
        stacks: 6,
        duration: 10,
        actorType: "player",
      },
    ],
  },
  [ID.ACERBIC_CUT]: {
    implemented: true,
    castTimeMs: 500,
    cooldown: 0,
    energyCost: 0,
    effects: [
      {
        type: "strike",
        coefficient: 0.533,
        hits: 1,
        name: "Acerbic Cut",
        actorType: "player",
      },
      {
        type: "boon",
        boon: "might",
        duration: 9,
        stacks: 2,
      },
    ],
  },
  [ID.SERENE_SLASH]: {
    implemented: true,
    castTimeMs: 500,
    cooldown: 0,
    energyCost: 0,
    effects: [
      {
        type: "strike",
        coefficient: 0.533,
        hits: 1,
        name: "Serene Slash",
        actorType: "player",
      },
    ],
  },
  [ID.MOTIVATING_WHIRL]: {
    implemented: true,
    castTimeMs: 500,
    cooldown: 0,
    energyCost: 0,
    effects: [
      {
        type: "strike",
        coefficient: 1,
        hits: 1,
        name: "Motivating Whirl",
        actorType: "player",
      },
    ],
  },
  [ID.OTHERWORLDLY_BOND]: {
    implemented: true,
    castTimeMs: 750,
    cooldown: 8,
    energyCost: 5,
    effects: [
      {
        type: "condition",
        condition: "Vulnerability",
        stacks: 1,
        duration: 10,
        actorType: "player",
      },
      {
        type: "condition",
        condition: "Crippled",
        stacks: 1,
        duration: 2,
        actorType: "player",
      },
      {
        type: "condition",
        condition: "Slow",
        stacks: 1,
        duration: 1,
        actorType: "player",
      },
      {
        type: "boon",
        boon: "might",
        duration: 9,
        stacks: 1,
      },
      {
        type: "boon",
        boon: "fury",
        duration: 3,
        stacks: 1,
      },
    ],
  },
  [ID.DETONATE_BLOSSOMING_AURA]: {
    implemented: true,
    castTimeMs: 0,
    cooldown: 0,
    energyCost: 0,
    effects: [],
  },
  [ID.ABYSSAL_FIRE]: {
    implemented: true,
    handlerId: "revenant.spear-recharge",
    simulatorExcluded: true,
    quicknessCastTimeMs: 460,
    cooldown: 0,
    energyCost: 0,
    flipParentId: null,
    effects: [
      {
        type: "strike",
        coefficient: 0.85,
        hits: 1,
        name: "Abyssal Fire",
        actorType: "player",
      },
      {
        type: "condition",
        condition: "Torment",
        stacks: 1,
        duration: 3,
        actorType: "player",
      },
      {
        type: "condition",
        condition: "Vulnerability",
        stacks: 1,
        duration: 6,
        actorType: "player",
      },
    ],
  },
  [ID.ABYSSAL_BLITZ]: {
    implemented: true,
    handlerId: "revenant.spear-recharge",
    quicknessCastTimeMs: 520,
    cooldown: 10,
    energyCost: 10,
    effects: [
      {
        type: "strike",
        name: "Abyssal Blitz — Mine",
        actorType: "player",
        timingAnchor: "castStart",
        timingScale: "fixed",
        persistsAfterInterrupt: true,
        ticks: [
          { atMs: 560, coefficient: 0.5 },
          { atMs: 720, coefficient: 0.5 },
          { atMs: 960, coefficient: 0.5 },
        ],
        metadata: {
          extendsResolutionHorizon: true,
        },
      },
      {
        type: "condition",
        timingAnchor: "castStart",
        timingScale: "fixed",
        actorType: "player",
        persistsAfterInterrupt: true,
        ticks: [
          { atMs: 560, condition: "Slow", stacks: 1, duration: 3 },
          { atMs: 720, condition: "Slow", stacks: 1, duration: 3 },
          { atMs: 960, condition: "Slow", stacks: 1, duration: 3 },
        ],
        metadata: {
          extendsResolutionHorizon: true,
        },
      },
      {
        type: "condition",
        timingAnchor: "castStart",
        timingScale: "fixed",
        actorType: "player",
        persistsAfterInterrupt: true,
        ticks: [
          { atMs: 560, condition: "Chilled", stacks: 1, duration: 3 },
          { atMs: 720, condition: "Chilled", stacks: 1, duration: 3 },
          { atMs: 960, condition: "Chilled", stacks: 1, duration: 3 },
        ],
        metadata: {
          extendsResolutionHorizon: true,
        },
      },
      {
        type: "condition",
        timingAnchor: "castStart",
        timingScale: "fixed",
        actorType: "player",
        persistsAfterInterrupt: true,
        ticks: [
          { atMs: 560, condition: "Weakness", stacks: 1, duration: 3 },
          { atMs: 720, condition: "Weakness", stacks: 1, duration: 3 },
          { atMs: 960, condition: "Weakness", stacks: 1, duration: 3 },
        ],
        metadata: {
          extendsResolutionHorizon: true,
        },
      },
    ],
  },
  [ID.ABYSSAL_BLOT]: {
    implemented: true,
    handlerId: "revenant.spear-recharge",
    quicknessCastTimeMs: 800,
    cooldown: 15,
    energyCost: 12,
    effects: [
      {
        type: "strike",
        name: "Abyssal Blot",
        actorType: "player",
        timingAnchor: "castStart",
        timingScale: "fixed",
        persistsAfterInterrupt: true,
        ticks: [
          { atMs: 960, coefficient: 0.4 },
          { atMs: 1240, coefficient: 0.4 },
          { atMs: 1520, coefficient: 0.4 },
          { atMs: 1800, coefficient: 0.4 },
          { atMs: 2080, coefficient: 0.4 },
        ],
        metadata: {
          extendsResolutionHorizon: true,
        },
      },
      {
        type: "condition",
        timingAnchor: "castStart",
        timingScale: "fixed",
        actorType: "player",
        persistsAfterInterrupt: true,
        ticks: [
          { atMs: 960, condition: "Poisoned", stacks: 1, duration: 6 },
          { atMs: 1240, condition: "Poisoned", stacks: 1, duration: 6 },
          { atMs: 1520, condition: "Poisoned", stacks: 1, duration: 6 },
          { atMs: 1800, condition: "Poisoned", stacks: 1, duration: 6 },
          { atMs: 2080, condition: "Poisoned", stacks: 1, duration: 6 },
        ],
        metadata: {
          extendsResolutionHorizon: true,
        },
      },
      {
        type: "condition",
        condition: "Chilled",
        stacks: 1,
        duration: 2,
        atMs: 960,
        timingAnchor: "castStart",
        timingScale: "fixed",
        persistsAfterInterrupt: true,
        actorType: "player",
      },
      {
        type: "control",
        actorType: "player",
        atMs: 960,
        timingAnchor: "castStart",
        timingScale: "fixed",
        persistsAfterInterrupt: true,
        metadata: {
          controlKind: "pull",
          duration: 180,
        },
      },
    ],
  },
  [ID.ABYSSAL_FORCE]: {
    implemented: true,
    handlerId: "revenant.spear-recharge",
    quicknessCastTimeMs: 520,
    cooldown: 6,
    energyCost: 4,
    effects: [
      {
        type: "strike",
        coefficient: 0.8,
        hits: 1,
        name: "Abyssal Force",
        actorType: "player",
        atMs: 1162,
        timingAnchor: "castStart",
        timingScale: "fixed",
        persistsAfterInterrupt: true,
        metadata: {
          extendsResolutionHorizon: true,
        },
      },
      {
        type: "condition",
        condition: "Burning",
        stacks: 1,
        duration: 8,
        actorType: "player",
        atMs: 1162,
        timingAnchor: "castStart",
        timingScale: "fixed",
        persistsAfterInterrupt: true,
      },
      {
        type: "condition",
        condition: "Chilled",
        stacks: 1,
        duration: 2,
        actorType: "player",
        atMs: 1162,
        timingAnchor: "castStart",
        timingScale: "fixed",
        persistsAfterInterrupt: true,
      },
    ],
  },
  [ID.ABYSSAL_STRIKE]: {
    implemented: true,
    handlerId: "revenant.spear-recharge",
    quicknessCastTimeMs: 520,
    interruptCommitMs: 396,
    cooldown: 0,
    energyCost: 0,
    nextChainId: null,
    effects: [
      {
        type: "strike",
        coefficient: 0.85,
        hits: 1,
        name: "Abyssal Strike",
        actorType: "player",
        atMs: 396,
        timingAnchor: "castStart",
        timingScale: "fixed",
        persistsAfterInterrupt: true,
      },
      {
        type: "condition",
        condition: "Torment",
        stacks: 1,
        duration: 3,
        actorType: "player",
        atMs: 396,
        timingAnchor: "castStart",
        timingScale: "fixed",
        persistsAfterInterrupt: true,
      },
      {
        type: "condition",
        condition: "Vulnerability",
        stacks: 1,
        duration: 6,
        actorType: "player",
        atMs: 396,
        timingAnchor: "castStart",
        timingScale: "fixed",
        persistsAfterInterrupt: true,
      },
    ],
  },
  [ID.ABYSSAL_RAZE]: {
    implemented: true,
    handlerId: "revenant.abyssal-raze",
    quicknessCastTimeMs: 600,
    cooldown: 1,
    recharge: 1,
    ammo: 3,
    ammoRecharge: 15,
    energyCost: 8,
    effects: [],
  },
  [ID.BLITZ_MINES]: {
    implemented: true,
    castTimeMs: 0,
    cooldown: 0,
    energyCost: 0,
    effects: [
      {
        type: "strike",
        coefficient: 0.5,
        hits: 1,
        name: "Blitz Mines",
        actorType: "player",
      },
      {
        type: "condition",
        condition: "Slow",
        stacks: 1,
        duration: 3,
        actorType: "player",
      },
      {
        type: "condition",
        condition: "Weakness",
        stacks: 1,
        duration: 3,
        actorType: "player",
      },
    ],
  },
  [ID.REPLENISHING_DESPAIR_TRAIT_SKILL]: {
    implemented: true,
    castTimeMs: 0,
    cooldown: 0,
    energyCost: 0,
    effects: [
      {
        type: "strike",
        coefficient: 1.064,
        hits: 1,
        name: "Replenishing Despair (trait skill)",
        actorType: "player",
      },
    ],
  },
  [ID.UNYIELDING_IMPACT]: {
    implemented: true,
    quicknessCastTimeMs: 920,
    cooldown: 0,
    energyCost: 5,
    effects: [
      {
        type: "strike",
        coefficient: 1,
        hits: 1,
        name: "Unyielding Impact",
        actorType: "player",
        atMs: 557,
        timingAnchor: "castStart",
        timingScale: "fixed",
      },
      {
        type: "condition",
        condition: "Burning",
        stacks: 1,
        duration: 3,
        actorType: "player",
        atMs: 557,
        timingAnchor: "castStart",
        timingScale: "fixed",
      },
      {
        type: "condition",
        condition: "Torment",
        stacks: 4,
        duration: 3,
        actorType: "player",
        atMs: 557,
        timingAnchor: "castStart",
        timingScale: "fixed",
      },
      {
        type: "condition",
        condition: "Poisoned",
        stacks: 1,
        duration: 3,
        actorType: "player",
        atMs: 557,
        timingAnchor: "castStart",
        timingScale: "fixed",
      },
    ],
    legendId: "LegendaryDemon",
  },
  [ID.LEGENDARY_ENTITY_STANCE]: {
    implemented: true,
    castTimeMs: 0,
    cooldown: 0,
    energyCost: 0,
    effects: [],
  },
  [ID.PAIN_ABSORPTION_ID_78505]: {
    implemented: true,
    castTimeMs: 0,
    cooldown: 5,
    energyCost: 0,
    effects: [],
  },
  [ID.BANISH_ENCHANTMENT_ID_78587]: {
    implemented: true,
    castTimeMs: 0,
    cooldown: 5,
    energyCost: 0,
    effects: [],
  },
  [ID.EMPOWERING_MISERY_ID_78681]: {
    implemented: true,
    castTimeMs: 0,
    cooldown: 30,
    energyCost: 0,
    effects: [],
  },
});

const extraSkills: readonly Skill[] = [
  {
    id: ID.SWAP_WEAPONS,
    handlerId: "revenant.weapon-swap",
    name: "Swap Weapons",
    description: "Swap equipped weapon sets.",
    icon: "https://wiki.guildwars2.com/images/c/ce/Weapon_Swap_Button.png",
    type: "Action",
    slot: "Action",
    castTimeMs: 0,
    cooldown: 10,
    rechargeAnchor: "castStart",
    implemented: true,
    effects: [],
  },
  {
    id: ID.SWAP_LEGENDS,
    handlerId: "revenant.legend-swap",
    name: "Swap Legends",
    description: "Invoke the other selected legend and reset energy.",
    icon: "",
    type: "Profession",
    slot: "Profession_1",
    castTimeMs: 0,
    cooldown: 10,
    implemented: true,
    effects: [],
  },
  {
    id: ID.DODGE,
    handlerId: "revenant.dodge",
    name: "Dodge",
    description: "Perform the selected dodge.",
    icon: "https://wiki.guildwars2.com/images/b/b2/Dodge.png",
    type: "Action",
    slot: "Action",
    castTimeMs: 0,
    cooldown: 0,
    implemented: true,
    effects: [],
  },
];

export const REVENANT_CORE_EXTRA_SKILLS: readonly Skill[] = Object.freeze(
  extraSkills.map((skill) => Object.freeze(skill)),
);
