// Generated by scripts/data/generate-engineer-ids.mjs.
// Committed constants keep mechanic references stable across metadata loads.

export const ENGINEER_SKILL_IDS = Object.freeze({
  STOW_ELITE_MORTAR_KIT: -301,
  EVOLVE_BASE: 76642,
  EVOLVE_DOUBLE_HELIX: 76651,
  MED_KIT: 5802, // Med Kit
  GRENADE_KIT: 5805, // Grenade Kit
  BOMB_KIT: 5812, // Bomb Kit
  FRAGMENTATION_SHOT: 5827, // Fragmentation Shot
  POISON_DART_VOLLEY: 5828, // Poison Dart Volley
  STATIC_SHOT: 5829, // Static Shot
  GLUE_SHOT: 5830, // Glue Shot
  BLOWTORCH: 5831, // Blowtorch
  HEALING_TURRET: 5857, // Healing Turret
  SUPPLY_CRATE: 5868, // Supply Crate
  FLAMETHROWER: 5927, // Flamethrower
  ELIXIR_GUN: 5933, // Elixir Gun
  DETONATE_HEALING_TURRET: 5961, // Detonate Healing Turret
  RIFLE_BURST: 6003, // Rifle Burst
  NET_SHOT: 6004, // Net Shot
  JUMP_SHOT: 6005, // Jump Shot
  MAGNETIC_SHIELD: 6053, // Magnetic Shield
  STATIC_SHIELD: 6054, // Static Shield
  THROW_SHIELD: 6057, // Throw Shield
  STOW_MED_KIT: 6109, // Stow Med Kit
  STOW_GRENADE_KIT: 6110, // Stow Grenade Kit
  STOW_BOMB_KIT: 6111, // Stow Bomb Kit
  STOW_ELIXIR_GUN: 6115, // Stow Elixir Gun
  MAGNETIC_INVERSION: 6126, // Magnetic Inversion
  BLUNDERBUSS: 6153, // Blunderbuss
  OVERCHARGED_SHOT: 6154, // Overcharged Shot
  THROW_MINE: 6161, // Throw Mine
  DETONATE: 6162, // Detonate
  A_E_D: 21659, // A.E.D.
  NEGATIVE_BASH: 29785, // Negative Bash
  SHOCK_SHIELD: 29840, // Shock Shield
  SHREDDER_GYRO: 29921, // Shredder Gyro
  ELECTRO_WHIRL: 30088, // Electro-whirl
  MEDIC_GYRO: 30357, // Medic Gyro
  EQUALIZING_BLOW: 30489, // Equalizing Blow
  POSITIVE_STRIKE: 30501, // Positive Strike
  ROCKET_CHARGE: 30665, // Rocket Charge
  THUNDERCLAP: 30713, // Thunderclap
  ELITE_MORTAR_KIT: 30800, // Elite Mortar Kit
  SNEAK_GYRO: 30815, // Sneak Gyro
  BLAST_GYRO: 31248, // Blast Gyro
  RADIANT_ARC: 40160, // Radiant Arc
  COOLANT_BLAST: 40507, // Coolant Blast
  LAUNCH_WALL: 40533, // Launch Wall
  DEACTIVATE_PHOTON_FORGE: 41123, // Deactivate Photon Forge
  PRIME_LIGHT_BEAM: 42009, // Prime Light Beam
  LASER_DISK: 42842, // Laser Disk
  ENGAGE_PHOTON_FORGE: 42938, // Engage Photon Forge
  SUN_EDGE: 43476, // Sun Edge
  PHOTON_WALL: 43739, // Photon Wall
  REFRACTION_CUTTER: 44110, // Refraction Cutter
  SUN_RIPPER: 45581, // Sun Ripper
  GLEAM_SABER: 45979, // Gleam Saber
  FUNCTION_GYRO: 56920, // Function Gyro
  RECTIFIER_SIGNET: 63049, // Rectifier Signet
  MACE_SMASH: 63077, // Mace Smash
  OVERCLOCK_SIGNET: 63095, // Overclock Signet
  SHIFT_SIGNET: 63111, // Shift Signet
  SUPERCONDUCTING_SIGNET: 63113, // Superconducting Signet
  ENERGIZING_SLAM: 63169, // Energizing Slam
  MACE_BLAST: 63174, // Mace Blast
  MACE_STRIKE: 63186, // Mace Strike
  ROCKET_FIST_PROTOTYPE: 63234, // Rocket Fist Prototype
  FORCE_SIGNET: 63253, // Force Signet
  BARRIER_SIGNET: 63262, // Barrier Signet
  JADE_BUSTER_CANNON: 63374, // Jade Buster Cannon
  RIFLE_BURST_GRENADE: 68079, // Rifle Burst Grenade
  RADIANT_ARC_NON_HOLOSMITH: 69565, // Radiant Arc Non Holosmith
  SUN_RIPPER_NON_HOLOSMITH: 69906, // Sun Ripper Non Holosmith
  SUN_EDGE_NON_HOLOSMITH: 70514, // Sun Edge Non Holosmith
  GLEAM_SABER_NON_HOLOSMITH: 70771, // Gleam Saber Non Holosmith
  REFRACTION_CUTTER_NON_HOLOSMITH: 71121, // Refraction Cutter Non Holosmith
  ESSENCE_OF_LIQUID_WRATH: 71870, // Essence of Liquid Wrath
  ARC_DETONATOR: 71873, // Arc Detonator
  ESSENCE_OF_LIVING_SHADOWS: 71882, // Essence of Living Shadows
  ESSENCE_OF_BORROWED_TIME: 71888, // Essence of Borrowed Time
  ESSENCE_OF_ANIMATED_SAND: 72052, // Essence of Animated Sand
  PUNCTURING_JAB: 72944, // Puncturing Jab
  DEVASTATOR: 72974, // Devastator
  ROILING_SKIES: 72977, // Roiling Skies
  AMPLIFYING_SLICE: 73001, // Amplifying Slice
  LIGHTNING_ROD: 73002, // Lightning Rod
  FOCUSED_DEVASTATION: 73064, // Focused Devastation
  RENDING_STRIKE: 73109, // Rending Strike
  CONDUIT_SURGE: 73122, // Conduit Surge
  ELECTRIC_ARTILLERY: 73143, // Electric Artillery
  EVOLVE: 76642, // Evolve
  EVOLVE_ID_76651: 76651, // Evolve
  MITOTIC_STATE: 76738, // Mitotic State
  LOCKED: 76790, // Locked
  LIQUID_STATE: 76908, // Liquid State
  FLUX_STATE: 76993, // Flux State
  SOLID_STATE: 77069, // Solid State
  LOCKED_ID_77107: 77107, // Locked
  PLASMATIC_STATE: 77209, // Plasmatic State
  LOCKED_ID_77388: 77388, // Locked
  POISON_GRENADE: 5806, // Poison Grenade
  SHRAPNEL_GRENADE: 5807, // Shrapnel Grenade
  FLASH_GRENADE: 5808, // Flash Grenade
  FREEZE_GRENADE: 5809, // Freeze Grenade
  GRENADE_BARRAGE: 5810, // Grenade Barrage
  BIG_OL_BOMB: 5813, // Big Ol' Bomb
  GALVANIC_BOMB: 5822, // Galvanic Bomb
  FIRE_BOMB: 5823, // Fire Bomb
  SMOKE_BOMB_ENGINEER_SKILL: 5824, // Smoke Bomb (engineer skill)
  BOMB: 5842, // Bomb
  GRENADE: 5882, // Grenade
  FLAME_JET: 5928, // Flame Jet
  NAPALM: 5929, // Napalm
  AIR_BLAST: 5930, // Air Blast
  FLAME_BLAST: 5931, // Flame Blast
  TRANQUILIZER_DART: 5934, // Tranquilizer Dart
  GLOB_SHOT: 5935, // Glob Shot
  ACID_BOMB: 5936, // Acid Bomb
  SUPER_ELIXIR: 5937, // Super Elixir
  FUMIGATE: 5965, // Fumigate
  HEALING_MIST: 5966, // Healing Mist
  CLEANSING_BURST: 5980, // Cleansing Burst
  LESSER_GRENADE_BARRAGE: 6050, // Lesser Grenade Barrage
  SUPER_ELIXIR_CHAIN_SKILL: 6104, // Super Elixir (chain skill)
  STOW_FLAMETHROWER: 6114, // Stow Flamethrower
  SMOKE_VENT: 6159, // Smoke Vent
  DEPLOY_MINE: 6163, // Deploy Mine
  MINE_FIELD: 6164, // Mine Field
  DETONATE_MINE_FIELD: 6166, // Detonate Mine Field
  REGENERATING_MIST: 6176, // Regenerating Mist
  CONFUSING_SPEECH: 12334, // Confusing Speech
  VENT_RADIATION: 12336, // Vent Radiation
  HIDDEN_PISTOLS: 12357, // Hidden Pistols
  THROW_VINE: 12462, // Throw Vine
  LESSER_ELIXIR_B: 13465, // Lesser Elixir B
  STATIC_DISCHARGE_TRAIT_SKILL: 13552, // Static Discharge (trait skill)
  DROP_MINE: 17810, // Drop Mine
  MAGNETIC_BOMB_TRAIT_SKILL: 17811, // Magnetic Bomb (trait skill)
  SUPERSPEED_TRAIT_SKILL: 17812, // Superspeed (trait skill)
  FIRE_SHIELD_TRAIT_SKILL: 17813, // Fire Shield (trait skill)
  MAGNETIC_AURA_TRAIT_SKILL: 17814, // Magnetic Aura (trait skill)
  STATIC_SHOCK: 21661, // Static Shock
  BUNKER_DOWN_TRAIT_SKILL: 24329, // Bunker Down (trait skill)
  RECONSTRUCTION_FIELD: 29505, // Reconstruction Field
  DETONATE_SUPPLY_CRATE_TURRETS: 29518, // Detonate Supply Crate Turrets
  BANDAGE_BLAST: 29547, // Bandage Blast
  INVISIBLE_ANALYSIS: 29606, // Invisible Analysis
  BYPASS_COATING: 29665, // Bypass Coating
  CLEANSING_PULSE: 29712, // Cleansing Pulse
  MED_PACK_DROP: 29716, // Med Pack Drop
  BANDAGE_SELF: 29772, // Bandage Self
  LESSER_UTILITY_GOGGLES: 29812, // Lesser Utility Goggles
  AIM_ASSISTED_ROCKET_TRAIT_SKILL: 29889, // Aim-Assisted Rocket (trait skill)
  ELIXIR_SHELL: 30032, // Elixir Shell
  FLASH_SHELL: 30121, // Flash Shell
  BANDAGE_TRAIT_SKILL: 30142, // Bandage (trait skill)
  OVERCHARGE_SUPPLY_CRATE: 30264, // Overcharge Supply Crate
  ENDOTHERMIC_SHELL: 30307, // Endothermic Shell
  THROW_MINE_ID_30337: 30337, // Throw Mine
  MORTAR_SHOT: 30371, // Mortar Shot
  MED_BLASTER: 30521, // Med Blaster
  ORBITAL_STRIKE: 30599, // Orbital Strike
  POISON_GAS_SHELL: 30885, // Poison Gas Shell
  DEPLOY_MINE_ID_30893: 30893, // Deploy Mine
  SPARE_CAPACITOR: 31167, // Spare Capacitor
  ORBITAL_COMMAND_STRIKE: 41612, // Orbital Command Strike
  FLASH_CUTTER_STORM: 41684, // Flash Cutter—Storm
  BLADE_BURST: 42163, // Blade Burst
  BRIGHT_SLASH_STORM: 42475, // Bright Slash—Storm
  HOLOGRAPHIC_SHOCKWAVE: 42521, // Holographic Shockwave
  HOLO_LEAP: 42965, // Holo Leap
  VENT_EXHAUST: 43630, // Vent Exhaust
  CAUTERIZE: 43845, // Cauterize
  OVERHEAT: 43937, // Overheat
  LIGHT_STRIKE_STORM: 44260, // Light Strike—Storm
  HOLOFORGE_OVERHEATED: 44386, // Holoforge Overheated
  CORONA_BURST: 44530, // Corona Burst
  LIGHT_STRIKE: 44588, // Light Strike
  REFRACTION_CUTTER_BLADE: 45119, // Refraction Cutter Blade
  DEACTIVATE_PHOTON_FORGE_HOT: 45219, // Deactivate Photon Forge (hot)
  CONTROLLED_ANALYSIS: 45709, // Controlled Analysis
  PARTICLE_ACCELERATOR: 45732, // Particle Accelerator
  BRIGHT_SLASH: 45756, // Bright Slash
  PHOTON_BLITZ: 45783, // Photon Blitz
  FLASH_CUTTER: 45890, // Flash Cutter
  CLEANSING_FIELD: 49045, // Cleansing Field
  VITAL_BURST: 49082, // Vital Burst
  INFUSION_BOMB: 50444, // Infusion Bomb
  EXPLOSIVE_ENTRANCE_TRAIT_SKILL: 59562, // Explosive Entrance (trait skill)
  JADE_MORTAR: 63121, // Jade Mortar
  BARRIER_BURST: 63141, // Barrier Burst
  AERIAL_SUPPORT: 63172, // Aerial Support
  ROCKET_PUNCH_MECH: 63185, // Rocket Punch (Mech)
  SPARK_REVOLVER: 63188, // Spark Revolver
  SKY_CIRCUS: 63236, // Sky Circus
  HEAVY_SMASH_MECH: 63263, // Heavy Smash (Mech)
  JADE_ENERGY_SHOT: 63264, // Jade Energy Shot
  TWIN_STRIKE_MECH: 63288, // Twin Strike (Mech)
  CRISIS_ZONE: 63293, // Crisis Zone
  HARD_STRIKE: 63298, // Hard Strike
  ROLLING_SMASH: 63334, // Rolling Smash
  CORE_REACTOR_SHOT: 63345, // Core Reactor Shot
  JADE_ENERGY_SHOT_ID_63348: 63348, // Jade Energy Shot
  EXPLOSIVE_KNUCKLE: 63365, // Explosive Knuckle
  DISCHARGE_ARRAY: 63367, // Discharge Array
  STOKE_THE_FLAMES: 76493, // Stoke the Flames
  MAGNETIC_BOMB: 76530, // Magnetic Bomb
  OFFENSIVE_PROTOCOL_SHRED: 76568, // Offensive Protocol: Shred
  SYMBIOTIC_SHIELDING: 76613, // Symbiotic Shielding
  DEFENSIVE_PROTOCOL_THORNS: 76640, // Defensive Protocol: Thorns
  OFFENSIVE_PROTOCOL_DEMOLISH: 76693, // Offensive Protocol: Demolish
  OFFENSIVE_PROTOCOL_OBLITERATE: 76705, // Offensive Protocol: Obliterate
  DEFENSIVE_PROTOCOL_CLEANSE: 76713, // Defensive Protocol: Cleanse
  DEFENSIVE_PROTOCOL_CLEANSE_ID_76798: 76798, // Defensive Protocol: Cleanse
  OFFENSIVE_PROTOCOL_OBLITERATE_ID_76806: 76806, // Offensive Protocol: Obliterate
  OFFENSIVE_PROTOCOL_PIERCE: 76815, // Offensive Protocol: Pierce
  OFFENSIVE_PROTOCOL_SHRED_ID_76866: 76866, // Offensive Protocol: Shred
  OFFENSIVE_PROTOCOL_OBLITERATE_ID_76901: 76901, // Offensive Protocol: Obliterate
  OFFENSIVE_PROTOCOL_DEMOLISH_ID_76927: 76927, // Offensive Protocol: Demolish
  OFFENSIVE_PROTOCOL_DEMOLISH_ID_76954: 76954, // Offensive Protocol: Demolish
  DEFENSIVE_PROTOCOL_PROTECT: 76959, // Defensive Protocol: Protect
  OFFENSIVE_PROTOCOL_PIERCE_ID_77005: 77005, // Offensive Protocol: Pierce
  OFFENSIVE_PROTOCOL_PIERCE_ID_77015: 77015, // Offensive Protocol: Pierce
  OFFENSIVE_PROTOCOL_SHRED_ID_77103: 77103, // Offensive Protocol: Shred
  DEFENSIVE_PROTOCOL_THORNS_ID_77104: 77104, // Defensive Protocol: Thorns
  DEFENSIVE_PROTOCOL_THORNS_ID_77163: 77163, // Defensive Protocol: Thorns
  DEFENSIVE_PROTOCOL_PROTECT_ID_77203: 77203, // Defensive Protocol: Protect
  DEFENSIVE_PROTOCOL_CLEANSE_ID_77285: 77285, // Defensive Protocol: Cleanse
  DEFENSIVE_PROTOCOL_PROTECT_ID_77358: 77358 // Defensive Protocol: Protect
});

export const ENGINEER_TRAIT_IDS = Object.freeze({
  EXPLOSIVE_ENTRANCE: 432, // Explosive Entrance
  STEEL_PACKED_POWDER: 517, // Steel-Packed Powder
  SHAPED_CHARGE: 429, // Shaped Charge
  GRENADIER: 514, // Grenadier
  SHORT_FUSE: 525, // Short Fuse
  GLASS_CANNON: 1882, // Glass Cannon
  AIM_ASSISTED_ROCKET: 482, // Aim-Assisted Rocket
  EXPLOSIVE_TEMPER: 1892, // Explosive Temper
  BLAST_SHIELD: 1944, // Blast Shield
  GRAND_ENTRANCE: 1541, // Grand Entrance
  SHRAPNEL: 505, // Shrapnel
  BIG_BOOMER: 1947, // Big Boomer
  OPTIMIZED_ACTIVATION: 1979, // Optimized Activation
  MECHANIZED_DEPLOYMENT: 1872, // Mechanized Deployment
  EXCESSIVE_ENERGY: 1936, // Excessive Energy
  STATIC_DISCHARGE: 532, // Static Discharge
  REACTIVE_LENSES: 1997, // Reactive Lenses
  POWER_WRENCH: 531, // Power Wrench
  STREAMLINED_KITS: 512, // Streamlined Kits
  LOCK_ON: 1946, // Lock On
  TAKEDOWN_ROUND: 1832, // Takedown Round
  KINETIC_BATTERY: 1856, // Kinetic Battery
  ADRENAL_IMPLANT: 523, // Adrenal Implant
  GADGETEER: 1679, // Gadgeteer
  HIDDEN_FLASK: 468, // Hidden Flask
  TRANSMUTE: 487, // Transmute
  COMPOUNDING_CHEMICALS: 413, // Compounding Chemicals
  INVIGORATING_SPEED: 396, // Invigorating Speed
  PROTECTION_INJECTION: 509, // Protection Injection
  HEALTH_INSURANCE: 521, // Health Insurance
  COMEBACK_CURE: 520, // Comeback Cure
  BOILING_POINT: 469, // Boiling Point
  BLAST_ZONE: 470, // Blast Zone
  HGH: 473, // HGH
  EQUAL_AND_OPPOSITE_REACTION: 1871, // Equal and Opposite Reaction
  CHAIN_REACTIVITY: 1854, // Chain Reactivity
  SERRATED_STEEL: 515, // Serrated Steel
  HEMATIC_FOCUS: 536, // Hematic Focus
  MODIFIED_AMMUNITION: 516, // Modified Ammunition
  CHEMICAL_ROUNDS: 1878, // Chemical Rounds
  SANGUINE_ARRAY: 1930, // Sanguine Array
  HIGH_CALIBER: 1914, // High Caliber
  JUGGERNAUT: 1984, // Juggernaut
  THERMAL_VISION: 2006, // Thermal Vision
  NO_SCOPE: 1923, // No Scope
  HEAVY_METAL: 510, // Heavy Metal
  SHARPSHOOTER: 526, // Sharpshooter
  INCENDIARY_POWDER: 433, // Incendiary Powder
  FUNCTION_GYRO: 1959, // Function Gyro
  SPEED_OF_SYNERGY: 2014, // Speed of Synergy
  IMPACT_SAVANT: 1877, // Impact Savant
  GYROSCOPIC_ACCELERATION: 1917, // Gyroscopic Acceleration
  SYSTEM_SHOCKER: 1971, // System Shocker
  MASS_MOMENTUM: 1867, // Mass Momentum
  RAPID_REGENERATION: 1954, // Rapid Regeneration
  EXPERT_EXAMINATION: 1999, // Expert Examination
  OBJECT_IN_MOTION: 1860, // Object in Motion
  EX_MACHINA: 1981, // Ex Machina
  KINETIC_ACCELERATORS: 2052, // Kinetic Accelerators
  APPLIED_FORCE: 1849, // Applied Force
  CLEANSING_SYNERGY: 518, // Cleansing Synergy
  RECONSTRUCTION_ENCLOSURE: 508, // Reconstruction Enclosure
  ENERGY_AMPLIFIER: 519, // Energy Amplifier
  OVER_SHIELD: 394, // Over Shield
  AUTOMATED_MEDICAL_RESPONSE: 1901, // Automated Medical Response
  SAPPING_DEVICE: 507, // Sapping Device
  EXPERIMENTAL_TURRETS: 1678, // Experimental Turrets
  SOOTHING_DETONATION: 1834, // Soothing Detonation
  MECHA_LEGS: 445, // Mecha Legs
  ANTICORROSION_PLATING: 472, // Anticorrosion Plating
  BUNKER_DOWN: 1680, // Bunker Down
  MEDICAL_DISPERSION_FIELD: 1916, // Medical Dispersion Field
  PHOTON_PROJECTOR: 2158, // Photon Projector
  HEAT_THERAPY: 2135, // Heat Therapy
  LASERS_EDGE: 2122, // Laser's Edge
  LIGHT_DENSITY_AMPLIFIER: 2114, // Light Density Amplifier
  PRISMATIC_CONVERTER: 2157, // Prismatic Converter
  SOLAR_FOCUSING_LENS: 2106, // Solar Focusing Lens
  CRYSTAL_CONFIGURATION_STORM: 2103, // Crystal Configuration: Storm
  CRYSTAL_CONFIGURATION_ECLIPSE: 2152, // Crystal Configuration: Eclipse
  CRYSTAL_CONFIGURATION_ZEPHYR: 2091, // Crystal Configuration: Zephyr
  THERMAL_RELEASE_VALVE: 2066, // Thermal Release Valve
  ENHANCED_CAPACITY_STORAGE_UNIT: 2137, // Enhanced Capacity Storage Unit
  PHOTONIC_BLASTING_MODULE: 2064, // Photonic Blasting Module
  MECHANICAL_GENIUS: 2291, // Mechanical Genius
  MECH_FIGHTER: 2266, // Mech Fighter
  EXIGENCY_PROTOCOLS: 2267, // Exigency Protocols
  MECH_ARMS_SINGLE_EDGE_CUTTERS: 2282, // Mech Arms: Single-Edge Cutters
  MECH_ARMS_HIGH_IMPACT_DRIVERS: 2296, // Mech Arms: High-Impact Drivers
  MECH_ARMS_JADE_CANNONS: 2279, // Mech Arms: Jade Cannons
  MECH_FRAME_CONDUCTIVE_ALLOYS: 2270, // Mech Frame: Conductive Alloys
  MECH_FRAME_CHANNELING_CONDUITS: 2276, // Mech Frame: Channeling Conduits
  MECH_FRAME_VARIABLE_MASS_DISTRIBUTOR: 2294, // Mech Frame: Variable Mass Distributor
  MECH_CORE_JADE_DYNAMO: 2292, // Mech Core: Jade Dynamo
  MECH_CORE_BARRIER_ENGINE: 2281, // Mech Core: Barrier Engine
  MECH_CORE_J_DRIVE: 2298, // Mech Core: J-Drive
  EXPERIMENTAL_UNION: 2377, // Experimental Union
  HYBRID_VIGOR: 2389, // Hybrid Vigor
  WILLING_HOST: 2356, // Willing Host
  STAINLESS_STEEL: 2366, // Stainless Steel
  INNERVATING_ALLOY: 2395, // Innervating Alloy
  HARDENED_CHROME: 2434, // Hardened Chrome
  CARBOLIC_COMPOSITION: 2383, // Carbolic Composition
  MERCURIAL_TENDENCIES: 2420, // Mercurial Tendencies
  SILVER_LINING: 2349, // Silver Lining
  SYMBIOTIC_SYNERGY: 2406, // Symbiotic Synergy
  NEW_GENES: 2387, // New Genes
  DOUBLE_HELIX: 2334 // Double Helix
});
