import type { Skill } from '../../../platform/engine/types.js';
import { reconstructConduitDpsReportActions } from './revenant/conduit.js';
import { reconstructHeraldDpsReportActions } from './revenant/herald.js';
import { reconstructRenegadeDpsReportActions } from './revenant/renegade.js';
import type {
  DpsReportProfessionActionReconstructor,
  DpsReportProfessionReconstructionContext,
  DpsReportRecordedAction
} from '../types.js';

const specializationReconstructors: ReadonlyMap<string, DpsReportProfessionActionReconstructor> = new Map([
  ['conduit', reconstructConduitDpsReportActions],
  ['herald', reconstructHeraldDpsReportActions],
  ['renegade', reconstructRenegadeDpsReportActions]
]);
const LEGEND_STANCE_NAME = /^legendary .+ stance$/;
const SONG_OF_THE_MISTS_SIGNAL = /^call of the (alliance|assassin|centaur|demon|dragon|dwarf|renegade)$/;

function normalized(value: unknown): string {
  return String(value || '')
    .trim()
    .toLowerCase();
}

function actionSkill(action: DpsReportRecordedAction, context: DpsReportProfessionReconstructionContext): Skill | null {
  const id = action.canonicalSkillId ?? action.rawSkillId;
  const name = action.canonicalName ?? action.rawName;
  return (
    context.catalog?.skills.find(
      (skill) =>
        (typeof skill.id === 'number' && Number(skill.id) === Number(id)) || normalized(skill.name) === normalized(name)
    ) || null
  );
}

function normalizeLegendSwaps(
  context: DpsReportProfessionReconstructionContext,
  actions: readonly DpsReportRecordedAction[]
): DpsReportRecordedAction[] {
  return actions.map((action) =>
    LEGEND_STANCE_NAME.test(normalized(action.rawName))
      ? {
          ...action,
          eventIndex: Math.max(
            action.eventIndex,
            ...actions
              .filter(
                (candidate) =>
                  candidate !== action &&
                  Math.abs(candidate.start - action.start) <= 1 &&
                  actionSkill(candidate, context)?.handlerId === 'revenant.upkeep-release'
              )
              .map((candidate) => candidate.eventIndex + 0.25)
          ),
          canonicalSkillId: -4,
          canonicalName: 'Swap Legends'
        }
      : action
  );
}

function normalizeRevenantAutoattacks(
  context: DpsReportProfessionReconstructionContext,
  actions: readonly DpsReportRecordedAction[]
): DpsReportRecordedAction[] {
  const sorted = [...actions].sort((left, right) => left.start - right.start || left.eventIndex - right.eventIndex);
  let activeChainRoot: number | null = null;
  let expectedSkillId: number | null = null;
  const result: DpsReportRecordedAction[] = [];
  for (const action of sorted) {
    const skill = actionSkill(action, context);
    const autoattack = normalized(skill?.slot) === 'weapon_1';
    if (autoattack && action.status === 'interrupted') continue;
    const chainRoot = Number(skill?.chainRoot);
    if (autoattack && Number.isFinite(chainRoot)) {
      const rawSkillId = Number(skill?.id);
      const continuesChain = activeChainRoot === chainRoot && expectedSkillId != null;
      // EI normally reports the exact chain stage. Trust an explicit root reset,
      // while still repairing a truncated phase that starts on a later stage.
      const canonicalId: number =
        continuesChain && rawSkillId !== chainRoot && expectedSkillId != null
          ? expectedSkillId
          : activeChainRoot == null
            ? chainRoot
            : rawSkillId;
      const canonical: Skill | undefined = context.catalog?.skills.find(
        (candidate) => typeof candidate.id === 'number' && Number(candidate.id) === canonicalId
      );
      result.push({
        ...action,
        canonicalSkillId: canonicalId,
        canonicalName: canonical?.name || action.canonicalName || action.rawName
      });
      activeChainRoot = chainRoot;
      const next: number | null = canonical?.nextChainId == null ? null : Number(canonical.nextChainId);
      expectedSkillId = next != null && Number.isFinite(next) ? next : chainRoot;
      continue;
    }

    // Weapon and legend changes reset the equipped autoattack chain; ordinary
    // weapon/legend skills do not, so preserve EI's later chain stages across them.
    if (action.isSwap || skill?.handlerId === 'revenant.legend-swap') {
      activeChainRoot = null;
      expectedSkillId = null;
    }

    result.push(action);
  }

  return result;
}

/** Normalizes report legend changes before applying Revenant specialization recovery. */
export function reconstructRevenantDpsReportActions(
  context: DpsReportProfessionReconstructionContext
): readonly DpsReportRecordedAction[] {
  // Song of the Mists calls are generated by legend invocation in the simulator;
  // EI exposes them as inaccurate casts, so importing them would apply the proc twice.
  const withoutAutomaticCalls = context.recordedActions.filter(
    (action) => !SONG_OF_THE_MISTS_SIGNAL.test(normalized(action.rawName))
  );
  const common = normalizeLegendSwaps(context, withoutAutomaticCalls);
  const specialized = specializationReconstructors.get(context.profile.specializationId)?.({
    ...context,
    recordedActions: common
  }) || [...common];
  return normalizeRevenantAutoattacks({ ...context, recordedActions: specialized }, specialized);
}
