/**
 * Raw Troubadour skill mechanics. Generated once from the characterized
 * pre-migration table; this file is now the runtime source owner.
 */
import { MESMER_SKILL_IDS as ID } from "../../data/ids.js";
import type {
  Skill,
  SkillFragment,
  SkillId,
} from "../../../../platform/engine/types.js";
import type { MesmerSkill } from "../../types.js";

export const MESMER_TROUBADOUR_SKILL_MECHANICS: Readonly<
  Record<SkillId, SkillFragment>
> = Object.freeze({
  [ID.TROUBADOUR_BLADECALL]: {
    implemented: true,
    type: "Weapon",
    weapon: "Dagger",
    specialization: "Troubadour",
    environment: "Terrestrial",
    cooldown: 5,
    phantasm: false,
    resource: {
      mode: "add",
      count: 1,
    },
    blade: false,
    wikiUrl: "https://wiki.guildwars2.com/wiki/Bladecall",
    effects: [
      {
        type: "strike",
        ticks: [
          {
            atMs: 199,
            coefficient: 0.25,
          },
          {
            atMs: 199,
            coefficient: 0.25,
          },
          {
            atMs: 199,
            coefficient: 0.25,
          },
        ],
        name: "Outgoing damage",
        actorType: "player",
        weapon: "dagger",
        timingAnchor: "castStart",
        timingScale: "fixed",
      },
      {
        type: "strike",
        ticks: [
          {
            atMs: 2716,
            coefficient: 0.25,
          },
          {
            atMs: 2716,
            coefficient: 0.25,
          },
          {
            atMs: 2766,
            coefficient: 0.25,
          },
        ],
        name: "Returning damage",
        actorType: "player",
        weapon: "dagger",
        timingAnchor: "castStart",
        timingScale: "fixed",
      },
    ],
    castTimeMs: 660,
  },
  [ID.LIVELY_LUTE]: {
    implemented: true,
    type: "Profession",
    weapon: "",
    specialization: "Troubadour",
    environment: "Terrestrial",
    castTimeMs: 500,
    quicknessCastTimeMs: 333.333333333,
    cooldown: 12,
    phantasm: false,
    resource: null,
    blade: false,
    wikiUrl: "https://wiki.guildwars2.com/wiki/Lively_Lute",
    effects: [],
  },
  [ID.TALE_OF_THE_HONORABLE_ROGUE]: {
    implemented: true,
    type: "Utility",
    weapon: "",
    specialization: "Troubadour",
    environment: "Terrestrial",
    castTimeMs: 0,
    rechargeAnchor: "castStart",
    cooldown: 4,
    phantasm: false,
    resource: null,
    blade: false,
    wikiUrl: "https://wiki.guildwars2.com/wiki/Tale_of_the_Honorable_Rogue",
    effects: [],
  },
  [ID.TALE_OF_THE_SECOND_SCION]: {
    implemented: true,
    type: "Heal",
    weapon: "",
    specialization: "Troubadour",
    environment: "Terrestrial",
    castTimeMs: 1000,
    quicknessCastTimeMs: 666.666666667,
    cooldown: 15,
    phantasm: false,
    resource: null,
    blade: false,
    wikiUrl: "https://wiki.guildwars2.com/wiki/Tale_of_the_Second_Scion",
    effects: [],
  },
  [ID.FLUSTERING_FLUTE]: {
    implemented: true,
    type: "Profession",
    weapon: "",
    specialization: "Troubadour",
    environment: "Terrestrial",
    castTimeMs: 500,
    quicknessCastTimeMs: 333.333333333,
    cooldown: 20,
    phantasm: false,
    resource: null,
    blade: false,
    wikiUrl: "https://wiki.guildwars2.com/wiki/Flustering_Flute",
    effects: [],
  },
  [ID.TALE_OF_THE_SOULKEEPER]: {
    implemented: true,
    type: "Utility",
    weapon: "",
    specialization: "Troubadour",
    environment: "Terrestrial",
    castTimeMs: 0,
    rechargeAnchor: "castStart",
    cooldown: 20,
    phantasm: false,
    resource: null,
    blade: false,
    wikiUrl: "https://wiki.guildwars2.com/wiki/Tale_of_the_Soulkeeper",
    effects: [],
  },
  [ID.CRESCENDO]: {
    implemented: true,
    type: "Profession",
    weapon: "",
    specialization: "Troubadour",
    environment: "Terrestrial",
    castTimeMs: 1250,
    quicknessCastTimeMs: 833.333333333,
    cooldown: 35,
    baseCoefficient: 2.25,
    instrumentDamageIncrease: 0.25,
    phantasm: false,
    resource: null,
    blade: false,
    wikiUrl: "https://wiki.guildwars2.com/wiki/Crescendo",
    effects: [],
  },
  [ID.HARMONIOUS_HARP]: {
    implemented: true,
    type: "Profession",
    weapon: "",
    specialization: "Troubadour",
    environment: "Terrestrial",
    castTimeMs: 2000,
    quicknessCastTimeMs: 1333.333333333,
    cooldown: 25,
    phantasm: false,
    resource: null,
    blade: false,
    wikiUrl: "https://wiki.guildwars2.com/wiki/Harmonious_Harp",
    effects: [],
  },
  [ID.TALE_OF_THE_AUGUST_QUEEN]: {
    implemented: true,
    type: "Elite",
    weapon: "",
    specialization: "Troubadour",
    environment: "Terrestrial",
    castTimeMs: 1000,
    quicknessCastTimeMs: 666.666666667,
    cooldown: 75,
    phantasm: false,
    resource: null,
    blade: false,
    wikiUrl: "https://wiki.guildwars2.com/wiki/Tale_of_the_August_Queen",
    effects: [],
  },
  [ID.TALE_OF_THE_TORTURED_MASTERMIND]: {
    implemented: true,
    type: "Utility",
    weapon: "",
    specialization: "Troubadour",
    environment: "Terrestrial",
    castTimeMs: 500,
    quicknessCastTimeMs: 333.333333333,
    cooldown: 20,
    phantasm: false,
    resource: null,
    blade: false,
    wikiUrl: "https://wiki.guildwars2.com/wiki/Tale_of_the_Tortured_Mastermind",
    effects: [
      {
        type: "strike",
        coefficient: 4,
        hits: 4,
        name: "Damage",
        actorType: "player",
        weapon: "utility",
      },
      {
        type: "condition",
        condition: "torment",
        duration: 8,
        stacks: 1,
      },
    ],
  },
  [ID.HARMONIOUS_HARP_ALTERNATE]: {
    implemented: true,
    type: "Profession",
    weapon: "",
    specialization: "Troubadour",
    environment: "Terrestrial",
    castTimeMs: 2000,
    quicknessCastTimeMs: 1333.333333333,
    cooldown: 25,
    phantasm: false,
    resource: null,
    blade: false,
    wikiUrl: "https://wiki.guildwars2.com/wiki/Harmonious_Harp",
    effects: [],
  },
  [ID.DEAFENING_DRUM]: {
    implemented: true,
    type: "Profession",
    weapon: "",
    specialization: "Troubadour",
    environment: "Terrestrial",
    castTimeMs: 250,
    quicknessCastTimeMs: 166.666666667,
    cooldown: 25,
    phantasm: false,
    resource: null,
    blade: false,
    wikiUrl: "https://wiki.guildwars2.com/wiki/Deafening_Drum",
    effects: [],
  },
  [ID.TALE_OF_THE_VALIANT_MARSHAL]: {
    implemented: true,
    type: "Utility",
    weapon: "",
    specialization: "Troubadour",
    environment: "Terrestrial",
    castTimeMs: 0,
    rechargeAnchor: "castStart",
    cooldown: 30,
    phantasm: false,
    resource: null,
    blade: false,
    wikiUrl: "https://wiki.guildwars2.com/wiki/Tale_of_the_Valiant_Marshal",
    effects: [],
  },
  [ID.LIVELY_LUTE_ALTERNATE]: {
    implemented: true,
    type: "Profession",
    weapon: "",
    specialization: "Troubadour",
    environment: "Terrestrial",
    castTimeMs: 500,
    quicknessCastTimeMs: 333.333333333,
    cooldown: 12,
    phantasm: false,
    resource: null,
    blade: false,
    wikiUrl: "https://wiki.guildwars2.com/wiki/Lively_Lute",
    effects: [],
  },
});

export const MESMER_TROUBADOUR_SUPPLEMENTAL_SKILL_MECHANICS: Readonly<
  Record<SkillId, SkillFragment>
> = Object.freeze({});

export const MESMER_TROUBADOUR_EXTRA_SKILLS: readonly Skill[] = Object.freeze(
  [] satisfies readonly MesmerSkill[],
);
