// Generated by scripts/generate-revenant-ids.mjs.
// Committed constants keep mechanic references stable across metadata loads.

export const REVENANT_SKILL_IDS = Object.freeze({
  SWAP_WEAPONS: -3,
  SWAP_LEGENDS: -4,
  DODGE: -5,
  VENGEFUL_HAMMERS: 26557, // Vengeful Hammers
  FACET_OF_STRENGTH: 26644, // Facet of Strength
  MANIFEST_TOXIN: 26666, // Manifest Toxin
  FORCED_ENGAGEMENT: 26679, // Forced Engagement
  RESIST_THE_DARKNESS: 26693, // Resist the Darkness
  UNRELENTING_ASSAULT: 26699, // Unrelenting Assault
  ANGUISH_SWIPE: 26730, // Anguish Swipe
  PROTECTIVE_SOLACE: 26821, // Protective Solace
  ENCHANTED_DAGGERS: 26937, // Enchanted Daggers
  RELEASE_HAMMERS: 26956, // Release Hammers
  FACET_OF_ELEMENTS: 27014, // Facet of Elements
  NATURAL_HARMONY: 27025, // Natural Harmony
  MISERY_SWIPE: 27066, // Misery Swipe
  DEATHSTRIKE: 27074, // Deathstrike
  GAZE_OF_DARKNESS: 27080, // Gaze of Darkness
  IMPOSSIBLE_ODDS: 27107, // Impossible Odds
  FACET_OF_LIGHT: 27220, // Facet of Light
  INFUSE_LIGHT: 27228, // Infuse Light
  PAIN_ABSORPTION: 27322, // Pain Absorption
  ENERGY_EXPULSION: 27356, // Energy Expulsion
  SOOTHING_STONE: 27372, // Soothing Stone
  BANISH_ENCHANTMENT: 27505, // Banish Enchantment
  DIMINISH_SOLACE: 27628, // Diminish Solace
  FIELD_OF_THE_MISTS: 27665, // Field of the Mists
  PURIFYING_ESSENCE: 27715, // Purifying Essence
  FACET_OF_CHAOS: 27760, // Facet of Chaos
  CALL_TO_ANGUISH: 27917, // Call to Anguish
  ECHOING_ERUPTION: 27964, // Echoing Eruption
  RITE_OF_THE_GREAT_DWARF: 27975, // Rite of the Great Dwarf
  PHASE_SMASH: 27976, // Phase Smash
  FRIGID_BLITZ: 28029, // Frigid Blitz
  CHAOTIC_RELEASE: 28075, // Chaotic Release
  LEGENDARY_DRAGON_STANCE: 28085, // Legendary Dragon Stance
  DROP_THE_HAMMER: 28110, // Drop the Hammer
  BURST_OF_STRENGTH: 28113, // Burst of Strength
  LEGENDARY_ASSASSIN_STANCE: 28134, // Legendary Assassin Stance
  LEGENDARY_CENTAUR_STANCE: 28195, // Legendary Centaur Stance
  EMPOWERING_MISERY: 28219, // Empowering Misery
  PHASE_TRAVERSAL: 28231, // Phase Traversal
  COALESCENCE_OF_RUIN: 28253, // Coalescence of Ruin
  CRYSTAL_HIBERNATION: 28262, // Crystal Hibernation
  EMBRACE_THE_DARKNESS: 28287, // Embrace the Darkness
  SEARING_FISSURE: 28357, // Searing Fissure
  FACET_OF_DARKNESS: 28379, // Facet of Darkness
  RELINQUISH_POWER: 28382, // Relinquish Power
  JADE_WINDS: 28406, // Jade Winds
  TEMPORAL_RIFT: 28409, // Temporal Rift
  LEGENDARY_DWARF_STANCE: 28419, // Legendary Dwarf Stance
  VENTARIS_WILL: 28427, // Ventari's Will
  SHACKLING_WAVE: 28472, // Shackling Wave
  LEGENDARY_DEMON_STANCE: 28494, // Legendary Demon Stance
  INSPIRING_REINFORCEMENT: 28516, // Inspiring Reinforcement
  HAMMER_BOLT: 28549, // Hammer Bolt
  DUELISTS_PREPARATION: 28571, // Duelist's Preparation
  DEATHSTRIKE_ID_28625: 28625, // Deathstrike
  RIFT_SLASH: 28964, // Rift Slash
  SURGE_OF_THE_MISTS: 28978, // Surge of the Mists
  REJUVENATING_ASSAULT: 29002, // Rejuvenating Assault
  PREPARATION_THRUST: 29057, // Preparation Thrust
  NATURAL_HARMONY_ID_29082: 29082, // Natural Harmony
  ENERGY_EXPULSION_ID_29114: 29114, // Energy Expulsion
  MENDERS_REBUKE: 29145, // Mender's Rebuke
  PROJECT_TRANQUILITY: 29148, // Project Tranquility
  RAPID_SWIPE: 29180, // Rapid Swipe
  PURIFYING_ESSENCE_ID_29197: 29197, // Purifying Essence
  RIPOSTING_SHADOWS: 29209, // Riposting Shadows
  CHILLING_ISOLATION: 29233, // Chilling Isolation
  BRUTAL_BLADE: 29256, // Brutal Blade
  WARDING_RIFT: 29288, // Warding Rift
  RENEWING_WAVE: 29321, // Renewing Wave
  FORCEFUL_BASH: 29331, // Forceful Bash
  FACET_OF_NATURE: 29371, // Facet of Nature
  ENVOY_OF_EXUBERANCE: 29386, // Envoy of Exuberance
  BLOODBANE_PATH: 40175, // Bloodbane Path
  ICERAZORS_IRE: 40485, // Icerazor's Ire
  SHATTERSHOT: 40497, // Shattershot
  DARKRAZORS_DARING: 41220, // Darkrazor's Daring
  SCORCHRAZOR: 41820, // Scorchrazor
  SEVENSHOT: 41829, // Sevenshot
  LEGENDARY_RENEGADE_STANCE: 41858, // Legendary Renegade Stance
  CITADEL_BOMBARDMENT: 42836, // Citadel Bombardment
  RAZORCLAWS_RAGE: 42949, // Razorclaw's Rage
  SPIRITCRUSH: 43993, // Spiritcrush
  HEROIC_COMMAND: 44076, // Heroic Command
  ORDERS_FROM_ABOVE: 45537, // Orders from Above
  BREAKRAZORS_BASTION: 45686, // Breakrazor's Bastion
  SOULCLEAVES_SUMMIT: 45773, // Soulcleave's Summit
  LEGENDARY_RENEGADE_STANCE_ID_46409: 46409, // Legendary Renegade Stance
  TRUE_NATURE: 51667, // True Nature
  TRUE_NATURE_ID_51675: 51675, // True Nature
  TRUE_NATURE_ID_51696: 51696, // True Nature
  TRUE_NATURE_ID_51713: 51713, // True Nature
  TRUE_NATURE_ID_51714: 51714, // True Nature
  ANCIENT_ECHO: 55029, // Ancient Echo
  SELFLESS_SPIRIT: 62680, // Selfless Spirit
  URN_OF_SAINT_VIKTOR: 62687, // Urn of Saint Viktor
  MIST_SLASH: 62688, // Mist Slash
  MIST_UNLEASHED: 62692, // Mist Unleashed
  BATTLE_DANCE: 62702, // Battle Dance
  SELFISH_SPIRIT: 62719, // Selfish Spirit
  ALLIANCE_TACTICS: 62729, // Alliance Tactics
  DROP_URN_OF_SAINT_VIKTOR: 62738, // Drop Urn of Saint Viktor
  ARCING_MISTS: 62752, // Arcing Mists
  ENERGY_MELD: 62757, // Energy Meld
  AWAKENING: 62796, // Awakening
  TRUE_STRIKE: 62828, // True Strike
  NOMADS_ADVANCE: 62832, // Nomad's Advance
  REAVERS_RAGE: 62878, // Reaver's Rage
  LEGENDARY_ALLIANCE_STANCE: 62891, // Legendary Alliance Stance
  PHANTOMS_ONSLAUGHT: 62895, // Phantom's Onslaught
  MIST_SWING: 62913, // Mist Swing
  IMPERIAL_GUARD: 62921, // Imperial Guard
  ETERNITYS_REQUIEM: 62929, // Eternity's Requiem
  TREE_SONG: 62941, // Tree Song
  SPEAR_OF_ARCHEMORUS: 62942, // Spear of Archemorus
  SCAVENGER_BURST: 62962, // Scavenger Burst
  BLOSSOMING_AURA: 71816, // Blossoming Aura
  DEACTIVATE_OTHERWORLDLY_BOND: 71858, // Deactivate Otherworldly Bond
  ACERBIC_CUT: 71930, // Acerbic Cut
  SERENE_SLASH: 71933, // Serene Slash
  MOTIVATING_WHIRL: 71942, // Motivating Whirl
  OTHERWORLDLY_BOND: 71952, // Otherworldly Bond
  ENERGY_MELD_ID_72058: 72058, // Energy Meld
  DETONATE_BLOSSOMING_AURA: 72109, // Detonate Blossoming Aura
  ICERAZORS_IRE_ID_72359: 72359, // Icerazor's Ire
  RAZORCLAWS_RAGE_ID_72363: 72363, // Razorclaw's Rage
  DARKRAZORS_DARING_ID_72366: 72366, // Darkrazor's Daring
  BREAKRAZORS_BASTION_ID_72389: 72389, // Breakrazor's Bastion
  ABYSSAL_FIRE: 72931, // Abyssal Fire
  ABYSSAL_BLITZ: 72938, // Abyssal Blitz
  ABYSSAL_BLOT: 72954, // Abyssal Blot
  ABYSSAL_FORCE: 72972, // Abyssal Force
  ABYSSAL_STRIKE: 73015, // Abyssal Strike
  ABYSSAL_RAZE: 73059, // Abyssal Raze
  UNYIELDING_IMPACT: 76503, // Unyielding Impact
  LEGENDARY_ENTITY_STANCE: 76610, // Legendary Entity Stance
  TWIN_MOON_SWEEP: 76968, // Twin Moon Sweep
  SHIELDING_HANDS: 77043, // Shielding Hands
  BEGUILING_HAZE: 77141, // Beguiling Haze
  BEGUILING_HAZE_ID_77159: 77159, // Beguiling Haze
  HEX_EATER_VORTEX: 77243, // Hex-Eater Vortex
  GLADIATORS_DEFENSE: 77291, // Gladiator's Defense
  COSMIC_WISDOM: 77371, // Cosmic Wisdom
  RELEASE_POTENTIAL_MONK: 78501, // Release Potential: Monk
  PAIN_ABSORPTION_ID_78505: 78505, // Pain Absorption
  BANISH_ENCHANTMENT_ID_78587: 78587, // Banish Enchantment
  RELEASE_POTENTIAL_MESMER: 78615, // Release Potential: Mesmer
  RELEASE_POTENTIAL_DERVISH: 78661, // Release Potential: Dervish
  EMPOWERING_MISERY_ID_78681: 78681, // Empowering Misery
  RELEASE_POTENTIAL_ASSASSIN: 78845, // Release Potential: Assassin
  RELEASE_POTENTIAL_WARRIOR: 78895, // Release Potential: Warrior
  LEGENDARY_DWARF_STANCE_ID_26650: 26650, // Legendary Dwarf Stance
  ELEMENTAL_BLAST: 27162, // Elemental Blast
  DOME_OF_THE_MISTS: 27198, // Dome of the Mists
  LEGENDARY_ASSASSIN_STANCE_ID_27659: 27659, // Legendary Assassin Stance
  LEGENDARY_CENTAUR_STANCE_ID_28141: 28141, // Legendary Centaur Stance
  LEGENDARY_DEMON_STANCE_ID_28376: 28376, // Legendary Demon Stance
  IGNITING_BRAND: 28692, // Igniting Brand
  SPEAR_OF_ANGUISH: 28714, // Spear of Anguish
  FRIGID_DISCHARGE: 28797, // Frigid Discharge
  DEVOUR_BRAND: 28815, // Devour Brand
  VENOMOUS_SPHERE: 28827, // Venomous Sphere
  RAPID_ASSAULT: 28915, // Rapid Assault
  RIFT_CONTAINMENT: 28930, // Rift Containment
  PROTECTIVE_SOLACE_ID_29310: 29310, // Protective Solace
  HEALING_ORB: 29373, // Healing Orb
  JADE_WINDS_ID_31294: 31294, // Jade Winds
  RITE_OF_THE_GREAT_DWARF_TRAIT_SKILL: 32588, // Rite of the Great Dwarf (trait skill)
  VENGEFUL_SNOWBALLS: 34198, // Vengeful Snowballs
  DISMISS_LIEUTENANT_SOULCLEAVE: 42752, // Dismiss Lieutenant Soulcleave
  ESSENCE_SAP_DOPPELGANGER: 44657, // Essence Sap (Doppelganger)
  CALL_OF_THE_DWARF: 46843, // Call of the Dwarf
  CALL_OF_THE_CENTAUR: 46847, // Call of the Centaur
  CALL_OF_THE_RENEGADE: 46849, // Call of the Renegade
  CALL_OF_THE_ASSASSIN: 46854, // Call of the Assassin
  CALL_OF_THE_DEMON: 46856, // Call of the Demon
  CALL_OF_THE_DRAGON: 46857, // Call of the Dragon
  UNCHAINED_DESOLATION: 47889, // Unchained Desolation
  LEGENDARY_PRISONER_STANCE: 48170, // Legendary Prisoner Stance
  RIFT_OF_PAIN: 50390, // Rift of Pain
  MISTSFIRE: 50395, // Mistsfire
  RECKONING_BLAST: 50410, // Reckoning Blast
  PORTAL_FIRE: 50456, // Portal Fire
  TORRENTIAL_MISTS: 50483, // Torrential Mists
  SOOTHING_STONE_ID_56661: 56661, // Soothing Stone
  FORCED_ENGAGEMENT_ID_56662: 56662, // Forced Engagement
  VENGEFUL_HAMMERS_ID_56752: 56752, // Vengeful Hammers
  RITE_OF_THE_GREAT_DWARF_ID_56773: 56773, // Rite of the Great Dwarf
  INSPIRING_REINFORCEMENT_ID_56841: 56841, // Inspiring Reinforcement
  INVOKE_TORMENT: 59591, // Invoke Torment
  SAINTS_SHIELD: 62689, // Saint's Shield
  DEATH_DROP: 62693, // Death Drop
  CALL_OF_THE_ALLIANCE: 62705, // Call of the Alliance
  PHANTOMS_ONSLAUGHT_ID_62713: 62713, // Phantom's Onslaught
  LEGENDARY_ALLIANCE_STANCE_ID_62749: 62749, // Legendary Alliance Stance
  IMPERIAL_IMPACT: 62859, // Imperial Impact
  OTHERWORLDLY_ATTRACTION_ALLY: 71827, // Otherworldly Attraction (ally)
  OTHERWORLDLY_ATTRACTION_ENEMY: 71880, // Otherworldly Attraction (enemy)
  BLITZ_MINES: 73149, // Blitz Mines
  REPLENISHING_DESPAIR_TRAIT_SKILL: 76497, // Replenishing Despair (trait skill)
  BEGUILING_HAZE_ID_76805: 76805, // Beguiling Haze
  FORM_OF_THE_DERVISH_ATTACK: 76818, // Form of the Dervish (Attack)
  BEGUILING_HAZE_ID_76917: 76917, // Beguiling Haze
  TWIN_MOON_SWEEP_ID_77001: 77001, // Twin Moon Sweep
  FORM_OF_THE_DERVISH_ATTACK_ELITE: 77116, // Form of the Dervish (Attack - Elite)
  DWARVEN_RETRIBUTION: 77920, // Dwarven Retribution
  LESSER_ENCHANTED_DAGGERS: 78971, // Lesser Enchanted Daggers
});

export const REVENANT_TRAIT_IDS = Object.freeze({
  INVOKERS_RAGE: 1778, // Invoker's Rage
  FEROCIOUS_AGGRESSION: 1758, // Ferocious Aggression
  CONTAINED_TEMPER: 1769, // Contained Temper
  CLEANSING_CHANNEL: 1732, // Cleansing Channel
  RISING_TIDE: 1761, // Rising Tide
  GLARING_RESOLVE: 1784, // Glaring Resolve
  SPIRIT_BOON: 1774, // Spirit Boon
  RAPID_FLOW: 1760, // Rapid Flow
  INCENSED_RESPONSE: 1781, // Incensed Response
  SONG_OF_THE_MISTS: 1749, // Song of the Mists
  CHARGED_MISTS: 1791, // Charged Mists
  ROILING_MISTS: 1719, // Roiling Mists
  ENDURING_RECOVERY: 1783, // Enduring Recovery
  UNWAVERING_AVOIDANCE: 1757, // Unwavering Avoidance
  DETERMINED_RESOLUTION: 1713, // Determined Resolution
  PLANAR_PROTECTION: 1811, // Planar Protection
  CLOSE_QUARTERS: 1728, // Close Quarters
  SPIRITUAL_RECKONING: 1810, // Spiritual Reckoning
  SET_IN_STONE: 1766, // Set in Stone
  RESOLUTE_EVASION: 1782, // Resolute Evasion
  DWARVEN_BATTLE_TRAINING: 1740, // Dwarven Battle Training
  VICIOUS_REPRISAL: 1779, // Vicious Reprisal
  VERSED_IN_STONE: 1770, // Versed in Stone
  STEADFAST_REJUVENATION: 1790, // Steadfast Rejuvenation
  HEALERS_GIFT: 1816, // Healer's Gift
  LIFE_ATTUNEMENT: 1821, // Life Attunement
  SERENE_REJUVENATION: 1814, // Serene Rejuvenation
  INVOKING_HARMONY: 1823, // Invoking Harmony
  BLINDING_TRUTHS: 1824, // Blinding Truths
  ELUDING_NULLIFICATION: 1822, // Eluding Nullification
  WORDS_OF_CENSURE: 1819, // Words of Censure
  RESILIENT_SPIRIT: 1817, // Resilient Spirit
  FORTIFIED_BLESSING: 1818, // Fortified Blessing
  GENEROUS_ABUNDANCE: 1815, // Generous Abundance
  UNYIELDING_DEVOTION: 1825, // Unyielding Devotion
  INVIGORATING_DISMISSAL: 1820, // Invigorating Dismissal
  INVOKING_TORMENT: 1799, // Invoking Torment
  SEETHING_MALICE: 1801, // Seething Malice
  YEARNING_EMPOWERMENT: 1744, // Yearning Empowerment
  ACOLYTE_OF_TORMENT: 1793, // Acolyte of Torment
  DEMONIC_DEFIANCE: 1789, // Demonic Defiance
  REPLENISHING_DESPAIR: 1741, // Replenishing Despair
  ABYSSAL_CHILL: 1727, // Abyssal Chill
  DEMONIC_RESISTANCE: 1726, // Demonic Resistance
  PACT_OF_PAIN: 1714, // Pact of Pain
  DIABOLIC_INFERNO: 1795, // Diabolic Inferno
  FIENDISH_TENACITY: 1720, // Fiendish Tenacity
  PERMEATING_PESTILENCE: 1721, // Permeating Pestilence
  EXPOSE_DEFENSES: 1808, // Expose Defenses
  DESTRUCTIVE_IMPULSES: 1724, // Destructive Impulses
  TARGETED_DESTRUCTION: 1792, // Targeted Destruction
  AGGRESSIVE_ARRIVAL: 1776, // Aggressive Arrival
  UNSUSPECTING_STRIKES: 1767, // Unsuspecting Strikes
  BATTLE_SCARRED: 1755, // Battle Scarred
  ASSASSINS_PRESENCE: 1786, // Assassin's Presence
  NOTORIETY: 1765, // Notoriety
  THRILL_OF_COMBAT: 1802, // Thrill of Combat
  BRUTALITY: 1715, // Brutality
  SWIFT_TERMINATION: 1800, // Swift Termination
  DANCE_OF_DEATH: 1754, // Dance of Death
  CRYSTAL_HARBINGER: 1777, // Crystal Harbinger
  DRACONIC_FORTITUDE: 1737, // Draconic Fortitude
  REINFORCED_POTENCY: 1788, // Reinforced Potency
  ELDERS_RESPITE: 1813, // Elder's Respite
  CORE_VALUE: 1806, // Core Value
  RISING_MOMENTUM: 1716, // Rising Momentum
  SHARED_EMPOWERMENT: 1738, // Shared Empowerment
  SHINING_ASPECTS: 1743, // Shining Aspects
  HARDENING_PERSISTENCE: 1730, // Hardening Persistence
  ELEVATED_COMPASSION: 1746, // Elevated Compassion
  DRACONIC_ECHO: 1772, // Draconic Echo
  FORCEFUL_PERSISTENCE: 1803, // Forceful Persistence
  AMBUSH_COMMANDER: 2181, // Ambush Commander
  ENDLESS_ENMITY: 2154, // Endless Enmity
  BRUTAL_MOMENTUM: 2142, // Brutal Momentum
  ASHEN_DEMEANOR: 2166, // Ashen Demeanor
  BLOOD_FURY: 2079, // Blood Fury
  WROUGHT_IRON_WILL: 2120, // Wrought-Iron Will
  BOLD_REVERSAL: 2133, // Bold Reversal
  HEARTPIERCER: 2092, // Heartpiercer
  ALL_FOR_ONE: 2108, // All for One
  VINDICATION: 2094, // Vindication
  LASTING_LEGACY: 2100, // Lasting Legacy
  RIGHTEOUS_REBEL: 2182, // Righteous Rebel
  TENACIOUS_RUIN: 2262, // Tenacious Ruin
  BALANCE_IN_DISCORD: 2254, // Balance in Discord
  EMPIRE_DIVIDED: 2229, // Empire Divided
  LEVIATHAN_STRENGTH: 2258, // Leviathan Strength
  AMNESTY_OF_SHING_JEA: 2248, // Amnesty of Shing Jea
  REDEMPTORS_SERMON: 2228, // Redemptor's Sermon
  REAVERS_CURSE: 2259, // Reaver's Curse
  ANGSIYANS_TRUST: 2243, // Angsiyan's Trust
  SONG_OF_ARBOREUM: 2255, // Song of Arboreum
  FORERUNNER_OF_DEATH: 2257, // Forerunner of Death
  VASSALS_OF_THE_EMPIRE: 2232, // Vassals of the Empire
  SAINT_OF_ZU_HELTZER: 2238, // Saint of zu Heltzer
  ENIGMATIC_CONNECTION: 2364, // Enigmatic Connection
  BOLSTERED_BONDS: 2331, // Bolstered Bonds
  NUMINOUS_GIFT: 2440, // Numinous Gift
  CONDUCTIVE_ARMAMENTS: 2390, // Conductive Armaments
  SHARED_WISDOM: 2355, // Shared Wisdom
  LINGERING_DETERMINATION: 2407, // Lingering Determination
  KINETIC_INSIGHT: 2411, // Kinetic Insight
  EXPANDED_CONSCIOUSNESS: 2358, // Expanded Consciousness
  ETHEREAL_PURIFICATION: 2416, // Ethereal Purification
  MISTFIRE: 2429, // Mistfire
  ENHANCED_EMBODIMENT: 2379, // Enhanced Embodiment
  FOUND_PURPOSE: 2352, // Found Purpose
});

export const REVENANT_SPECIALIZATION_IDS = Object.freeze({
  INVOCATION: 3, // Invocation
  RETRIBUTION: 9, // Retribution
  SALVATION: 12, // Salvation
  CORRUPTION: 14, // Corruption
  DEVASTATION: 15, // Devastation
  HERALD: 52, // Herald
  RENEGADE: 63, // Renegade
  VINDICATOR: 69, // Vindicator
  CONDUIT: 79, // Conduit
});

export const REVENANT_LEGEND_IDS = Object.freeze({
  ASSASSIN: "LegendaryAssassin",
  DEMON: "LegendaryDemon",
  DWARF: "LegendaryDwarf",
  CENTAUR: "LegendaryCentaur",
  DRAGON: "LegendaryDragon",
  RENEGADE: "LegendaryRenegade",
  ALLIANCE: "LegendaryAlliance",
  ENTITY: "LegendaryEntity",
});

export type RevenantLegendId =
  (typeof REVENANT_LEGEND_IDS)[keyof typeof REVENANT_LEGEND_IDS];
