/**
 * Renegade skill mechanics owned by the Renegade Revenant module.
 */
import { REVENANT_SKILL_IDS as ID } from "../../data/ids.js";
import type { SkillFragment } from "../../../../platform/engine/types.js";

export const RENEGADE_BASE_SKILL_MECHANICS: Readonly<
  Record<number, SkillFragment>
> = Object.freeze({
  [ID.ICERAZORS_IRE]: {
    implemented: true,
    handlerId: "revenant.band-together",
    castTimeMs: 520,
    unaffectedByQuickness: true,
    cooldown: 10,
    energyCost: 20,
    effects: [
      {
        type: "strike",
        coefficient: 6,
        hits: 3,
        name: "Icerazor's Ire",
        actorType: "player",
        atMs: 500,
        intervalMs: 161,
        intervalTimingScale: "fixed",
        timingAnchor: "castEnd",
        timingScale: "fixed",
        metadata: {
          extendsResolutionHorizon: true,
        },
      },
      {
        type: "condition",
        condition: "Vulnerability",
        stacks: 10,
        duration: 8,
        actorType: "player",
        atMs: 500,
        timingAnchor: "castEnd",
        timingScale: "fixed",
      },
      {
        type: "condition",
        condition: "Torment",
        stacks: 3,
        duration: 6,
        actorType: "player",
        atMs: 500,
        timingAnchor: "castEnd",
        timingScale: "fixed",
      },
      {
        type: "condition",
        condition: "Vulnerability",
        stacks: 5,
        duration: 8,
        actorType: "player",
        atMs: 500,
        timingAnchor: "castEnd",
        timingScale: "fixed",
      },
      {
        type: "condition",
        condition: "Immobilized",
        stacks: 1,
        duration: 2,
        actorType: "player",
        atMs: 822,
        timingAnchor: "castEnd",
        timingScale: "fixed",
      },
    ],
    legendId: "LegendaryRenegade",
  },
  [ID.DARKRAZORS_DARING]: {
    implemented: true,
    handlerId: "revenant.band-together",
    castTimeMs: 500,
    unaffectedByQuickness: true,
    cooldown: 12,
    energyCost: 25,
    effects: [
      {
        type: "strike",
        coefficient: 3,
        hits: 1,
        name: "Darkrazor's Daring",
        actorType: "player",
        atMs: 1000,
        timingAnchor: "castEnd",
        timingScale: "fixed",
      },
      {
        type: "boon",
        boon: "stability",
        duration: 1,
        stacks: 1,
      },
      {
        type: "boon",
        boon: "stability",
        duration: 6,
        stacks: 3,
        atMs: 1000,
        timingAnchor: "castEnd",
        timingScale: "fixed",
      },
      {
        type: "control",
        actorType: "player",
        atMs: 1000,
        timingAnchor: "castEnd",
        timingScale: "fixed",
        metadata: {
          controlKind: "daze",
          duration: 2,
          breakbar: 200,
        },
      },
    ],
    legendId: "LegendaryRenegade",
  },
  [ID.DISMISS_LIEUTENANT_SOULCLEAVE]: {
    implemented: true,
    handlerId: "revenant.upkeep-release",
    castTimeMs: 0,
    cooldown: 0,
    energyCost: 0,
    effects: [],
    flipParentId: ID.SOULCLEAVES_SUMMIT,
    legendId: "LegendaryRenegade",
  },
  [ID.CITADEL_BOMBARDMENT]: {
    implemented: true,
    castTimeMs: 600,
    unaffectedByQuickness: true,
    cooldown: 15,
    energyCost: 35,
    effects: [
      {
        type: "strike",
        name: "Citadel Bombardment",
        actorType: "player",
        ticks: [
          { atMs: 245, coefficient: 0.6 },
          { atMs: 359, coefficient: 0.6 },
          { atMs: 473, coefficient: 0.6 },
          { atMs: 559, coefficient: 0.6 },
          { atMs: 645, coefficient: 0.6 },
          { atMs: 760, coefficient: 0.6 },
          { atMs: 847, coefficient: 0.6 },
          { atMs: 959, coefficient: 0.6 },
          { atMs: 1075, coefficient: 0.6 },
          { atMs: 1196, coefficient: 0.6 },
        ],
        timingAnchor: "castEnd",
        timingScale: "fixed",
        metadata: {
          extendsResolutionHorizon: true,
        },
      },
      {
        type: "condition",
        actorType: "player",
        ticks: [
          { atMs: 245, condition: "Burning", stacks: 1, duration: 1 },
          { atMs: 359, condition: "Burning", stacks: 1, duration: 1 },
          { atMs: 473, condition: "Burning", stacks: 1, duration: 1 },
          { atMs: 559, condition: "Burning", stacks: 1, duration: 1 },
          { atMs: 645, condition: "Burning", stacks: 1, duration: 1 },
          { atMs: 760, condition: "Burning", stacks: 1, duration: 1 },
          { atMs: 847, condition: "Burning", stacks: 1, duration: 1 },
          { atMs: 959, condition: "Burning", stacks: 1, duration: 1 },
          { atMs: 1075, condition: "Burning", stacks: 1, duration: 1 },
          { atMs: 1196, condition: "Burning", stacks: 1, duration: 1 },
        ],
        timingAnchor: "castEnd",
        timingScale: "fixed",
      },
    ],
  },
  [ID.RAZORCLAWS_RAGE]: {
    implemented: true,
    handlerId: "revenant.band-together",
    castTimeMs: 500,
    cooldown: 15,
    energyCost: 25,
    effects: [
      {
        type: "strike",
        coefficient: 2,
        hits: 1,
        name: "Razorclaw's Rage",
        actorType: "player",
      },
      {
        type: "condition",
        condition: "Bleeding",
        stacks: 4,
        duration: 8,
        actorType: "player",
      },
    ],
    legendId: "LegendaryRenegade",
  },
  [ID.HEROIC_COMMAND]: {
    implemented: true,
    handlerId: "revenant.heroic-command",
    castTimeMs: 500,
    cooldown: 10,
    energyCost: 10,
    effects: [],
  },
  [ID.ORDERS_FROM_ABOVE]: {
    implemented: true,
    handlerId: "revenant.orders-from-above",
    castTimeMs: 0,
    cooldown: 20,
    energyCost: 20,
    effects: [],
  },
  [ID.BREAKRAZORS_BASTION]: {
    implemented: true,
    handlerId: "revenant.band-together",
    castTimeMs: 750,
    cooldown: 30,
    energyCost: 5,
    effects: [
      {
        type: "boon",
        boon: "resolution",
        duration: 2.5,
        stacks: 1,
      },
      {
        type: "boon",
        boon: "resolution",
        duration: 4,
        stacks: 1,
      },
    ],
    legendId: "LegendaryRenegade",
  },
  [ID.SOULCLEAVES_SUMMIT]: {
    implemented: true,
    handlerId: "revenant.upkeep",
    castTimeMs: 500,
    cooldown: 3,
    energyCost: 5,
    upkeepCost: 5,
    manualReleaseCooldown: 3,
    flipSkillId: ID.DISMISS_LIEUTENANT_SOULCLEAVE,
    effects: [],
    legendId: "LegendaryRenegade",
  },
  [ID.ICERAZORS_IRE_ID_72359]: {
    implemented: true,
    castTimeMs: 520,
    unaffectedByQuickness: true,
    cooldown: 10,
    energyCost: 20,
    effects: [
      {
        type: "strike",
        coefficient: 18,
        hits: 3,
        name: "Icerazor's Ire",
        actorType: "summon",
        atMs: 167,
        intervalMs: 167,
        timingAnchor: "castStart",
        timingScale: "cast",
      },
      {
        type: "condition",
        condition: "Vulnerability",
        stacks: 10,
        duration: 8,
        actorType: "summon",
      },
      {
        type: "condition",
        condition: "Torment",
        stacks: 3,
        duration: 6,
        actorType: "summon",
      },
      {
        type: "condition",
        condition: "Vulnerability",
        stacks: 5,
        duration: 8,
        actorType: "summon",
      },
      {
        type: "condition",
        condition: "Chilled",
        stacks: 1,
        duration: 1.5,
        actorType: "summon",
      },
    ],
    legendId: "LegendaryRenegade",
  },
  [ID.RAZORCLAWS_RAGE_ID_72363]: {
    implemented: true,
    castTimeMs: 500,
    cooldown: 15,
    energyCost: 25,
    effects: [
      {
        type: "strike",
        coefficient: 2,
        hits: 1,
        name: "Razorclaw's Rage",
        actorType: "player",
      },
      {
        type: "condition",
        condition: "Bleeding",
        stacks: 4,
        duration: 8,
        actorType: "player",
      },
      {
        type: "condition",
        condition: "Bleeding",
        stacks: 1,
        duration: 3,
        actorType: "player",
        atMs: 400,
        timingAnchor: "castStart",
        timingScale: "fixed",
      },
      {
        type: "condition",
        condition: "Torment",
        stacks: 3,
        duration: 6,
        actorType: "player",
        atMs: 600,
        timingAnchor: "castStart",
        timingScale: "fixed",
      },
    ],
    legendId: "LegendaryRenegade",
  },
  [ID.DARKRAZORS_DARING_ID_72366]: {
    implemented: true,
    castTimeMs: 500,
    unaffectedByQuickness: true,
    cooldown: 12,
    energyCost: 25,
    effects: [
      {
        type: "strike",
        coefficient: 3,
        hits: 1,
        name: "Darkrazor's Daring",
        actorType: "player",
        atMs: 1000,
        timingAnchor: "castEnd",
        timingScale: "fixed",
      },
      {
        type: "boon",
        boon: "stability",
        duration: 1,
        stacks: 1,
      },
      {
        type: "boon",
        boon: "stability",
        duration: 6,
        stacks: 3,
        atMs: 1000,
        timingAnchor: "castEnd",
        timingScale: "fixed",
      },
      {
        type: "control",
        actorType: "player",
        atMs: 1000,
        timingAnchor: "castEnd",
        timingScale: "fixed",
        metadata: {
          controlKind: "daze",
          duration: 2,
        },
      },
      {
        type: "boon",
        boon: "resistance",
        duration: 4,
        stacks: 1,
      },
      {
        type: "boon",
        boon: "protection",
        duration: 4,
        stacks: 1,
      },
    ],
    legendId: "LegendaryRenegade",
  },
  [ID.BREAKRAZORS_BASTION_ID_72389]: {
    implemented: true,
    castTimeMs: 750,
    cooldown: 30,
    energyCost: 5,
    effects: [
      {
        type: "boon",
        boon: "resolution",
        duration: 2.5,
        stacks: 1,
      },
      {
        type: "boon",
        boon: "resolution",
        duration: 4,
        stacks: 1,
      },
    ],
    legendId: "LegendaryRenegade",
  },
});
